DGRv2: ns3::DGRRouter Class Reference
ns3::DGRRouter Class Reference
An interface aggregated to a node to provide global routing info.
#include <dgr-router-interface.h>
Public Member Functions
DGRRouter ()
Create a Global Router class.
uint32_t DiscoverLSAs (void)
Walk the connected channels, discover the adjacent routers and build the associated number of Global Routing Link State Advertisements that this router can export.
Ipv4DGRRoutingTableEntry * GetInjectedRoute (uint32_t i)
Return the injected route indexed by i.
bool GetLSA (uint32_t n, DGRRoutingLSA &lsa) const
Get a Global Routing Link State Advertisements that this router has said that it can export.
uint32_t GetNInjectedRoutes (void)
Get the number of injected routes that have been added to the routing table.
uint32_t GetNumLSAs (void) const
Get the Number of Global Routing Link State Advertisements that this router can export.
Ipv4Address GetRouterId (void) const
Get the Router ID associated with this Global Router.
Ptr< Ipv4DGRRouting > GetRoutingProtocol (void)
Get the specific Global Routing Protocol used.
void InjectRoute (Ipv4Address network, Ipv4Mask networkMask)
Inject a route to be circulated to other routers as an external route.
void RemoveInjectedRoute (uint32_t i)
Withdraw a route from the global unicast routing table.
void SetRoutingProtocol (Ptr< Ipv4DGRRouting > routing)
Set the specific Global Routing Protocol to be used.
bool WithdrawRoute (Ipv4Address network, Ipv4Mask networkMask)
Withdraw a route from the global unicast routing table.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::list< Ipv4DGRRoutingTableEntry * > InjectedRoutes
container of Ipv4RoutingTableEntry
typedef std::list< Ipv4DGRRoutingTableEntry * >::const_iterator InjectedRoutesCI
Const Iterator to container of Ipv4RoutingTableEntry.
typedef std::list< Ipv4DGRRoutingTableEntry * >::iterator InjectedRoutesI
Iterator to container of Ipv4RoutingTableEntry.
typedef std::list< DGRRoutingLSA * > ListOfLSAs_t
container for the GlobalRoutingLSAs
Private Member Functions
DGRRouter (DGRRouter &sr)
Global Router copy construction is disallowed.
virtual ~DGRRouter ()
bool AnotherRouterOnLink (Ptr< NetDevice > nd) const
Checks for the presence of another router on the NetDevice.
bool BridgeHasAlreadyBeenVisited (Ptr< BridgeNetDevice > device) const
When recursively checking for devices on the link, check whether a given device has already been visited.
void BuildNetworkLSAs (NetDeviceContainer c)
Build one NetworkLSA for each net device talking to a network that we are the designated router for.
void ClearBridgesVisited (void) const
Clear the list of bridges visited on the link.
void ClearLSAs (void)
Clear list of LSAs.
virtual void DoDispose (void)
NetDeviceContainer FindAllNonBridgedDevicesOnLink (Ptr< Channel > ch) const
Return a container of all non-bridged NetDevices on a link.
Ipv4Address FindDesignatedRouterForLink (Ptr< NetDevice > ndLocal) const
Finds a designated router.
bool FindInterfaceForDevice (Ptr< Node > node, Ptr< NetDevice > nd, uint32_t &index) const
Given a node and a net device, find an IPV4 interface index that corresponds to that net device.
Ptr< NetDevice > GetAdjacent (Ptr< NetDevice > nd, Ptr< Channel > ch) const
Link through the given channel and find the net device that's on the other end.
void MarkBridgeAsVisited (Ptr< BridgeNetDevice > device) const
When recursively checking for devices on the link, mark a given device as having been visited.
Ptr< BridgeNetDevice > NetDeviceIsBridged (Ptr< NetDevice > nd) const
Decide whether or not a given net device is being bridged by a BridgeNetDevice.
DGRRouter & operator= (DGRRouter &sr)
Global Router assignment operator is disallowed.
void ProcessBridgedBroadcastLink (Ptr< NetDevice > nd, DGRRoutingLSA *pLSA, NetDeviceContainer &c)
Process a bridged broadcast link.
void ProcessBroadcastLink (Ptr< NetDevice > nd, DGRRoutingLSA *pLSA, NetDeviceContainer &c)
Process a generic broadcast link.
void ProcessPointToPointLink (Ptr< NetDevice > ndLocal, DGRRoutingLSA *pLSA)
Process a point to point link.
void ProcessSingleBroadcastLink (Ptr< NetDevice > nd, DGRRoutingLSA *pLSA, NetDeviceContainer &c)
Process a single broadcast link.
Private Attributes
std::vector< Ptr< BridgeNetDevice > > m_bridgesVisited
Container of bridges visited.
InjectedRoutes m_injectedRoutes
Routes we are exporting.
ListOfLSAs_t m_LSAs
database of GlobalRoutingLSAs
Ipv4Address m_routerId
router ID (its IPv4 address)
Ptr< Ipv4DGRRouting > m_routingProtocol
the Ipv4GlobalRouting in use
Detailed Description
An interface aggregated to a node to provide global routing info.
An interface aggregated to a node that provides global routing information to a global route manager. The presence of the interface indicates that the node is a router. The interface is the mechanism by which the router advertises its connections to neighboring routers. We're basically allowing the route manager to query for link state advertisements.
Definition at line 589 of file dgr-router-interface.h.
Member Typedef Documentation
InjectedRoutes
typedef std::list<Ipv4DGRRoutingTableEntry *> ns3::DGRRouter::InjectedRoutes private
container of Ipv4RoutingTableEntry
Definition at line 864 of file dgr-router-interface.h.
InjectedRoutesCI
typedef std::list<Ipv4DGRRoutingTableEntry*>::const_iterator ns3::DGRRouter::InjectedRoutesCI private
Const Iterator to container of Ipv4RoutingTableEntry.
Definition at line 865 of file dgr-router-interface.h.
InjectedRoutesI
typedef std::list<Ipv4DGRRoutingTableEntry*>::iterator ns3::DGRRouter::InjectedRoutesI private
Iterator to container of Ipv4RoutingTableEntry.
Definition at line 866 of file dgr-router-interface.h.
ListOfLSAs_t
typedef std::list<DGRRoutingLSA*> ns3::DGRRouter::ListOfLSAs_t private
container for the GlobalRoutingLSAs
Definition at line 858 of file dgr-router-interface.h.
Constructor & Destructor Documentation
DGRRouter() [1/2]
ns3::DGRRouter::DGRRouter ()
Create a Global Router class.
Definition at line 519 of file dgr-router-interface.cc.
References ns3::DGRRouteManager::AllocateRouterId(), and m_routerId.
~DGRRouter()
ns3::DGRRouter::~DGRRouter () private virtual
Definition at line 526 of file dgr-router-interface.cc.
References ClearLSAs().
DGRRouter() [2/2]
ns3::DGRRouter::DGRRouter (DGRRouter & sr) private
Global Router copy construction is disallowed.
Parameters
sr object to copy from.
Member Function Documentation
AnotherRouterOnLink()
bool ns3::DGRRouter::AnotherRouterOnLink (Ptr< NetDevice > nd) const private
Checks for the presence of another router on the NetDevice.
Given a node and an attached net device, take a look off in the channel to which the net device is attached and look for a node on the other side that has a GlobalRouter interface aggregated.
Parameters
nd NetDevice to scan
Returns
true if a router is found
Definition at line 1473 of file dgr-router-interface.cc.
References AnotherRouterOnLink(), BridgeHasAlreadyBeenVisited(), ns3::i, MarkBridgeAsVisited(), and NetDeviceIsBridged().
Referenced by AnotherRouterOnLink(), ProcessBridgedBroadcastLink(), and ProcessSingleBroadcastLink().
BridgeHasAlreadyBeenVisited()
bool ns3::DGRRouter::BridgeHasAlreadyBeenVisited (Ptr< BridgeNetDevice > device) const private
When recursively checking for devices on the link, check whether a given device has already been visited.
Parameters
device the bridge device to check
Returns
true if bridge has already been visited
Definition at line 1816 of file dgr-router-interface.cc.
References m_bridgesVisited.
Referenced by AnotherRouterOnLink(), FindAllNonBridgedDevicesOnLink(), and FindDesignatedRouterForLink().
BuildNetworkLSAs()
void ns3::DGRRouter::BuildNetworkLSAs (NetDeviceContainer c) private
Build one NetworkLSA for each net device talking to a network that we are the designated router for.
Parameters
c the devices.
Definition at line 1161 of file dgr-router-interface.cc.
References ns3::DGRRoutingLSA::AddAttachedRouter(), ClearBridgesVisited(), FindAllNonBridgedDevicesOnLink(), FindInterfaceForDevice(), ns3::i, ns3::DGRRoutingLSA::LSA_SPF_NOT_EXPLORED, m_LSAs, m_routerId, ns3::DGRRoutingLSA::NetworkLSA, ns3::DGRRoutingLSA::SetAdvertisingRouter(), ns3::DGRRoutingLSA::SetLinkStateId(), ns3::DGRRoutingLSA::SetLSType(), ns3::DGRRoutingLSA::SetNetworkLSANetworkMask(), ns3::DGRRoutingLSA::SetNode(), and ns3::DGRRoutingLSA::SetStatus().
Referenced by DiscoverLSAs().
ClearBridgesVisited()
void ns3::DGRRouter::ClearBridgesVisited (void) const private
Clear the list of bridges visited on the link.
Definition at line 1807 of file dgr-router-interface.cc.
References m_bridgesVisited.
Referenced by BuildNetworkLSAs(), ProcessBridgedBroadcastLink(), and ProcessSingleBroadcastLink().
ClearLSAs()
void ns3::DGRRouter::ClearLSAs (void) private
Clear list of LSAs.
Definition at line 560 of file dgr-router-interface.cc.
References ns3::i, and m_LSAs.
Referenced by ~DGRRouter(), and DiscoverLSAs().
DiscoverLSAs()
uint32_t ns3::DGRRouter::DiscoverLSAs (void)
Walk the connected channels, discover the adjacent routers and build the associated number of Global Routing Link State Advertisements that this router can export.
This is a fairly expensive operation in that every time it is called the current list of LSAs is built by walking connected point-to-point channels and peeking into adjacent IPV4 stacks to get address information. This is done to allow for limited dynamics of the Global Routing environment. By that we mean that you can discover new link state advertisements after a network topology change by calling DiscoverLSAs and then by reading those advertisements.
See also
GlobalRoutingLSA
GlobalRouter::GetLSA ()
Returns
The number of Global Routing Link State Advertisements.
Definition at line 593 of file dgr-router-interface.cc.
References ns3::DGRRoutingLSA::ASExternalLSAs, BuildNetworkLSAs(), ClearLSAs(), FindInterfaceForDevice(), ns3::i, ns3::DGRRoutingLSA::LSA_SPF_NOT_EXPLORED, m_injectedRoutes, m_LSAs, m_routerId, NetDeviceIsBridged(), ProcessBroadcastLink(), ProcessPointToPointLink(), ns3::DGRRoutingLSA::RouterLSA, ns3::DGRRoutingLSA::SetAdvertisingRouter(), ns3::DGRRoutingLSA::SetLinkStateId(), ns3::DGRRoutingLSA::SetLSType(), ns3::DGRRoutingLSA::SetNetworkLSANetworkMask(), ns3::DGRRoutingLSA::SetNode(), and ns3::DGRRoutingLSA::SetStatus().
DoDispose()
void ns3::DGRRouter::DoDispose (void) private virtual
Definition at line 546 of file dgr-router-interface.cc.
References m_injectedRoutes, and m_routingProtocol.
FindAllNonBridgedDevicesOnLink()
NetDeviceContainer ns3::DGRRouter::FindAllNonBridgedDevicesOnLink (Ptr< Channel > ch) const private
Return a container of all non-bridged NetDevices on a link.
This method will recursively find all of the 'edge' devices in an L2 broadcast domain. If there are no bridged devices, then the container returned is simply the set of devices on the channel passed in as an argument. If the link has bridges on it (and therefore multiple ns3::Channel objects interconnected by bridges), the method will find all of the non-bridged devices in the L2 broadcast domain.
Parameters
ch a channel from the link
Returns
the NetDeviceContainer.
Definition at line 1272 of file dgr-router-interface.cc.
References BridgeHasAlreadyBeenVisited(), FindAllNonBridgedDevicesOnLink(), ns3::i, MarkBridgeAsVisited(), and NetDeviceIsBridged().
Referenced by BuildNetworkLSAs(), and FindAllNonBridgedDevicesOnLink().
FindDesignatedRouterForLink()
Ipv4Address ns3::DGRRouter::FindDesignatedRouterForLink (Ptr< NetDevice > ndLocal) const private
Finds a designated router.
Given a local net device, we need to walk the channel to which the net device is attached and look for nodes with GlobalRouter interfaces on them (one of them will be us). Of these, the router with the lowest IP address on the net device connecting to the channel becomes the designated router for the link.
Parameters
ndLocal local NetDevice to scan
Returns
the IP address of the designated router
Definition at line 1317 of file dgr-router-interface.cc.
References BridgeHasAlreadyBeenVisited(), FindDesignatedRouterForLink(), FindInterfaceForDevice(), ns3::i, MarkBridgeAsVisited(), and NetDeviceIsBridged().
Referenced by FindDesignatedRouterForLink(), ProcessBridgedBroadcastLink(), and ProcessSingleBroadcastLink().
FindInterfaceForDevice()
bool ns3::DGRRouter::FindInterfaceForDevice (Ptr< Node > node, Ptr< NetDevice > nd, uint32_t & index) const private
Given a node and a net device, find an IPV4 interface index that corresponds to that net device.
This function may fail for various reasons. If a node does not have an internet stack (for example if it is a bridge) we won't have an IPv4 at all. If the node does have a stack, but the net device in question is bridged, there will not be an interface associated directly with the device.
Parameters
node the node
nd outgoing NetDevice
index the IPV4 interface index
Returns
true on success
Definition at line 1734 of file dgr-router-interface.cc.
References ns3::i.
Referenced by BuildNetworkLSAs(), DiscoverLSAs(), FindDesignatedRouterForLink(), ProcessBridgedBroadcastLink(), ProcessPointToPointLink(), and ProcessSingleBroadcastLink().
GetAdjacent()
Ptr< NetDevice > ns3::DGRRouter::GetAdjacent (Ptr< NetDevice > nd, Ptr< Channel > ch) const private
Link through the given channel and find the net device that's on the other end.
This only makes sense with a point-to-point channel.
Parameters
nd outgoing NetDevice
ch channel
Returns
the NetDevice on the other end
Definition at line 1696 of file dgr-router-interface.cc.
Referenced by ProcessPointToPointLink().
GetInjectedRoute()
Ipv4DGRRoutingTableEntry * ns3::DGRRouter::GetInjectedRoute (uint32_t i)
Return the injected route indexed by i.
Parameters
i the index of the route
Returns
a pointer to that Ipv4RoutingTableEntry is returned
Definition at line 1625 of file dgr-router-interface.cc.
References ns3::i, and m_injectedRoutes.
GetLSA()
bool ns3::DGRRouter::GetLSA (uint32_t n, DGRRoutingLSA & lsa) const
Get a Global Routing Link State Advertisements that this router has said that it can export.
This is a fairly inexpensive expensive operation in that the hard work was done in GetNumLSAs. We just copy the indicated Global Routing Link State Advertisement into the requested GlobalRoutingLSA object.
You must call GlobalRouter::GetNumLSAs before calling this method in order to discover the adjacent routers and build the advertisements. GetNumLSAs will return the number of LSAs this router advertises. The parameter n (requested LSA number) must be in the range 0 to GetNumLSAs() - 1.
See also
GlobalRoutingLSA
GlobalRouting::GetNumLSAs ()
Parameters
n The index number of the LSA you want to read.
lsa The GlobalRoutingLSA class to receive the LSA information.
Returns
The number of Global Router Link State Advertisements.
Definition at line 1585 of file dgr-router-interface.cc.
References ns3::i, ns3::DGRRoutingLSA::IsEmpty(), and m_LSAs.
GetNInjectedRoutes()
uint32_t ns3::DGRRouter::GetNInjectedRoutes (void)
Get the number of injected routes that have been added to the routing table.
Returns
number of injected routes
Definition at line 1648 of file dgr-router-interface.cc.
References m_injectedRoutes.
GetNumLSAs()
uint32_t ns3::DGRRouter::GetNumLSAs (void) const
Get the Number of Global Routing Link State Advertisements that this router can export.
To get meaningful information you must have previously called DiscoverLSAs. After you know how many LSAs are present in the router, you may call GetLSA () to retrieve the actual advertisement.
See also
GlobalRouterLSA
GlobalRouting::DiscoverLSAs ()
GlobalRouting::GetLSA ()
Returns
The number of Global Routing Link State Advertisements.
Definition at line 1575 of file dgr-router-interface.cc.
References m_LSAs.
GetRouterId()
Ipv4Address ns3::DGRRouter::GetRouterId (void) const
Get the Router ID associated with this Global Router.
The Router IDs are allocated in the RoutingEnvironment – one per Router, starting at 0.0.0.1 and incrementing with each instantiation of a router.
See also
RoutingEnvironment::AllocateRouterId ()
Returns
The Router ID associated with the Global Router.
Definition at line 580 of file dgr-router-interface.cc.
References m_routerId.
Referenced by ProcessPointToPointLink().
GetRoutingProtocol()
Ptr< Ipv4DGRRouting > ns3::DGRRouter::GetRoutingProtocol (void)
Get the specific Global Routing Protocol used.
Returns
the routing protocol
Definition at line 539 of file dgr-router-interface.cc.
References m_routingProtocol.
Referenced by ns3::DGRRouteManagerImpl::BuildDGRRoutingDatabase(), ns3::DGRRouteManagerImpl::DeleteDGRRoutes(), ns3::DGRRouteManagerImpl::InitializeRoutes(), ns3::DGRRouteManagerImpl::SPFAddASExternal(), ns3::DGRRouteManagerImpl::SPFIntraAddRouter(), ns3::DGRRouteManagerImpl::SPFIntraAddStub(), and ns3::DGRRouteManagerImpl::SPFIntraAddTransit().
GetTypeId()
TypeId ns3::DGRRouter::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 511 of file dgr-router-interface.cc.
InjectRoute()
void ns3::DGRRouter::InjectRoute (Ipv4Address network, Ipv4Mask networkMask)
Inject a route to be circulated to other routers as an external route.
Parameters
network The Network to inject
networkMask The Network Mask to inject
Definition at line 1611 of file dgr-router-interface.cc.
References ns3::Ipv4DGRRoutingTableEntry::CreateNetworkRouteTo(), and m_injectedRoutes.
MarkBridgeAsVisited()
void ns3::DGRRouter::MarkBridgeAsVisited (Ptr< BridgeNetDevice > device) const private
When recursively checking for devices on the link, mark a given device as having been visited.
Parameters
device the bridge device to mark
Definition at line 1834 of file dgr-router-interface.cc.
References m_bridgesVisited.
Referenced by AnotherRouterOnLink(), FindAllNonBridgedDevicesOnLink(), and FindDesignatedRouterForLink().
NetDeviceIsBridged()
Ptr< BridgeNetDevice > ns3::DGRRouter::NetDeviceIsBridged (Ptr< NetDevice > nd) const private
Decide whether or not a given net device is being bridged by a BridgeNetDevice.
Parameters
nd the NetDevice
Returns
the BridgeNetDevice smart pointer or null if not found
Definition at line 1764 of file dgr-router-interface.cc.
References ns3::i.
Referenced by AnotherRouterOnLink(), DiscoverLSAs(), FindAllNonBridgedDevicesOnLink(), and FindDesignatedRouterForLink().
operator=()
DGRRouter & ns3::DGRRouter::operator= (DGRRouter & sr) private
Global Router assignment operator is disallowed.
Parameters
sr object to copy from.
Returns
The object copied.
ProcessBridgedBroadcastLink()
void ns3::DGRRouter::ProcessBridgedBroadcastLink (Ptr< NetDevice > nd, DGRRoutingLSA * pLSA, NetDeviceContainer & c) private
Process a bridged broadcast link.
Parameters
nd the NetDevice
pLSA the Global LSA
c the returned NetDevice container
Definition at line 875 of file dgr-router-interface.cc.
References ns3::DGRRoutingLSA::AddLinkRecord(), AnotherRouterOnLink(), ClearBridgesVisited(), FindDesignatedRouterForLink(), FindInterfaceForDevice(), ns3::i, ns3::DGRRoutingLinkRecord::SetLinkData(), ns3::DGRRoutingLinkRecord::SetLinkId(), ns3::DGRRoutingLinkRecord::SetLinkType(), ns3::DGRRoutingLinkRecord::SetMetric(), ns3::DGRRoutingLinkRecord::StubNetwork, and ns3::DGRRoutingLinkRecord::TransitNetwork.
Referenced by ProcessBroadcastLink().
ProcessBroadcastLink()
void ns3::DGRRouter::ProcessBroadcastLink (Ptr< NetDevice > nd, DGRRoutingLSA * pLSA, NetDeviceContainer & c) private
Process a generic broadcast link.
Parameters
nd the NetDevice
pLSA the Global LSA
c the returned NetDevice container
Definition at line 746 of file dgr-router-interface.cc.
References ProcessBridgedBroadcastLink(), and ProcessSingleBroadcastLink().
Referenced by DiscoverLSAs().
ProcessPointToPointLink()
void ns3::DGRRouter::ProcessPointToPointLink (Ptr< NetDevice > ndLocal, DGRRoutingLSA * pLSA) private
Process a point to point link.
Parameters
ndLocal the NetDevice
pLSA the Global LSA
Definition at line 1040 of file dgr-router-interface.cc.
References ns3::DGRRoutingLSA::AddLinkRecord(), FindInterfaceForDevice(), GetAdjacent(), GetRouterId(), ns3::DGRRoutingLinkRecord::PointToPoint, ns3::DGRRoutingLinkRecord::SetLinkData(), ns3::DGRRoutingLinkRecord::SetLinkId(), ns3::DGRRoutingLinkRecord::SetLinkType(), ns3::DGRRoutingLinkRecord::SetMetric(), and ns3::DGRRoutingLinkRecord::StubNetwork.
Referenced by DiscoverLSAs().
ProcessSingleBroadcastLink()
void ns3::DGRRouter::ProcessSingleBroadcastLink (Ptr< NetDevice > nd, DGRRoutingLSA * pLSA, NetDeviceContainer & c) private
Process a single broadcast link.
Parameters
nd the NetDevice
pLSA the Global LSA
c the returned NetDevice container
Definition at line 761 of file dgr-router-interface.cc.
References ns3::DGRRoutingLSA::AddLinkRecord(), AnotherRouterOnLink(), ClearBridgesVisited(), FindDesignatedRouterForLink(), FindInterfaceForDevice(), ns3::DGRRoutingLinkRecord::SetLinkData(), ns3::DGRRoutingLinkRecord::SetLinkId(), ns3::DGRRoutingLinkRecord::SetLinkType(), ns3::DGRRoutingLinkRecord::SetMetric(), ns3::DGRRoutingLinkRecord::StubNetwork, and ns3::DGRRoutingLinkRecord::TransitNetwork.
Referenced by ProcessBroadcastLink().
RemoveInjectedRoute()
void ns3::DGRRouter::RemoveInjectedRoute (uint32_t i)
Withdraw a route from the global unicast routing table.
Calling this function will cause all indexed routes numbered above index i to have their index decremented. For instance, it is possible to remove N injected routes by calling RemoveInjectedRoute (0) N times.
Parameters
i The index (into the injected routing list) of the route to remove.
See also
GlobalRouter::WithdrawRoute ()
Definition at line 1655 of file dgr-router-interface.cc.
References ns3::i, and m_injectedRoutes.
SetRoutingProtocol()
void ns3::DGRRouter::SetRoutingProtocol (Ptr< Ipv4DGRRouting > routing)
Set the specific Global Routing Protocol to be used.
Parameters
routing the routing protocol
Definition at line 533 of file dgr-router-interface.cc.
References m_routingProtocol.
WithdrawRoute()
bool ns3::DGRRouter::WithdrawRoute (Ipv4Address network, Ipv4Mask networkMask)
Withdraw a route from the global unicast routing table.
Parameters
network The Network to withdraw
networkMask The Network Mask to withdraw
Returns
whether the operation succeeded (will return false if no such route)
See also
GlobalRouter::RemoveInjectedRoute ()
Definition at line 1674 of file dgr-router-interface.cc.
References ns3::i, and m_injectedRoutes.
Member Data Documentation
m_bridgesVisited
std::vector<Ptr<BridgeNetDevice> > ns3::DGRRouter::m_bridgesVisited mutable private
Container of bridges visited.
Definition at line 874 of file dgr-router-interface.h.
Referenced by BridgeHasAlreadyBeenVisited(), ClearBridgesVisited(), and MarkBridgeAsVisited().
m_injectedRoutes
InjectedRoutes ns3::DGRRouter::m_injectedRoutes private
Routes we are exporting.
Definition at line 867 of file dgr-router-interface.h.
Referenced by DiscoverLSAs(), DoDispose(), GetInjectedRoute(), GetNInjectedRoutes(), InjectRoute(), RemoveInjectedRoute(), and WithdrawRoute().
m_LSAs
ListOfLSAs_t ns3::DGRRouter::m_LSAs private
database of GlobalRoutingLSAs
Definition at line 859 of file dgr-router-interface.h.
Referenced by BuildNetworkLSAs(), ClearLSAs(), DiscoverLSAs(), GetLSA(), and GetNumLSAs().
m_routerId
Ipv4Address ns3::DGRRouter::m_routerId private
router ID (its IPv4 address)
Definition at line 861 of file dgr-router-interface.h.
Referenced by DGRRouter(), BuildNetworkLSAs(), DiscoverLSAs(), and GetRouterId().
m_routingProtocol
Ptr<Ipv4DGRRouting> ns3::DGRRouter::m_routingProtocol private
the Ipv4GlobalRouting in use
Definition at line 862 of file dgr-router-interface.h.
Referenced by DoDispose(), GetRoutingProtocol(), and SetRoutingProtocol().
The documentation for this class was generated from the following files:
model/dgr-router-interface.h
model/dgr-router-interface.cc