DGRv2: ns3::DGRApplicationHelper Class Reference
ns3::DGRApplicationHelper Class Reference
PacketSink
A helper to make it easier to instantiate an ns3::PacketSinkApplication on a set of nodes.
#include <dgr-application-helper.h>
Public Member Functions
DGRApplicationHelper (std::string protocol, Address address)
Create a PacketSinkHelper to make it easier to work with PacketSinkApplications.
~DGRApplicationHelper ()
ApplicationContainer Install (NodeContainer c) const
Install an ns3::PacketSinkApplication on each node of the input container configured with all the attributes set with SetAttribute.
ApplicationContainer Install (Ptr< Node > node) const
Install an ns3::PacketSinkApplication on each node of the input container configured with all the attributes set with SetAttribute.
ApplicationContainer Install (std::string nodeName) const
Install an ns3::PacketSinkApplication on each node of the input container configured with all the attributes set with SetAttribute.
void SetAttribute (std::string name, const AttributeValue &value)
Helper function used to set the underlying application attributes.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Install an ns3::PacketSink on the node configured with all the attributes set with SetAttribute.
Private Attributes
ObjectFactory m_factory
Object factory.
Detailed Description
A helper to make it easier to instantiate an ns3::PacketSinkApplication on a set of nodes.
Definition at line 18 of file dgr-application-helper.h.
Constructor & Destructor Documentation
DGRApplicationHelper()
ns3::DGRApplicationHelper::DGRApplicationHelper (std::string protocol, Address address)
Create a PacketSinkHelper to make it easier to work with PacketSinkApplications.
Parameters
protocol the name of the protocol to use to receive traffic This string identifies the socket factory type used to create sockets for the applications. A typical value would be ns3::TcpSocketFactory.
address the address of the sink,
Definition at line 29 of file dgr-application-helper.cc.
References m_factory.
~DGRApplicationHelper()
ns3::DGRApplicationHelper::~DGRApplicationHelper ()
Definition at line 36 of file dgr-application-helper.cc.
Member Function Documentation
Install() [1/3]
ApplicationContainer ns3::DGRApplicationHelper::Install (NodeContainer c) const
Install an ns3::PacketSinkApplication on each node of the input container configured with all the attributes set with SetAttribute.
Parameters
c NodeContainer of the set of nodes on which a PacketSinkApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 60 of file dgr-application-helper.cc.
References ns3::i, and InstallPriv().
Install() [2/3]
ApplicationContainer ns3::DGRApplicationHelper::Install (Ptr< Node > node) const
Install an ns3::PacketSinkApplication on each node of the input container configured with all the attributes set with SetAttribute.
Parameters
node The node on which a PacketSinkApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 47 of file dgr-application-helper.cc.
References InstallPriv().
Install() [3/3]
ApplicationContainer ns3::DGRApplicationHelper::Install (std::string nodeName) const
Install an ns3::PacketSinkApplication on each node of the input container configured with all the attributes set with SetAttribute.
Parameters
nodeName The name of the node on which a PacketSinkApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 53 of file dgr-application-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::DGRApplicationHelper::InstallPriv (Ptr< Node > node) const private
Install an ns3::PacketSink on the node configured with all the attributes set with SetAttribute.
Parameters
node The node on which an PacketSink will be installed.
Returns
Ptr to the application installed.
Definition at line 72 of file dgr-application-helper.cc.
References m_factory.
Referenced by Install(), Install(), and Install().
SetAttribute()
void ns3::DGRApplicationHelper::SetAttribute (std::string name, const AttributeValue & value)
Helper function used to set the underlying application attributes.
Parameters
name the name of the application attribute to set
value the value of the application attribute to set
Definition at line 41 of file dgr-application-helper.cc.
References m_factory.
Member Data Documentation
m_factory
ObjectFactory ns3::DGRApplicationHelper::m_factory private
Object factory.
Definition at line 80 of file dgr-application-helper.h.
Referenced by DGRApplicationHelper(), InstallPriv(), and SetAttribute().
The documentation for this class was generated from the following files:
helper/dgr-application-helper.h
helper/dgr-application-helper.cc