DGRv2: ns3::NeighborStatusEntry Class Reference
ns3::NeighborStatusEntry Class Reference
#include <neighbor-status-database.h>
Public Member Functions
NeighborStatusEntry ()
~NeighborStatusEntry ()
uint32_t GetNumStatusUnit () const
StatusUnit * GetStatusUnit (uint32_t n_iface) const
void Insert (uint32_t n_iface, StatusUnit *su)
void Print (std::ostream &os) const
Private Types
typedef std::map< uint32_t, StatusUnit * > NSMap_t
typedef std::pair< uint32_t, StatusUnit * > NSPair_t
status, statistic
Private Attributes
NSMap_t m_database
Detailed Description
Definition at line 26 of file neighbor-status-database.h.
Member Typedef Documentation
NSMap_t
typedef std::map<uint32_t, StatusUnit*> ns3::NeighborStatusEntry::NSMap_t private
Definition at line 39 of file neighbor-status-database.h.
NSPair_t
typedef std::pair<uint32_t, StatusUnit*> ns3::NeighborStatusEntry::NSPair_t private
status, statistic
pair of <interface, StatusUnit>
Definition at line 41 of file neighbor-status-database.h.
Constructor & Destructor Documentation
NeighborStatusEntry()
ns3::NeighborStatusEntry::NeighborStatusEntry ()
Definition at line 71 of file neighbor-status-database.cc.
~NeighborStatusEntry()
ns3::NeighborStatusEntry::~NeighborStatusEntry ()
Definition at line 76 of file neighbor-status-database.cc.
References m_database.
Member Function Documentation
GetNumStatusUnit()
uint32_t ns3::NeighborStatusEntry::GetNumStatusUnit () const
Definition at line 112 of file neighbor-status-database.cc.
References m_database.
GetStatusUnit()
StatusUnit * ns3::NeighborStatusEntry::GetStatusUnit (uint32_t n_iface) const
Definition at line 96 of file neighbor-status-database.cc.
References m_database.
Referenced by ns3::Ipv4DGRRouting::HandleResponses(), and ns3::Ipv4DGRRouting::LookupDGRRoute().
Insert()
void ns3::NeighborStatusEntry::Insert (uint32_t n_iface, StatusUnit * su)
Definition at line 82 of file neighbor-status-database.cc.
References m_database.
Referenced by ns3::Ipv4DGRRouting::HandleResponses().
Print()
void ns3::NeighborStatusEntry::Print (std::ostream & os) const
Definition at line 118 of file neighbor-status-database.cc.
References m_database.
Member Data Documentation
m_database
NSMap_t ns3::NeighborStatusEntry::m_database private
Definition at line 42 of file neighbor-status-database.h.
Referenced by ~NeighborStatusEntry(), GetNumStatusUnit(), GetStatusUnit(), Insert(), and Print().
The documentation for this class was generated from the following files:
model/neighbor-status-database.h
model/neighbor-status-database.cc