DGRv2: ns3::DGRVertex Class Reference
ns3::DGRVertex Class Reference
Vertex used in shortest path first (SPF) computations.
#include <dgr-route-manager-impl.h>
Public Types
typedef std::pair< Ipv4Address, int32_t > NodeExit_t
IPv4 / interface container for exit nodes.
enum VertexType { VertexUnknown = 0 , VertexRouter , VertexNetwork }
Enumeration of the possible types of DGRVertex objects.
Public Member Functions
DGRVertex ()
Construct an empty ("uninitialized") DGRVertex (Shortest Path First Vertex).
DGRVertex (DGRRoutingLSA *lsa)
Construct an initialized DGRVertex (Shortest Path First Vertex).
~DGRVertex ()
Destroy an DGRVertex (Shortest Path First Vertex).
uint32_t AddChild (DGRVertex *child)
Get a borrowed DGRVertex pointer to the specified child of "this" DGRVertex.
void ClearVertexProcessed (void)
Clear the value of the VertexProcessed flag.
DGRVertex * GetChild (uint32_t n) const
Get a borrowed DGRVertex pointer to the specified child of "this" DGRVertex.
uint32_t GetDistanceFromRoot (void) const
Get the distance from the root vertex to "this" DGRVertex object.
DGRRoutingLSA * GetLSA (void) const
Get the Global Router Link State Advertisement returned by the Global Router represented by this DGRVertex during the route discovery process.
uint32_t GetNChildren (void) const
Get the number of children of "this" DGRVertex.
uint32_t GetNRootExitDirections () const
Get the number of exit directions from root for reaching 'this' vertex.
DGRVertex * GetParent (uint32_t i=0) const
Get a pointer to the SPFVector that is the parent of "this" DGRVertex.
NodeExit_t GetRootExitDirection () const
Obtain a pair indicating the exit direction from the root.
NodeExit_t GetRootExitDirection (uint32_t i) const
Obtain a pair indicating the exit direction from the root.
Ipv4Address GetVertexId (void) const
Get the Vertex ID field of a DGRVertex object.
VertexType GetVertexType (void) const
Get the Vertex Type field of a DGRVertex object.
void InheritAllRootExitDirections (const DGRVertex *vertex)
Inherit all root exit directions from a given vertex to 'this' vertex.
bool IsVertexProcessed (void) const
Check the value of the VertexProcessed flag.
void MergeParent (const DGRVertex *v)
Merge the Parent list from the v into this vertex.
void MergeRootExitDirections (const DGRVertex *vertex)
Merge into 'this' vertex the list of exit directions from another vertex.
void SetDistanceFromRoot (uint32_t distance)
Set the distance from the root vertex to "this" DGRVertex object.
void SetLSA (DGRRoutingLSA *lsa)
Set the Global Router Link State Advertisement returned by the Global Router represented by this DGRVertex during the route discovery process.
void SetParent (DGRVertex *parent)
Set the pointer to the SPFVector that is the parent of "this" DGRVertex.
void SetRootExitDirection (DGRVertex::NodeExit_t exit)
Set the IP address and outgoing interface index that should be used to begin forwarding packets from the root DGRVertex to "this" DGRVertex.
void SetRootExitDirection (Ipv4Address nextHop, int32_t id=DISTINFINITY)
Set the IP address and outgoing interface index that should be used to begin forwarding packets from the root DGRVertex to "this" DGRVertex.
void SetVertexId (Ipv4Address id)
Set the Vertex ID field of a DGRVertex object.
void SetVertexProcessed (bool value)
Set the value of the VertexProcessed flag.
void SetVertexType (VertexType type)
Set the Vertex Type field of a DGRVertex object.
Private Types
typedef std::list< DGRVertex * > ListOfDGRVertex_t
container of DGRVertexes
typedef std::list< NodeExit_t > ListOfNodeExit_t
container of Exit nodes
Private Member Functions
DGRVertex (DGRVertex &v)
The DGRVertex copy construction is disallowed.
DGRVertex & operator= (DGRVertex &v)
The DGRVertex copy assignment operator is disallowed.
Private Attributes
ListOfDGRVertex_t m_children
Children list.
uint32_t m_distanceFromRoot
Distance from root node.
ListOfNodeExit_t m_ecmpRootExits
store the multiple root's exits for supporting ECMP
DGRRoutingLSA * m_lsa
Link State Advertisement.
Ipv4Address m_nextHop
next hop
ListOfDGRVertex_t m_parents
parent list
int32_t m_rootOif
root Output Interface
Ipv4Address m_vertexId
Vertex ID.
bool m_vertexProcessed
Flag to note whether vertex has been processed in stage two of SPF computation.
VertexType m_vertexType
Vertex type.
Friends
std::ostream & operator<< (std::ostream &os, const DGRVertex::ListOfDGRVertex_t &vs)
Stream insertion operator.
Detailed Description
Vertex used in shortest path first (SPF) computations.
See \RFC{2328}, Section 16.
Each router in the simulation is associated with an DGRVertex object. When calculating routes, each of these routers is, in turn, chosen as the "root" of the calculation and routes to all of the other routers are eventually saved in the routing tables of each of the chosen nodes. Each of these routers in the calculation has an associated DGRVertex.
The "Root" vertex is the DGRVertex representing the router that is having its routing tables set. The DGRVertex objects representing other routers or networks in the simulation are arranged in the SPF tree. It is this tree that represents the Shortest Paths to the other networks.
Each DGRVertex has a pointer to the Global Router Link State Advertisement (LSA) that its underlying router has exported. Within these LSAs are Global Router Link Records that describe the point to point links from the underlying router to other nodes (represented by other DGRVertex objects) in the simulation topology. The combination of the arrangement of the DGRVertex objects in the SPF tree, along with the details of the link records that connect them provide the information required to construct the required routes.
Definition at line 69 of file dgr-route-manager-impl.h.
Member Typedef Documentation
ListOfDGRVertex_t
typedef std::list<DGRVertex*> ns3::DGRVertex::ListOfDGRVertex_t private
container of DGRVertexes
Definition at line 538 of file dgr-route-manager-impl.h.
ListOfNodeExit_t
typedef std::list< NodeExit_t > ns3::DGRVertex::ListOfNodeExit_t private
container of Exit nodes
Definition at line 536 of file dgr-route-manager-impl.h.
NodeExit_t
typedef std::pair<Ipv4Address, int32_t> ns3::DGRVertex::NodeExit_t
IPv4 / interface container for exit nodes.
Definition at line 292 of file dgr-route-manager-impl.h.
Member Enumeration Documentation
VertexType
enum ns3::DGRVertex::VertexType
Enumeration of the possible types of DGRVertex objects.
Currently we use VertexRouter to identify objects that represent a router in the simulation topology, and VertexNetwork to identify objects that represent a network.
Enumerator
VertexUnknown
Uninitialized Link Record.
VertexRouter
Vertex representing a router in the topology.
VertexNetwork
Vertex representing a network in the topology.
Definition at line 79 of file dgr-route-manager-impl.h.
Constructor & Destructor Documentation
DGRVertex() [1/3]
ns3::DGRVertex::DGRVertex ()
Construct an empty ("uninitialized") DGRVertex (Shortest Path First Vertex).
The Vertex Type is set to VertexUnknown, the Vertex ID is set to 255.255.255.255, and the distance from root is set to infinity (UINT32_MAX). The referenced Link State Advertisement (LSA) is set to null as is the parent DGRVertex. The outgoing interface index is set to infinity, the next hop address is set to 0.0.0.0 and the list of children of the DGRVertex is initialized to empty.
See also
VertexType
Definition at line 89 of file dgr-route-manager-impl.cc.
DGRVertex() [2/3]
ns3::DGRVertex::DGRVertex (DGRRoutingLSA * lsa)
Construct an initialized DGRVertex (Shortest Path First Vertex).
The Vertex Type is initialized to VertexRouter and the Vertex ID is found from the Link State ID of the Link State Advertisement (LSA) passed as a parameter. The Link State ID is set to the Router ID of the advertising router. The referenced LSA (m_lsa) is set to the given LSA. Other than these members, initialization is as in the default constructor. of the DGRVertex is initialized to empty.
See also
DGRVertex::DGRVertex ()
VertexType
GlobalRoutingLSA
Parameters
lsa The Link State Advertisement used for finding initial values.
Definition at line 103 of file dgr-route-manager-impl.cc.
References ns3::DGRRoutingLSA::GetLSType(), m_vertexType, ns3::DGRRoutingLSA::NetworkLSA, ns3::DGRRoutingLSA::RouterLSA, VertexNetwork, and VertexRouter.
~DGRVertex()
ns3::DGRVertex::~DGRVertex ()
Destroy an DGRVertex (Shortest Path First Vertex).
The children vertices of the DGRVertex are recursively deleted.
See also
DGRVertex::DGRVertex ()
Definition at line 127 of file dgr-route-manager-impl.cc.
References GetVertexId(), m_children, m_ecmpRootExits, m_parents, and m_vertexId.
DGRVertex() [3/3]
ns3::DGRVertex::DGRVertex (DGRVertex & v) private
The DGRVertex copy construction is disallowed.
There's no need for it and a compiler provided shallow copy would be wrong.
Parameters
v object to copy from
Member Function Documentation
AddChild()
uint32_t ns3::DGRVertex::AddChild (DGRVertex * child)
Get a borrowed DGRVertex pointer to the specified child of "this" DGRVertex.
Each router node in the simulation is associated with an DGRVertex object. When calculating routes, each of these routers is, in turn, chosen as the "root" of the calculation and routes to all of the other routers are eventually saved in the routing tables of each of the chosen nodes.
The "Root" vertex is then the DGRVertex representing the router that is having its routing tables set and is the root of the SPF tree. Each vertex in the SPF tree can have a number of children that represent host or network routes available via that vertex.
This method the number of children of "this" DGRVertex (which reside in the SPF tree.
See also
DGRVertex::GetNChildren
Warning
Ownership of the pointer added to the children of "this" DGRVertex is transferred to the "this" DGRVertex. You must not delete the (now) child DGRVertex after calling this method.
Parameters
child A pointer to the DGRVertex (which resides in the SPF tree) to be added to the list of children of "this" DGRVertex.
Returns
The number of children of "this" DGRVertex after the addition of the new child.
Definition at line 386 of file dgr-route-manager-impl.cc.
References m_children.
Referenced by ns3::DGRRouteManagerImpl::DGRVertexAddParent().
ClearVertexProcessed()
void ns3::DGRVertex::ClearVertexProcessed (void)
Clear the value of the VertexProcessed flag.
Flag to note whether vertex has been processed in stage two of SPF computation
Definition at line 408 of file dgr-route-manager-impl.cc.
References ClearVertexProcessed(), GetChild(), GetNChildren(), ns3::i, and SetVertexProcessed().
Referenced by ClearVertexProcessed(), and ns3::DGRRouteManagerImpl::SPFCalculate().
GetChild()
DGRVertex * ns3::DGRVertex::GetChild (uint32_t n) const
Get a borrowed DGRVertex pointer to the specified child of "this" DGRVertex.
Each router node in the simulation is associated with an DGRVertex object. When calculating routes, each of these routers is, in turn, chosen as the "root" of the calculation and routes to all of the other routers are eventually saved in the routing tables of each of the chosen nodes.
The "Root" vertex is then the DGRVertex representing the router that is having its routing tables set and is the root of the SPF tree. Each vertex in the SPF tree can have a number of children that represent host or network routes available via that vertex.
This method the number of children of "this" DGRVertex (which reside in the SPF tree.
See also
DGRVertex::GetNChildren
Parameters
n The index (from 0 to the number of children minus 1) of the child DGRVertex to return.
Warning
The pointer returned by GetChild () is a borrowed pointer. You do not have any ownership of the underlying object and must not delete that object.
Returns
A pointer to the specified child DGRVertex (which resides in the SPF tree).
Definition at line 367 of file dgr-route-manager-impl.cc.
References ns3::i, and m_children.
Referenced by ClearVertexProcessed(), ns3::DGRRouteManagerImpl::ProcessASExternals(), and ns3::DGRRouteManagerImpl::SPFProcessStubs().
GetDistanceFromRoot()
uint32_t ns3::DGRVertex::GetDistanceFromRoot (void) const
Get the distance from the root vertex to "this" DGRVertex object.
Each router in the simulation is associated with an DGRVertex object. When calculating routes, each of these routers is, in turn, chosen as the "root" of the calculation and routes to all of the other routers are eventually saved in the routing tables of each of the chosen nodes. Each of these routers in the calculation has an associated DGRVertex.
The "Root" vertex is then the DGRVertex representing the router that is having its routing tables set. The "this" DGRVertex is the vertex to which a route is being calculated from the root. The distance from the root that we're asking for is the number of hops from the root vertex to the vertex in question.
The distance is calculated during route discovery and is stored in a member variable. This method simply fetches that value.
Returns
The distance, in hops, from the root DGRVertex to "this" DGRVertex.
Definition at line 228 of file dgr-route-manager-impl.cc.
References m_distanceFromRoot.
Referenced by ns3::DGRCandidateQueue::CompareDGRVertex(), ns3::DGRRouteManagerImpl::SPFIntraAddRouter(), and ns3::DGRRouteManagerImpl::SPFNext().
GetLSA()
DGRRoutingLSA * ns3::DGRVertex::GetLSA (void) const
Get the Global Router Link State Advertisement returned by the Global Router represented by this DGRVertex during the route discovery process.
See also
DGRRouter
DGRRoutingLSA
DGRRouter::DiscoverLSAs ()
Returns
A pointer to the DGRRoutingLSA found by the router represented by this DGRVertex object.
Definition at line 214 of file dgr-route-manager-impl.cc.
References m_lsa.
Referenced by ns3::DGRRouteManagerImpl::InitializeRoutes(), ns3::DGRRouteManagerImpl::ProcessASExternals(), ns3::DGRRouteManagerImpl::SPFAddASExternal(), ns3::DGRRouteManagerImpl::SPFCalculate(), ns3::DGRRouteManagerImpl::SPFGetNextLink(), ns3::DGRRouteManagerImpl::SPFIntraAddRouter(), ns3::DGRRouteManagerImpl::SPFIntraAddStub(), ns3::DGRRouteManagerImpl::SPFIntraAddTransit(), ns3::DGRRouteManagerImpl::SPFNext(), ns3::DGRRouteManagerImpl::SPFNexthopCalculation(), and ns3::DGRRouteManagerImpl::SPFProcessStubs().
GetNChildren()
uint32_t ns3::DGRVertex::GetNChildren (void) const
Get the number of children of "this" DGRVertex.
Each router node in the simulation is associated with an DGRVertex object. When calculating routes, each of these routers is, in turn, chosen as the "root" of the calculation and routes to all of the other routers are eventually saved in the routing tables of each of the chosen nodes.
The "Root" vertex is then the DGRVertex representing the router that is having its routing tables set and is the root of the SPF tree. Each vertex in the SPF tree can have a number of children that represent host or network routes available via that vertex.
This method returns the number of children of "this" DGRVertex (which reside in the SPF tree).
Returns
The number of children of "this" DGRVertex (which reside in the SPF tree).
Definition at line 360 of file dgr-route-manager-impl.cc.
References m_children.
Referenced by ClearVertexProcessed(), ns3::DGRRouteManagerImpl::ProcessASExternals(), and ns3::DGRRouteManagerImpl::SPFProcessStubs().
GetNRootExitDirections()
uint32_t ns3::DGRVertex::GetNRootExitDirections () const
Get the number of exit directions from root for reaching 'this' vertex.
Returns
The number of exit directions from root
Definition at line 353 of file dgr-route-manager-impl.cc.
References m_ecmpRootExits.
Referenced by ns3::DGRRouteManagerImpl::SPFAddASExternal(), ns3::DGRRouteManagerImpl::SPFIntraAddRouter(), ns3::DGRRouteManagerImpl::SPFIntraAddStub(), and ns3::DGRRouteManagerImpl::SPFIntraAddTransit().
GetParent()
DGRVertex * ns3::DGRVertex::GetParent (uint32_t i = 0) const
Get a pointer to the SPFVector that is the parent of "this" DGRVertex.
Each router node in the simulation is associated with an DGRVertex object. When calculating routes, each of these routers is, in turn, chosen as the "root" of the calculation and routes to all of the other routers are eventually saved in the routing tables of each of the chosen nodes.
The "Root" vertex is then the DGRVertex representing the router that is having its routing tables set and is the root of the SPF tree.
This method returns a pointer to the parent node of "this" DGRVertex (both of which reside in that SPF tree).
Parameters
i The index to one of the parents
Returns
A pointer to the DGRVertex that is the parent of "this" DGRVertex in the SPF tree.
Definition at line 245 of file dgr-route-manager-impl.cc.
References ns3::i, and m_parents.
Referenced by ns3::DGRRouteManagerImpl::DGRVertexAddParent(), and ns3::DGRRouteManagerImpl::SPFNexthopCalculation().
GetRootExitDirection() [1/2]
DGRVertex::NodeExit_t ns3::DGRVertex::GetRootExitDirection () const
Obtain a pair indicating the exit direction from the root.
This method assumes there is only a single exit direction from the root. Error occur if this assumption is invalid.
Returns
The pair of next-hop-IP and outgoing-interface-index for reaching 'this' vertex from the root
Definition at line 313 of file dgr-route-manager-impl.cc.
References GetRootExitDirection(), and m_ecmpRootExits.
Referenced by GetRootExitDirection().
GetRootExitDirection() [2/2]
DGRVertex::NodeExit_t ns3::DGRVertex::GetRootExitDirection (uint32_t i) const
Obtain a pair indicating the exit direction from the root.
Parameters
i An index to a pair
Returns
A pair of next-hop-IP and outgoing-interface-index for indicating an exit direction from the root. It is 0 if the index 'i' is out-of-range
Definition at line 300 of file dgr-route-manager-impl.cc.
References ns3::i, and m_ecmpRootExits.
Referenced by ns3::DGRRouteManagerImpl::SPFAddASExternal(), ns3::DGRRouteManagerImpl::SPFIntraAddRouter(), ns3::DGRRouteManagerImpl::SPFIntraAddStub(), ns3::DGRRouteManagerImpl::SPFIntraAddTransit(), and ns3::DGRRouteManagerImpl::SPFNexthopCalculation().
GetVertexId()
Ipv4Address ns3::DGRVertex::GetVertexId (void) const
Get the Vertex ID field of a DGRVertex object.
The Vertex ID uniquely identifies the simulation object a given DGRVertex represents. Typically, this is the Router ID for DGRVertex objects representing routers, and comes from the Link State Advertisement of a router aggregated to a node in the simulation. These IDs are allocated automatically by the routing environment and look like IP addresses beginning at 0.0.0.0 and monotonically increasing as new routers are instantiated.
Returns
The Ipv4Address Vertex ID of the current DGRVertex object.
Definition at line 200 of file dgr-route-manager-impl.cc.
References m_vertexId.
Referenced by ~DGRVertex(), ns3::DGRCandidateQueue::Find(), ns3::DGRRouteManagerImpl::FindOutgoingInterfaceId(), ns3::DGRRouteManagerImpl::InitializeRoutes(), ns3::DGRRouteManagerImpl::ProcessASExternals(), ns3::DGRRouteManagerImpl::SPFAddASExternal(), ns3::DGRRouteManagerImpl::SPFCalculate(), ns3::DGRRouteManagerImpl::SPFGetNextLink(), ns3::DGRRouteManagerImpl::SPFIntraAddRouter(), ns3::DGRRouteManagerImpl::SPFIntraAddStub(), ns3::DGRRouteManagerImpl::SPFIntraAddTransit(), ns3::DGRRouteManagerImpl::SPFNext(), ns3::DGRRouteManagerImpl::SPFNexthopCalculation(), and ns3::DGRRouteManagerImpl::SPFProcessStubs().
GetVertexType()
DGRVertex::VertexType ns3::DGRVertex::GetVertexType (void) const
Get the Vertex Type field of a DGRVertex object.
The Vertex Type describes the kind of simulation object a given DGRVertex represents.
See also
VertexType
Returns
The VertexType of the current DGRVertex object.
Definition at line 186 of file dgr-route-manager-impl.cc.
References m_vertexType.
Referenced by ns3::DGRCandidateQueue::CompareDGRVertex(), ns3::DGRRouteManagerImpl::InitializeRoutes(), ns3::DGRRouteManagerImpl::ProcessASExternals(), ns3::DGRRouteManagerImpl::SPFCalculate(), ns3::DGRRouteManagerImpl::SPFNext(), ns3::DGRRouteManagerImpl::SPFNexthopCalculation(), and ns3::DGRRouteManagerImpl::SPFProcessStubs().
InheritAllRootExitDirections()
void ns3::DGRVertex::InheritAllRootExitDirections (const DGRVertex * vertex)
Inherit all root exit directions from a given vertex to 'this' vertex.
Parameters
vertex The vertex from which all root exit directions are to be inherited
After the call of this method, the original root exit directions in 'this' vertex are all lost.
Definition at line 337 of file dgr-route-manager-impl.cc.
References m_ecmpRootExits.
Referenced by ns3::DGRRouteManagerImpl::SPFNexthopCalculation().
IsVertexProcessed()
bool ns3::DGRVertex::IsVertexProcessed (void) const
Check the value of the VertexProcessed flag.
Flag to note whether vertex has been processed in stage two of SPF computation
Returns
value of underlying flag
Definition at line 401 of file dgr-route-manager-impl.cc.
References m_vertexProcessed.
Referenced by ns3::DGRRouteManagerImpl::ProcessASExternals(), and ns3::DGRRouteManagerImpl::SPFProcessStubs().
MergeParent()
void ns3::DGRVertex::MergeParent (const DGRVertex * v)
Merge the Parent list from the v into this vertex.
Parameters
v The vertex from which its list of Parent is read and then merged into the list of Parent of this vertex. Note that the list in v remains intact
Definition at line 264 of file dgr-route-manager-impl.cc.
References m_parents.
Referenced by ns3::DGRRouteManagerImpl::SPFNext().
MergeRootExitDirections()
void ns3::DGRVertex::MergeRootExitDirections (const DGRVertex * vertex)
Merge into 'this' vertex the list of exit directions from another vertex.
This merge is necessary when ECMP are found.
Parameters
vertex From which the list of exit directions are obtain and are merged into 'this' vertex
Definition at line 322 of file dgr-route-manager-impl.cc.
References m_ecmpRootExits.
Referenced by ns3::DGRRouteManagerImpl::SPFNext().
operator=()
DGRVertex & ns3::DGRVertex::operator= (DGRVertex & v) private
The DGRVertex copy assignment operator is disallowed.
There's no need for it and a compiler provided shallow copy would be wrong.
Parameters
v object to copy from
Returns
the copied object
SetDistanceFromRoot()
void ns3::DGRVertex::SetDistanceFromRoot (uint32_t distance)
Set the distance from the root vertex to "this" DGRVertex object.
Each router in the simulation is associated with an DGRVertex object. When calculating routes, each of these routers is, in turn, chosen as the "root" of the calculation and routes to all of the other routers are eventually saved in the routing tables of each of the chosen nodes. Each of these routers in the calculation has an associated DGRVertex.
The "Root" vertex is then the DGRVertex representing the router that is having its routing tables set. The "this" DGRVertex is the vertex to which a route is being calculated from the root. The distance from the root that we're asking for is the number of hops from the root vertex to the vertex in question.
Parameters
distance The distance, in hops, from the root DGRVertex to "this" DGRVertex.
Definition at line 221 of file dgr-route-manager-impl.cc.
References m_distanceFromRoot.
Referenced by ns3::DGRRouteManagerImpl::SPFCalculate(), and ns3::DGRRouteManagerImpl::SPFNexthopCalculation().
SetLSA()
void ns3::DGRVertex::SetLSA (DGRRoutingLSA * lsa)
Set the Global Router Link State Advertisement returned by the Global Router represented by this DGRVertex during the route discovery process.
See also
DGRVertex::GetLSA ()
DGRRouter
DGRRoutingLSA
DGRRouter::DiscoverLSAs ()
Warning
Ownership of the LSA is transferred to the "this" DGRVertex. You must not delete the LSA after calling this method.
Parameters
lsa A pointer to the DGRRoutingLSA.
Definition at line 207 of file dgr-route-manager-impl.cc.
References m_lsa.
SetParent()
void ns3::DGRVertex::SetParent (DGRVertex * parent)
Set the pointer to the SPFVector that is the parent of "this" DGRVertex.
Each router node in the simulation is associated with an DGRVertex object. When calculating routes, each of these routers is, in turn, chosen as the "root" of the calculation and routes to all of the other routers are eventually saved in the routing tables of each of the chosen nodes.
The "Root" vertex is then the DGRVertex representing the router that is having its routing tables set and is the root of the SPF tree.
This method sets the parent pointer of "this" DGRVertex (both of which reside in that SPF tree).
Parameters
parent A pointer to the DGRVertex that is the parent of "this" DGRVertex* in the SPF tree.
Definition at line 235 of file dgr-route-manager-impl.cc.
References m_parents.
Referenced by ns3::DGRRouteManagerImpl::SPFNexthopCalculation().
SetRootExitDirection() [1/2]
void ns3::DGRVertex::SetRootExitDirection (DGRVertex::NodeExit_t exit)
Set the IP address and outgoing interface index that should be used to begin forwarding packets from the root DGRVertex to "this" DGRVertex.
Each router node in the simulation is associated with an DGRVertex object. When calculating routes, each of these routers is, in turn, chosen as the "root" of the calculation and routes to all of the other routers are eventually saved in the routing tables of each of the chosen nodes.
The "Root" vertex is then the DGRVertex representing the router that is having its routing tables set. The "this" DGRVertex is the vertex that represents the host or network to which a route is being calculated from the root. The IP address that we're asking for is the address on the remote side of a link off of the root node that should be used as the destination for packets along the path to "this" vertex.
When initializing the root DGRVertex, the IP address used when forwarding packets is determined by examining the Global Router Link Records of the Link State Advertisement generated by the root node's DGRRouter. This address is used to forward packets off of the root's network down those links. As other vertices / nodes are discovered which are further away from the root, they will be accessible down one of the paths via a link described by one of these Global Router Link Records.
To forward packets to these hosts or networks, the root node must begin the forwarding process by sending the packets to a first hop router down an interface. This means that the first hop address and interface ID must be the same for all downstream SPFVertices. We call this "inheriting" the interface and next hop.
In this method we are telling the root node which exit direction it should send should I send a packet to the network or host represented by 'this' DGRVertex.
See also
DGRRouter
DGRRoutingLSA
DGRRoutingLinkRecord
Parameters
exit The pair of next-hop-IP and outgoing-interface-index to use when forwarding packets to the host or network represented by "this" DGRVertex.
Definition at line 293 of file dgr-route-manager-impl.cc.
References SetRootExitDirection().
SetRootExitDirection() [2/2]
void ns3::DGRVertex::SetRootExitDirection (Ipv4Address nextHop, int32_t id = DISTINFINITY)
Set the IP address and outgoing interface index that should be used to begin forwarding packets from the root DGRVertex to "this" DGRVertex.
Each router node in the simulation is associated with an DGRVertex object. When calculating routes, each of these routers is, in turn, chosen as the "root" of the calculation and routes to all of the other routers are eventually saved in the routing tables of each of the chosen nodes.
The "Root" vertex is then the DGRVertex representing the router that is having its routing tables set. The "this" DGRVertex is the vertex that represents the host or network to which a route is being calculated from the root. The IP address that we're asking for is the address on the remote side of a link off of the root node that should be used as the destination for packets along the path to "this" vertex.
When initializing the root DGRVertex, the IP address used when forwarding packets is determined by examining the Global Router Link Records of the Link State Advertisement generated by the root node's DGRRouter. This address is used to forward packets off of the root's network down those links. As other vertices / nodes are discovered which are further away from the root, they will be accessible down one of the paths via a link described by one of these Global Router Link Records.
To forward packets to these hosts or networks, the root node must begin the forwarding process by sending the packets to a first hop router down an interface. This means that the first hop address and interface ID must be the same for all downstream SPFVertices. We call this "inheriting" the interface and next hop.
In this method we are telling the root node which exit direction it should send should I send a packet to the network or host represented by 'this' DGRVertex.
See also
DGRRouter
DGRRoutingLSA
DGRRoutingLinkRecord
Parameters
nextHop The IP address to use when forwarding packets to the host or network represented by "this" DGRVertex.
id The interface index to use when forwarding packets to the host or network represented by "this" DGRVertex.
Definition at line 279 of file dgr-route-manager-impl.cc.
References m_ecmpRootExits, m_nextHop, and m_rootOif.
Referenced by SetRootExitDirection(), and ns3::DGRRouteManagerImpl::SPFNexthopCalculation().
SetVertexId()
void ns3::DGRVertex::SetVertexId (Ipv4Address id)
Set the Vertex ID field of a DGRVertex object.
The Vertex ID uniquely identifies the simulation object a given DGRVertex represents. Typically, this is the Router ID for DGRVertex objects representing routers, and comes from the Link State Advertisement of a router aggregated to a node in the simulation. These IDs are allocated automatically by the routing environment and look like IP addresses beginning at 0.0.0.0 and monotonically increase as new routers are instantiated. This method is an explicit override of the automatically generated value.
Parameters
id The new Ipv4Address Vertex ID for the current DGRVertex object.
Definition at line 193 of file dgr-route-manager-impl.cc.
References m_vertexId.
SetVertexProcessed()
void ns3::DGRVertex::SetVertexProcessed (bool value)
Set the value of the VertexProcessed flag.
Flag to note whether vertex has been processed in stage two of SPF computation
Parameters
value boolean value to set the flag
Definition at line 394 of file dgr-route-manager-impl.cc.
References m_vertexProcessed.
Referenced by ClearVertexProcessed(), ns3::DGRRouteManagerImpl::ProcessASExternals(), and ns3::DGRRouteManagerImpl::SPFProcessStubs().
SetVertexType()
void ns3::DGRVertex::SetVertexType (DGRVertex::VertexType type)
Set the Vertex Type field of a DGRVertex object.
The Vertex Type describes the kind of simulation object a given DGRVertex represents.
See also
VertexType
Parameters
type The new VertexType for the current DGRVertex object.
Definition at line 179 of file dgr-route-manager-impl.cc.
References m_vertexType.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const DGRVertex::ListOfDGRVertex_t & vs) friend
Stream insertion operator.
Parameters
os the reference to the output stream
vs a list of DGRVertexes
Returns
the reference to the output stream
Definition at line 62 of file dgr-route-manager-impl.cc.
Member Data Documentation
m_children
ListOfDGRVertex_t ns3::DGRVertex::m_children private
Children list.
Definition at line 540 of file dgr-route-manager-impl.h.
Referenced by ~DGRVertex(), AddChild(), GetChild(), and GetNChildren().
m_distanceFromRoot
uint32_t ns3::DGRVertex::m_distanceFromRoot private
Distance from root node.
Definition at line 533 of file dgr-route-manager-impl.h.
Referenced by GetDistanceFromRoot(), and SetDistanceFromRoot().
m_ecmpRootExits
ListOfNodeExit_t ns3::DGRVertex::m_ecmpRootExits private
store the multiple root's exits for supporting ECMP
Definition at line 537 of file dgr-route-manager-impl.h.
Referenced by ~DGRVertex(), GetNRootExitDirections(), GetRootExitDirection(), GetRootExitDirection(), InheritAllRootExitDirections(), MergeRootExitDirections(), and SetRootExitDirection().
m_lsa
DGRRoutingLSA* ns3::DGRVertex::m_lsa private
Link State Advertisement.
Definition at line 532 of file dgr-route-manager-impl.h.
Referenced by GetLSA(), and SetLSA().
m_nextHop
Ipv4Address ns3::DGRVertex::m_nextHop private
next hop
Definition at line 535 of file dgr-route-manager-impl.h.
Referenced by SetRootExitDirection().
m_parents
ListOfDGRVertex_t ns3::DGRVertex::m_parents private
parent list
Definition at line 539 of file dgr-route-manager-impl.h.
Referenced by ~DGRVertex(), GetParent(), MergeParent(), and SetParent().
m_rootOif
int32_t ns3::DGRVertex::m_rootOif private
root Output Interface
Definition at line 534 of file dgr-route-manager-impl.h.
Referenced by SetRootExitDirection().
m_vertexId
Ipv4Address ns3::DGRVertex::m_vertexId private
Vertex ID.
Definition at line 531 of file dgr-route-manager-impl.h.
Referenced by ~DGRVertex(), GetVertexId(), and SetVertexId().
m_vertexProcessed
bool ns3::DGRVertex::m_vertexProcessed private
Flag to note whether vertex has been processed in stage two of SPF computation.
Definition at line 541 of file dgr-route-manager-impl.h.
Referenced by IsVertexProcessed(), and SetVertexProcessed().
m_vertexType
VertexType ns3::DGRVertex::m_vertexType private
Vertex type.
Definition at line 530 of file dgr-route-manager-impl.h.
Referenced by DGRVertex(), GetVertexType(), and SetVertexType().
The documentation for this class was generated from the following files:
model/dgr-route-manager-impl.h
model/dgr-route-manager-impl.cc