DGRv2: ns3::BudgetTag Class Reference
ns3::BudgetTag Class Reference
This class implements a tag that carries the budget time of a packet to the IP layer.
#include <dgr-tags.h>
Public Member Functions
BudgetTag ()
void Deserialize (TagBuffer i) override
uint32_t GetBudget (void) const
Get the tag's budget.
TypeId GetInstanceTypeId (void) const override
uint32_t GetSerializedSize (void) const override
void Print (std::ostream &os) const override
void Serialize (TagBuffer i) const override
void SetBudget (uint32_t m_budget)
Set the tag's budget.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_budget
Detailed Description
This class implements a tag that carries the budget time of a packet to the IP layer.
Definition at line 17 of file dgr-tags.h.
Constructor & Destructor Documentation
BudgetTag()
ns3::BudgetTag::BudgetTag ()
Definition at line 22 of file dgr-tags.cc.
Member Function Documentation
Deserialize()
void ns3::BudgetTag::Deserialize (TagBuffer i) override
Definition at line 73 of file dgr-tags.cc.
References ns3::i, and m_budget.
GetBudget()
uint32_t ns3::BudgetTag::GetBudget (void) const
Get the tag's budget.
Returns
the budget in millisecond
Definition at line 35 of file dgr-tags.cc.
References m_budget.
Referenced by ns3::Ipv4DGRRouting::LookupDGRRoute().
GetInstanceTypeId()
TypeId ns3::BudgetTag::GetInstanceTypeId (void) const override
Definition at line 52 of file dgr-tags.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::BudgetTag::GetSerializedSize (void) const override
Definition at line 58 of file dgr-tags.cc.
GetTypeId()
TypeId ns3::BudgetTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file dgr-tags.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::BudgetTag::Print (std::ostream & os) const override
Definition at line 82 of file dgr-tags.cc.
References m_budget.
Serialize()
void ns3::BudgetTag::Serialize (TagBuffer i) const override
Definition at line 65 of file dgr-tags.cc.
References ns3::i, and m_budget.
SetBudget()
void ns3::BudgetTag::SetBudget (uint32_t m_budget)
Set the tag's budget.
Parameters
budget the delay budget in millisecond
Definition at line 28 of file dgr-tags.cc.
References m_budget.
Referenced by ns3::DGRTcpApplication::SendData(), and ns3::DGRUdpApplication::SendPacket().
Member Data Documentation
m_budget
uint32_t ns3::BudgetTag::m_budget private
Definition at line 56 of file dgr-tags.h.
Referenced by Deserialize(), GetBudget(), Print(), Serialize(), and SetBudget().
The documentation for this class was generated from the following files:
model/dgr-tags.h
model/dgr-tags.cc