DGRv2: ns3::DgrNSDB Class Reference
ns3::DgrNSDB Class Reference
The DGR neighbor status database.
#include <neighbor-status-database.h>
Public Member Functions
DgrNSDB ()
Construct an empty Neighbor Status Database.
DgrNSDB (const DgrNSDB &)=delete
~DgrNSDB ()
Destroy an empty Neighbor Status Database.
NeighborStatusEntry * GetNeighborStatusEntry (uint32_t iface) const
Get the NeighborStatusEntry of a Interface.
NeighborStatusEntry * HandleNeighborStatusEntry (uint32_t iface)
Handle the NeighborStatusEntry of a Interface.
void Initialize ()
Set NSDB to empty.
void Insert (uint32_t iface, NeighborStatusEntry *nse)
Insert an <interface, Neighbor Status Entry> into the NSDB.
DgrNSDB & operator= (const DgrNSDB &)=delete
void Print (std::ostream &os) const
Print the database.
Private Types
typedef std::map< uint32_t, NeighborStatusEntry * >::const_iterator NeighborStatusMapCI
NSE type const iterator.
typedef std::map< uint32_t, NeighborStatusEntry * >::iterator NeighborStatusMapI
NSE type iterator.
typedef std::map< uint32_t, NeighborStatusEntry * > NSDBMap_t
container of <interface, NeighborStatusEntry>
typedef std::pair< uint32_t, NeighborStatusEntry * > NSDBPair_t
pair of <interface, NeighborStatusEntry>
Private Attributes
NSDBMap_t m_database
database of <interface, NeighborStatusEntry>
Detailed Description
The DGR neighbor status database.
Each node in DGR maintains a neighbor status data base.
Definition at line 51 of file neighbor-status-database.h.
Member Typedef Documentation
NeighborStatusMapCI
typedef std::map<uint32_t,NeighborStatusEntry*>::const_iterator ns3::DgrNSDB::NeighborStatusMapCI private
NSE type const iterator.
Definition at line 118 of file neighbor-status-database.h.
NeighborStatusMapI
typedef std::map<uint32_t,NeighborStatusEntry*>::iterator ns3::DgrNSDB::NeighborStatusMapI private
NSE type iterator.
Definition at line 116 of file neighbor-status-database.h.
NSDBMap_t
typedef std::map<uint32_t, NeighborStatusEntry*> ns3::DgrNSDB::NSDBMap_t private
container of <interface, NeighborStatusEntry>
Definition at line 112 of file neighbor-status-database.h.
NSDBPair_t
typedef std::pair<uint32_t, NeighborStatusEntry*> ns3::DgrNSDB::NSDBPair_t private
pair of <interface, NeighborStatusEntry>
Definition at line 114 of file neighbor-status-database.h.
Constructor & Destructor Documentation
DgrNSDB() [1/2]
ns3::DgrNSDB::DgrNSDB ()
Construct an empty Neighbor Status Database.
The database map composing the Neighbor Status Database in initilaized in this constructor.
Definition at line 134 of file neighbor-status-database.cc.
~DgrNSDB()
ns3::DgrNSDB::~DgrNSDB ()
Destroy an empty Neighbor Status Database.
Before distroy the database, resources should be release by clear ()
Definition at line 140 of file neighbor-status-database.cc.
References Initialize().
DgrNSDB() [2/2]
ns3::DgrNSDB::DgrNSDB (const DgrNSDB &) delete
Member Function Documentation
GetNeighborStatusEntry()
NeighborStatusEntry * ns3::DgrNSDB::GetNeighborStatusEntry (uint32_t iface) const
Get the NeighborStatusEntry of a Interface.
Parameters
iface The interface number
Returns
NeighborStatusEntry*
Definition at line 162 of file neighbor-status-database.cc.
References m_database.
Referenced by ns3::Ipv4DGRRouting::LookupDGRRoute().
HandleNeighborStatusEntry()
NeighborStatusEntry * ns3::DgrNSDB::HandleNeighborStatusEntry (uint32_t iface)
Handle the NeighborStatusEntry of a Interface.
Parameters
iface The interface number
Returns
NeighborStatusEntry*
Definition at line 177 of file neighbor-status-database.cc.
References m_database.
Referenced by ns3::Ipv4DGRRouting::HandleResponses().
Initialize()
void ns3::DgrNSDB::Initialize ()
Set NSDB to empty.
Definition at line 155 of file neighbor-status-database.cc.
References m_database.
Referenced by ~DgrNSDB().
Insert()
void ns3::DgrNSDB::Insert (uint32_t iface, NeighborStatusEntry * nse)
Insert an <interface, Neighbor Status Entry> into the NSDB.
The interface and NeighborStatusEntry given as parameters are converted to an STL pair and insert into the database map.
Parameters
iface interface number
nse the neighbor status entry
Definition at line 193 of file neighbor-status-database.cc.
References m_database.
Referenced by ns3::Ipv4DGRRouting::HandleResponses().
operator=()
DgrNSDB & ns3::DgrNSDB::operator= (const DgrNSDB &) delete
Print()
void ns3::DgrNSDB::Print (std::ostream & os) const
Print the database.
Definition at line 210 of file neighbor-status-database.cc.
References m_database.
Member Data Documentation
m_database
NSDBMap_t ns3::DgrNSDB::m_database private
database of <interface, NeighborStatusEntry>
Definition at line 119 of file neighbor-status-database.h.
Referenced by GetNeighborStatusEntry(), HandleNeighborStatusEntry(), Initialize(), Insert(), and Print().
The documentation for this class was generated from the following files:
model/neighbor-status-database.h
model/neighbor-status-database.cc