DGRv2: ns3::DGRRouteManagerLSDB Class Reference
ns3::DGRRouteManagerLSDB Class Reference
The Link State DataBase (LSDB) of the DGR Route Manager.
#include <dgr-route-manager-impl.h>
Public Member Functions
DGRRouteManagerLSDB ()
Construct an empty Global Router Manager Link State Database.
~DGRRouteManagerLSDB ()
Destroy an empty Global Router Manager Link State Database.
DGRRoutingLSA * GetExtLSA (uint32_t index) const
Look up the External Link State Advertisement associated with the given index.
DGRRoutingLSA * GetLSA (Ipv4Address addr) const
Look up the Link State Advertisement associated with the given link state ID (address).
DGRRoutingLSA * GetLSAByLinkData (Ipv4Address addr) const
Look up the Link State Advertisement associated with the given link state ID (address).
uint32_t GetNumExtLSAs () const
Get the number of External Link State Advertisements.
void Initialize ()
Set all LSA flags to an initialized state, for SPF computation.
void Insert (Ipv4Address addr, DGRRoutingLSA *lsa)
Insert an IP address / Link State Advertisement pair into the Link State Database.
Private Types
typedef std::map< Ipv4Address, DGRRoutingLSA * > LSDBMap_t
container of IPv4 addresses / Link State Advertisements
typedef std::pair< Ipv4Address, DGRRoutingLSA * > LSDBPair_t
pair of IPv4 addresses / Link State Advertisements
Private Member Functions
DGRRouteManagerLSDB (DGRRouteManagerLSDB &lsdb)
DGRRouteManagerLSDB copy construction is disallowed.
DGRRouteManagerLSDB & operator= (DGRRouteManagerLSDB &lsdb)
The DGRVertex copy assignment operator is disallowed.
Private Attributes
LSDBMap_t m_database
database of IPv4 addresses / Link State Advertisements
std::vector< DGRRoutingLSA * > m_extdatabase
database of External Link State Advertisements
Detailed Description
The Link State DataBase (LSDB) of the DGR Route Manager.
Each node in the simulation participating in global routing has a DGRRouter interface. The primary job of this interface is to export Global Router Link State Advertisements (LSAs). These advertisements in turn contain a number of Global Router Link Records that describe the point to point links from the underlying node to other nodes (that will also export their own LSAs.
This class implements a searchable database of LSAs gathered from every router in the simulation.
Definition at line 581 of file dgr-route-manager-impl.h.
Member Typedef Documentation
LSDBMap_t
typedef std::map<Ipv4Address, DGRRoutingLSA*> ns3::DGRRouteManagerLSDB::LSDBMap_t private
container of IPv4 addresses / Link State Advertisements
Definition at line 680 of file dgr-route-manager-impl.h.
LSDBPair_t
typedef std::pair<Ipv4Address, DGRRoutingLSA*> ns3::DGRRouteManagerLSDB::LSDBPair_t private
pair of IPv4 addresses / Link State Advertisements
Definition at line 681 of file dgr-route-manager-impl.h.
Constructor & Destructor Documentation
DGRRouteManagerLSDB() [1/2]
ns3::DGRRouteManagerLSDB::DGRRouteManagerLSDB ()
Construct an empty Global Router Manager Link State Database.
The database map composing the Link State Database is initialized in this constructor.
Definition at line 424 of file dgr-route-manager-impl.cc.
~DGRRouteManagerLSDB()
ns3::DGRRouteManagerLSDB::~DGRRouteManagerLSDB ()
Destroy an empty Global Router Manager Link State Database.
The database map is walked and all of the Link State Advertisements stored in the database are freed; then the database map itself is clear ()ed to release any remaining resources.
Definition at line 432 of file dgr-route-manager-impl.cc.
References ns3::i, m_database, and m_extdatabase.
DGRRouteManagerLSDB() [2/2]
ns3::DGRRouteManagerLSDB::DGRRouteManagerLSDB (DGRRouteManagerLSDB & lsdb) private
DGRRouteManagerLSDB copy construction is disallowed.
There's no need for it and a compiler provided shallow copy would be wrong.
Parameters
lsdb object to copy from
Member Function Documentation
GetExtLSA()
DGRRoutingLSA * ns3::DGRRouteManagerLSDB::GetExtLSA (uint32_t index) const
Look up the External Link State Advertisement associated with the given index.
The external database map is searched for the given index and corresponding DGRRoutingLSA is returned.
See also
DGRRoutingLSA
Parameters
index the index associated with the LSA.
Returns
A pointer to the Link State Advertisement.
Definition at line 479 of file dgr-route-manager-impl.cc.
References m_extdatabase.
Referenced by ns3::DGRRouteManagerImpl::SPFCalculate().
GetLSA()
DGRRoutingLSA * ns3::DGRRouteManagerLSDB::GetLSA (Ipv4Address addr) const
Look up the Link State Advertisement associated with the given link state ID (address).
The database map is searched for the given IPV4 address and corresponding DGRRoutingLSA is returned.
See also
DGRRoutingLSA
Ipv4Address
Parameters
addr The IP address associated with the LSA. Typically the Router ID.
Returns
A pointer to the Link State Advertisement for the router specified by the IP address addr.
Definition at line 493 of file dgr-route-manager-impl.cc.
References ns3::i, and m_database.
Referenced by ns3::DGRRouteManagerImpl::CheckForStubNode(), ns3::DGRRouteManagerImpl::InitializeRoutes(), ns3::DGRRouteManagerImpl::SPFCalculate(), and ns3::DGRRouteManagerImpl::SPFNext().
GetLSAByLinkData()
DGRRoutingLSA * ns3::DGRRouteManagerLSDB::GetLSAByLinkData (Ipv4Address addr) const
Look up the Link State Advertisement associated with the given link state ID (address).
This is a variation of the GetLSA call to allow the LSA to be found by matching addr with the LinkData field of the TransitNetwork link record.
See also
GetLSA
Parameters
addr The IP address associated with the LSA. Typically the Router
Returns
A pointer to the Link State Advertisement for the router specified by the IP address addr. ID.
Definition at line 511 of file dgr-route-manager-impl.cc.
References ns3::DGRRoutingLinkRecord::GetLinkData(), ns3::DGRRoutingLSA::GetLinkRecord(), ns3::DGRRoutingLinkRecord::GetLinkType(), ns3::DGRRoutingLSA::GetNLinkRecords(), ns3::i, m_database, and ns3::DGRRoutingLinkRecord::TransitNetwork.
Referenced by ns3::DGRRouteManagerImpl::SPFNext().
GetNumExtLSAs()
uint32_t ns3::DGRRouteManagerLSDB::GetNumExtLSAs () const
Get the number of External Link State Advertisements.
See also
DGRRoutingLSA
Returns
the number of External Link State Advertisements.
Definition at line 486 of file dgr-route-manager-impl.cc.
References m_extdatabase.
Referenced by ns3::DGRRouteManagerImpl::SPFCalculate().
Initialize()
void ns3::DGRRouteManagerLSDB::Initialize ()
Set all LSA flags to an initialized state, for SPF computation.
This function walks the database and resets the status flags of all of the contained Link State Advertisements to LSA_SPF_NOT_EXPLORED. This is done prior to each SPF calculation to reset the state of the DGRVertex structures that will reference the LSAs during the calculation.
See also
DGRRoutingLSA
DGRVertex
Definition at line 453 of file dgr-route-manager-impl.cc.
References ns3::i, ns3::DGRRoutingLSA::LSA_SPF_NOT_EXPLORED, m_database, and ns3::DGRRoutingLSA::SetStatus().
Referenced by ns3::DGRRouteManagerImpl::SPFCalculate().
Insert()
void ns3::DGRRouteManagerLSDB::Insert (Ipv4Address addr, DGRRoutingLSA * lsa)
Insert an IP address / Link State Advertisement pair into the Link State Database.
The IPV4 address and the DGRRoutingLSA given as parameters are converted to an STL pair and are inserted into the database map.
See also
DGRRoutingLSA
Ipv4Address
Parameters
addr The IP address associated with the LSA. Typically the Router ID.
lsa A pointer to the Link State Advertisement for the router.
Definition at line 465 of file dgr-route-manager-impl.cc.
References ns3::DGRRoutingLSA::ASExternalLSAs, ns3::DGRRoutingLSA::GetLSType(), m_database, and m_extdatabase.
Referenced by ns3::DGRRouteManagerImpl::BuildDGRRoutingDatabase().
operator=()
DGRRouteManagerLSDB & ns3::DGRRouteManagerLSDB::operator= (DGRRouteManagerLSDB & lsdb) private
The DGRVertex copy assignment operator is disallowed.
There's no need for it and a compiler provided shallow copy would be wrong.
Parameters
lsdb object to copy from
Returns
the copied object
Member Data Documentation
m_database
LSDBMap_t ns3::DGRRouteManagerLSDB::m_database private
database of IPv4 addresses / Link State Advertisements
Definition at line 683 of file dgr-route-manager-impl.h.
Referenced by ~DGRRouteManagerLSDB(), GetLSA(), GetLSAByLinkData(), Initialize(), and Insert().
m_extdatabase
std::vector<DGRRoutingLSA*> ns3::DGRRouteManagerLSDB::m_extdatabase private
database of External Link State Advertisements
Definition at line 684 of file dgr-route-manager-impl.h.
Referenced by ~DGRRouteManagerLSDB(), GetExtLSA(), GetNumExtLSAs(), and Insert().
The documentation for this class was generated from the following files:
model/dgr-route-manager-impl.h
model/dgr-route-manager-impl.cc