#!/bin/bash
# exp 2
echo "exptcpudp"
echo ""

DIR="contrib/dgr/infocomm2023/tcpudp/"
FILE="dgr-packet.delay"

# # abilene 0 --> 10
# # back	  2 --> 5
# TOPO="abilene"
# SINK="10"
# SENDER="0"
# TCPSINK="3"
# TCPSENDER="1"
# DATARATE="1Mbps"
# echo "${TOPO} ${SINK} ${SENDER} ${TCPSINK} ${TCPSENDER}"
# # ./waf --run "scratch/dgr.cc --topo=${TOPO} --sink=${SINK} --sender=${SENDER} --tcpSink=${TCPSINK} --tcpSender=${TCPSENDER}"
# # cp $FILE "${DIR}${TOPO}/dgr.txt"
# TCPSINK="5"
# TCPSENDER="2"
# ./waf --run "scratch/ospf.cc --ns3::Ipv4GlobalRouting::RandomEcmpRouting=true --topo=${TOPO} --sink=${SINK} --sender=${SENDER} --tcpSink=${TCPSINK} --tcpSender=${TCPSENDER}"
# cp $FILE "${DIR}${TOPO}/ecmp.txt"
# ./waf --run "scratch/ospf.cc --ns3::Ipv4GlobalRouting::RandomEcmpRouting=false --topo=${TOPO} --sink=${SINK} --sender=${SENDER} --tcpSink=${TCPSINK} --tcpSender=${TCPSENDER}"
# cp $FILE "${DIR}${TOPO}/ospf.txt"

# # att 20 --> 14
# # back 2 --> 16
# TOPO="att"
# SINK="14"
# SENDER="20"
# TCPSINK="16"
# TCPSENDER="2"
# DATARATE="1Mbps"
# echo "${TOPO} ${SINK} ${SENDER} ${TCPSINK} ${TCPSENDER}"
# ./waf --run "scratch/dgr.cc --topo=${TOPO} --sink=${SINK} --sender=${SENDER} --tcpSink=${TCPSINK} --tcpSender=${TCPSENDER}"
# cp $FILE "${DIR}${TOPO}/dgr.txt"
# TCPSINK="13"
# TCPSENDER="17"
# ./waf --run "scratch/ospf.cc --ns3::Ipv4GlobalRouting::RandomEcmpRouting=true --topo=${TOPO} --sink=${SINK} --sender=${SENDER} --tcpSink=${TCPSINK} --tcpSender=${TCPSENDER}"
# cp $FILE "${DIR}${TOPO}/ecmp.txt"
# TCPSINK="9"
# TCPSENDER="2"
# ./waf --run "scratch/ospf.cc --ns3::Ipv4GlobalRouting::RandomEcmpRouting=false --topo=${TOPO} --sink=${SINK} --sender=${SENDER} --tcpSink=${TCPSINK} --tcpSender=${TCPSENDER}"
# cp $FILE "${DIR}${TOPO}/ospf.txt"

# cernet 7 --> 13
# back   9 --> 21
TOPO="cernet"
SINK="13"
SENDER="7"
TCPSINK="21"
TCPSENDER="9"
DATARATE="1Mbps"
echo "${TOPO} ${SINK} ${SENDER} ${TCPSINK} ${TCPSENDER}"
./waf --run "scratch/dgr.cc --topo=${TOPO} --sink=${SINK} --sender=${SENDER} --tcpSink=${TCPSINK} --tcpSender=${TCPSENDER}"
cp $FILE "${DIR}${TOPO}/dgr.txt"
TCPSINK="13"
TCPSENDER="24"
./waf --run "scratch/ospf.cc --ns3::Ipv4GlobalRouting::RandomEcmpRouting=true --topo=${TOPO} --sink=${SINK} --sender=${SENDER} --tcpSink=${TCPSINK} --tcpSender=${TCPSENDER}"
cp $FILE "${DIR}${TOPO}/ecmp.txt"
./waf --run "scratch/ospf.cc --ns3::Ipv4GlobalRouting::RandomEcmpRouting=false --topo=${TOPO} --sink=${SINK} --sender=${SENDER} --tcpSink=${TCPSINK} --tcpSender=${TCPSENDER}"
cp $FILE "${DIR}${TOPO}/ospf.txt"

# # geant 16 --> 14
# # back 12 --> 13
# TOPO="geant"
# SINK="14"
# SENDER="16"
# TCPSINK="13"
# TCPSENDER="12"
# DATARATE="1Mbps"
# echo "${TOPO} ${SINK} ${SENDER} ${TCPSINK} ${TCPSENDER}"
# ./waf --run "scratch/dgr.cc --topo=${TOPO} --sink=${SINK} --sender=${SENDER} --tcpSink=${TCPSINK} --tcpSender=${TCPSENDER}"
# cp $FILE "${DIR}${TOPO}/dgr.txt"
# TCPSINK="15"
# TCPSENDER="9"
# ./waf --run "scratch/ospf.cc --ns3::Ipv4GlobalRouting::RandomEcmpRouting=true --topo=${TOPO} --sink=${SINK} --sender=${SENDER} --tcpSink=${TCPSINK} --tcpSender=${TCPSENDER}"
# cp $FILE "${DIR}${TOPO}/ecmp.txt"
# ./waf --run "scratch/ospf.cc --ns3::Ipv4GlobalRouting::RandomEcmpRouting=false --topo=${TOPO} --sink=${SINK} --sender=${SENDER} --tcpSink=${TCPSINK} --tcpSender=${TCPSENDER}"
# cp $FILE "${DIR}${TOPO}/ospf.txt"
