DGRv2: ns3::DGRCandidateQueue Class Reference
ns3::DGRCandidateQueue Class Reference
A Candidate Queue used in routing calculations.
#include <dgr-candidate-queue.h>
Public Member Functions
DGRCandidateQueue ()
Create an empty SPF Candidate Queue.
virtual ~DGRCandidateQueue ()
Destroy an SPF Candidate Queue and release any resources held by the contents.
void Clear (void)
Empty the Candidate Queue and release all of the resources associated with the Shortest Path First Vertex pointers in the queue.
bool Empty (void) const
Test the Candidate Queue to determine if it is empty.
DGRVertex * Find (const Ipv4Address addr) const
Searches the Candidate Queue for a Shortest Path First Vertex pointer that points to a vertex having the given IP address.
DGRVertex * Pop (void)
Pop the Shortest Path First Vertex pointer at the top of the queue.
void Push (DGRVertex *vNew)
Push a Shortest Path First Vertex pointer onto the queue according to the priority scheme.
void Reorder (void)
Reorders the Candidate Queue according to the priority scheme.
uint32_t Size (void) const
Return the number of Shortest Path First Vertex pointers presently stored in the Candidate Queue.
DGRVertex * Top (void) const
Return the Shortest Path First Vertex pointer at the top of the queue.
Private Types
typedef std::list< DGRVertex * > DGRCandidateList_t
container of DGRVertex pointers
Private Member Functions
DGRCandidateQueue (DGRCandidateQueue &sr)
Candidate Queue copy construction is disallowed (not implemented) to prevent the compiler from slipping in incorrect versions that don't properly deal with deep copies.
DGRCandidateQueue & operator= (DGRCandidateQueue &sr)
Candidate Queue assignment operator is disallowed (not implemented) to prevent the compiler from slipping in incorrect versions that don't properly deal with deep copies.
Static Private Member Functions
static bool CompareDGRVertex (const DGRVertex *v1, const DGRVertex *v2)
return true if v1 < v2
Private Attributes
DGRCandidateList_t m_candidates
DGRVertex candidates.
Friends
std::ostream & operator<< (std::ostream &os, const DGRCandidateQueue &q)
Stream insertion operator.
Detailed Description
A Candidate Queue used in routing calculations.
The CandidateQueue is used in the OSPF shortest path computations. It is a priority queue used to store candidates for the shortest path to a given network.
The queue holds Shortest Path First Vertex pointers and orders them according to the lowest value of the field m_distanceFromRoot. Remaining vertices are ordered according to increasing distance. This implements a priority queue.
Although a STL priority_queue almost does what we want, the requirement for a Find () operation, the dynamic nature of the data and the derived requirement for a Reorder () operation led us to implement this simple enhanced priority queue.
Definition at line 51 of file dgr-candidate-queue.h.
Member Typedef Documentation
DGRCandidateList_t
typedef std::list<DGRVertex*> ns3::DGRCandidateQueue::DGRCandidateList_t private
container of DGRVertex pointers
Definition at line 187 of file dgr-candidate-queue.h.
Constructor & Destructor Documentation
DGRCandidateQueue() [1/2]
ns3::DGRCandidateQueue::DGRCandidateQueue ()
Create an empty SPF Candidate Queue.
See also
DGRVertex
Definition at line 68 of file dgr-candidate-queue.cc.
~DGRCandidateQueue()
ns3::DGRCandidateQueue::~DGRCandidateQueue () virtual
Destroy an SPF Candidate Queue and release any resources held by the contents.
See also
DGRVertex
Definition at line 74 of file dgr-candidate-queue.cc.
References Clear().
DGRCandidateQueue() [2/2]
ns3::DGRCandidateQueue::DGRCandidateQueue (DGRCandidateQueue & sr) private
Candidate Queue copy construction is disallowed (not implemented) to prevent the compiler from slipping in incorrect versions that don't properly deal with deep copies.
Parameters
sr object to copy
Member Function Documentation
Clear()
void ns3::DGRCandidateQueue::Clear (void)
Empty the Candidate Queue and release all of the resources associated with the Shortest Path First Vertex pointers in the queue.
See also
DGRVertex
Definition at line 81 of file dgr-candidate-queue.cc.
References m_candidates, and Pop().
Referenced by ~DGRCandidateQueue().
CompareDGRVertex()
bool ns3::DGRCandidateQueue::CompareDGRVertex (const DGRVertex * v1, const DGRVertex * v2) static private
return true if v1 < v2
DGRVertexes are added into the queue according to the ordering defined by this method. If v1 should be popped before v2, this method return true; false otherwise
Parameters
v1 first operand
v2 second operand
Returns
True if v1 should be popped before v2; false otherwise
Definition at line 180 of file dgr-candidate-queue.cc.
References ns3::DGRVertex::GetDistanceFromRoot(), ns3::DGRVertex::GetVertexType(), ns3::DGRVertex::VertexNetwork, and ns3::DGRVertex::VertexRouter.
Referenced by Push(), and Reorder().
Empty()
bool ns3::DGRCandidateQueue::Empty (void) const
Test the Candidate Queue to determine if it is empty.
Returns
True if the queue is empty, false otherwise.
Definition at line 131 of file dgr-candidate-queue.cc.
References m_candidates.
Find()
DGRVertex * ns3::DGRCandidateQueue::Find (const Ipv4Address addr) const
Searches the Candidate Queue for a Shortest Path First Vertex pointer that points to a vertex having the given IP address.
See also
DGRVertex
Parameters
addr The IP address to search for.
Returns
The DGRVertex* pointer corresponding to the given IP address.
Definition at line 145 of file dgr-candidate-queue.cc.
References ns3::DGRVertex::GetVertexId(), ns3::i, and m_candidates.
Referenced by ns3::DGRRouteManagerImpl::SPFNext().
operator=()
DGRCandidateQueue & ns3::DGRCandidateQueue::operator= (DGRCandidateQueue & sr) private
Candidate Queue assignment operator is disallowed (not implemented) to prevent the compiler from slipping in incorrect versions that don't properly deal with deep copies.
Parameters
sr object to assign
Returns
copied object
Pop()
DGRVertex * ns3::DGRCandidateQueue::Pop (void)
Pop the Shortest Path First Vertex pointer at the top of the queue.
The caller is given the responsibility for releasing the resources associated with the vertex.
See also
DGRVertex
Top ()
Returns
The Shortest Path First Vertex pointer at the top of the queue.
Definition at line 105 of file dgr-candidate-queue.cc.
References m_candidates.
Referenced by Clear(), and ns3::DGRRouteManagerImpl::SPFCalculate().
Push()
void ns3::DGRCandidateQueue::Push (DGRVertex * vNew)
Push a Shortest Path First Vertex pointer onto the queue according to the priority scheme.
On completion, the top of the queue will hold the Shortest Path First Vertex pointer that points to a vertex having lowest value of the field m_distanceFromRoot. Remaining vertices are ordered according to increasing distance.
See also
DGRVertex
Parameters
vNew The Shortest Path First Vertex to add to the queue.
Definition at line 93 of file dgr-candidate-queue.cc.
References CompareDGRVertex(), ns3::i, and m_candidates.
Referenced by ns3::DGRRouteManagerImpl::SPFNext().
Reorder()
void ns3::DGRCandidateQueue::Reorder (void)
Reorders the Candidate Queue according to the priority scheme.
On completion, the top of the queue will hold the Shortest Path First Vertex pointer that points to a vertex having lowest value of the field m_distanceFromRoot. Remaining vertices are ordered according to increasing distance.
This method is provided in case the values of m_distanceFromRoot change during the routing calculations.
See also
DGRVertex
Definition at line 163 of file dgr-candidate-queue.cc.
References CompareDGRVertex(), and m_candidates.
Referenced by ns3::DGRRouteManagerImpl::SPFNext().
Size()
uint32_t ns3::DGRCandidateQueue::Size (void) const
Return the number of Shortest Path First Vertex pointers presently stored in the Candidate Queue.
See also
DGRVertex
Returns
The number of DGRVertex* pointers in the Candidate Queue.
Definition at line 138 of file dgr-candidate-queue.cc.
References m_candidates.
Referenced by ns3::DGRRouteManagerImpl::SPFCalculate().
Top()
DGRVertex * ns3::DGRCandidateQueue::Top (void) const
Return the Shortest Path First Vertex pointer at the top of the queue.
This method does not pop the DGRVertex* off of the queue, it simply returns the pointer.
See also
DGRVertex
Pop ()
Returns
The Shortest Path First Vertex pointer at the top of the queue.
Definition at line 119 of file dgr-candidate-queue.cc.
References m_candidates.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const DGRCandidateQueue & q) friend
Stream insertion operator.
Parameters
os the reference to the output stream
q the CandidateQueue
Returns
the reference to the output stream
Definition at line 49 of file dgr-candidate-queue.cc.
Member Data Documentation
m_candidates
DGRCandidateList_t ns3::DGRCandidateQueue::m_candidates private
DGRVertex candidates.
Definition at line 188 of file dgr-candidate-queue.h.
Referenced by Clear(), Empty(), Find(), Pop(), Push(), Reorder(), Size(), and Top().
The documentation for this class was generated from the following files:
model/dgr-candidate-queue.h
model/dgr-candidate-queue.cc