DGRv2: ns3::Ipv4DGRRoutingTableEntry Class Reference
ns3::Ipv4DGRRoutingTableEntry Class Reference
A record of an IPv4 routing table entry for Ipv4GlobalRouting and Ipv4StaticRouting.
#include <ipv4-dgr-routing-table-entry.h>
Public Member Functions
Ipv4DGRRoutingTableEntry ()
This constructor does nothing.
Ipv4DGRRoutingTableEntry (Ipv4DGRRoutingTableEntry const &route)
Copy Constructor.
Ipv4DGRRoutingTableEntry (Ipv4DGRRoutingTableEntry const *route)
Copy Constructor.
Ipv4Address GetDest (void) const
Ipv4Address GetDestNetwork (void) const
Ipv4Mask GetDestNetworkMask (void) const
uint32_t GetDistance (void) const
Ipv4Address GetGateway (void) const
uint32_t GetInterface (void) const
uint32_t GetNextInterface (void) const
bool IsDefault (void) const
bool IsGateway (void) const
bool IsHost (void) const
bool IsNetwork (void) const
Static Public Member Functions
static Ipv4DGRRoutingTableEntry CreateDefaultRoute (Ipv4Address nextHop, uint32_t interface)
static Ipv4DGRRoutingTableEntry CreateHostRouteTo (Ipv4Address dest, Ipv4Address nextHop, uint32_t interface)
static Ipv4DGRRoutingTableEntry CreateHostRouteTo (Ipv4Address dest, Ipv4Address nextHop, uint32_t interface, uint32_t nextInterface, uint32_t distance)
Create a host route with the distance value
static Ipv4DGRRoutingTableEntry CreateHostRouteTo (Ipv4Address dest, uint32_t interface)
static Ipv4DGRRoutingTableEntry CreateNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, Ipv4Address nextHop, uint32_t interface)
static Ipv4DGRRoutingTableEntry CreateNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, uint32_t interface)
Private Member Functions
Ipv4DGRRoutingTableEntry (Ipv4Address dest, Ipv4Address gateway, uint32_t interface)
Constructor.
Ipv4DGRRoutingTableEntry (Ipv4Address dest, Ipv4Address gateway, uint32_t interface, uint32_t nextInterface, uint32_t distance)
Constructor.
Ipv4DGRRoutingTableEntry (Ipv4Address dest, Ipv4Mask mask, uint32_t interface)
Constructor.
Ipv4DGRRoutingTableEntry (Ipv4Address dest, uint32_t interface)
Constructor.
Ipv4DGRRoutingTableEntry (Ipv4Address network, Ipv4Mask mask, Ipv4Address gateway, uint32_t interface)
Constructor.
Private Attributes
Ipv4Address m_dest
destination address
Ipv4Mask m_destNetworkMask
destination network mask
uint32_t m_distance
the distance between root and destination
Ipv4Address m_gateway
gateway
uint32_t m_interface
output interface
uint32_t m_nextInterface
output interface in next hop
Detailed Description
A record of an IPv4 routing table entry for Ipv4GlobalRouting and Ipv4StaticRouting.
This is not a reference counted object.
Definition at line 19 of file ipv4-dgr-routing-table-entry.h.
Constructor & Destructor Documentation
Ipv4DGRRoutingTableEntry() [1/8]
ns3::Ipv4DGRRoutingTableEntry::Ipv4DGRRoutingTableEntry ()
This constructor does nothing.
Definition at line 16 of file ipv4-dgr-routing-table-entry.cc.
Referenced by CreateDefaultRoute(), CreateHostRouteTo(), CreateHostRouteTo(), CreateHostRouteTo(), CreateNetworkRouteTo(), and CreateNetworkRouteTo().
Ipv4DGRRoutingTableEntry() [2/8]
ns3::Ipv4DGRRoutingTableEntry::Ipv4DGRRoutingTableEntry (Ipv4DGRRoutingTableEntry const & route)
Copy Constructor.
change m_distance (MAX_UINT32) to m_distance (route.m_distance)
Parameters
route The route to copy
Definition at line 24 of file ipv4-dgr-routing-table-entry.cc.
Ipv4DGRRoutingTableEntry() [3/8]
ns3::Ipv4DGRRoutingTableEntry::Ipv4DGRRoutingTableEntry (Ipv4DGRRoutingTableEntry const * route)
Copy Constructor.
Parameters
route The route to copy
Definition at line 36 of file ipv4-dgr-routing-table-entry.cc.
Ipv4DGRRoutingTableEntry() [4/8]
ns3::Ipv4DGRRoutingTableEntry::Ipv4DGRRoutingTableEntry (Ipv4Address network, Ipv4Mask mask, Ipv4Address gateway, uint32_t interface) private
Constructor.
Parameters
network network address
mask network mask
gateway the gateway
interface the interface index
Definition at line 70 of file ipv4-dgr-routing-table-entry.cc.
Ipv4DGRRoutingTableEntry() [5/8]
ns3::Ipv4DGRRoutingTableEntry::Ipv4DGRRoutingTableEntry (Ipv4Address dest, Ipv4Mask mask, uint32_t interface) private
Constructor.
Parameters
dest destination address
mask network mask
interface the interface index
Definition at line 84 of file ipv4-dgr-routing-table-entry.cc.
Ipv4DGRRoutingTableEntry() [6/8]
ns3::Ipv4DGRRoutingTableEntry::Ipv4DGRRoutingTableEntry (Ipv4Address dest, Ipv4Address gateway, uint32_t interface) private
Constructor.
Parameters
dest destination address
gateway the gateway
interface the interface index
Definition at line 47 of file ipv4-dgr-routing-table-entry.cc.
Ipv4DGRRoutingTableEntry() [7/8]
ns3::Ipv4DGRRoutingTableEntry::Ipv4DGRRoutingTableEntry (Ipv4Address dest, uint32_t interface) private
Constructor.
Parameters
dest destination address
interface the interface index
Definition at line 59 of file ipv4-dgr-routing-table-entry.cc.
Ipv4DGRRoutingTableEntry() [8/8]
ns3::Ipv4DGRRoutingTableEntry::Ipv4DGRRoutingTableEntry (Ipv4Address dest, Ipv4Address gateway, uint32_t interface, uint32_t nextInterface, uint32_t distance) private
Constructor.
Parameters
dest destination address
gateway gateway address
interface the interface index
nextInterface the interface index in next hop
distance the distance between root and destination
Author
Pu Yang
Parameters
dest destination address
interface the interface index
distance the distance between root and dest
Definition at line 104 of file ipv4-dgr-routing-table-entry.cc.
Member Function Documentation
CreateDefaultRoute()
Ipv4DGRRoutingTableEntry ns3::Ipv4DGRRoutingTableEntry::CreateDefaultRoute (Ipv4Address nextHop, uint32_t interface) static
Returns
An Ipv4RoutingTableEntry object corresponding to the input parameters. This route is distinguished; it will match any destination for which a more specific route does not exist.
Parameters
nextHop Ipv4Address of the next hop
interface Outgoing interface
Definition at line 263 of file ipv4-dgr-routing-table-entry.cc.
References Ipv4DGRRoutingTableEntry().
CreateHostRouteTo() [1/3]
Ipv4DGRRoutingTableEntry ns3::Ipv4DGRRoutingTableEntry::CreateHostRouteTo (Ipv4Address dest, Ipv4Address nextHop, uint32_t interface) static
Returns
An Ipv4RoutingTableEntry object corresponding to the input parameters.
Parameters
dest Ipv4Address of the destination
nextHop Ipv4Address of the next hop
interface Outgoing interface
Definition at line 212 of file ipv4-dgr-routing-table-entry.cc.
References Ipv4DGRRoutingTableEntry().
Referenced by ns3::Ipv4DGRRouting::AddHostRouteTo(), ns3::Ipv4DGRRouting::AddHostRouteTo(), and ns3::Ipv4DGRRouting::AddHostRouteTo().
CreateHostRouteTo() [2/3]
Ipv4DGRRoutingTableEntry ns3::Ipv4DGRRoutingTableEntry::CreateHostRouteTo (Ipv4Address dest, Ipv4Address nextHop, uint32_t interface, uint32_t nextInterface, uint32_t distance) static
Create a host route with the distance value
Author
Pu Yang
Returns
An Ipv4RoutingTableEntry object corresponding to the input parameters.
Parameters
dest Ipv4Address of the destination
nextHop the Ipv4Address the nextHop
interface Outgoing interface
nextInterface Outgoing interface in next hop
distance The distance between root and destination
Author
Pu Yang
Definition at line 232 of file ipv4-dgr-routing-table-entry.cc.
References Ipv4DGRRoutingTableEntry().
CreateHostRouteTo() [3/3]
Ipv4DGRRoutingTableEntry ns3::Ipv4DGRRoutingTableEntry::CreateHostRouteTo (Ipv4Address dest, uint32_t interface) static
Returns
An Ipv4RoutingTableEntry object corresponding to the input parameters.
Parameters
dest Ipv4Address of the destination
interface Outgoing interface
Definition at line 220 of file ipv4-dgr-routing-table-entry.cc.
References Ipv4DGRRoutingTableEntry().
CreateNetworkRouteTo() [1/2]
Ipv4DGRRoutingTableEntry ns3::Ipv4DGRRoutingTableEntry::CreateNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, Ipv4Address nextHop, uint32_t interface) static
Returns
An Ipv4RoutingTableEntry object corresponding to the input parameters.
Parameters
network Ipv4Address of the destination network
networkMask Ipv4Mask of the destination network mask
nextHop Ipv4Address of the next hop
interface Outgoing interface
Definition at line 244 of file ipv4-dgr-routing-table-entry.cc.
References Ipv4DGRRoutingTableEntry().
Referenced by ns3::Ipv4DGRRouting::AddASExternalRouteTo(), ns3::Ipv4DGRRouting::AddNetworkRouteTo(), ns3::Ipv4DGRRouting::AddNetworkRouteTo(), and ns3::DGRRouter::InjectRoute().
CreateNetworkRouteTo() [2/2]
Ipv4DGRRoutingTableEntry ns3::Ipv4DGRRoutingTableEntry::CreateNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, uint32_t interface) static
Returns
An Ipv4RoutingTableEntry object corresponding to the input parameters.
Parameters
network Ipv4Address of the destination network
networkMask Ipv4Mask of the destination network mask
interface Outgoing interface
Definition at line 254 of file ipv4-dgr-routing-table-entry.cc.
References Ipv4DGRRoutingTableEntry().
GetDest()
Ipv4Address ns3::Ipv4DGRRoutingTableEntry::GetDest (void) const
Returns
The IPv4 address of the destination of this route
Definition at line 134 of file ipv4-dgr-routing-table-entry.cc.
References m_dest.
Referenced by ns3::Ipv4DGRRouting::LookupDGRRoute(), ns3::Ipv4DGRRouting::LookupUniRoute(), ns3::operator<<(), ns3::operator==(), and ns3::Ipv4DGRRouting::PrintRoutingTable().
GetDestNetwork()
Ipv4Address ns3::Ipv4DGRRoutingTableEntry::GetDestNetwork (void) const
Returns
The IPv4 network number of the destination of this route
Definition at line 159 of file ipv4-dgr-routing-table-entry.cc.
References m_dest.
Referenced by ns3::operator<<().
GetDestNetworkMask()
Ipv4Mask ns3::Ipv4DGRRoutingTableEntry::GetDestNetworkMask (void) const
Returns
The IPv4 network mask of the destination of this route
Definition at line 165 of file ipv4-dgr-routing-table-entry.cc.
References m_destNetworkMask.
Referenced by ns3::operator<<(), and ns3::operator==().
GetDistance()
uint32_t ns3::Ipv4DGRRoutingTableEntry::GetDistance (void) const
Returns
the distance
Definition at line 205 of file ipv4-dgr-routing-table-entry.cc.
References m_distance.
Referenced by ns3::Ipv4DGRRouting::LookupDGRRoute(), and ns3::Ipv4DGRRouting::PrintRoutingTable().
GetGateway()
Ipv4Address ns3::Ipv4DGRRoutingTableEntry::GetGateway (void) const
Returns
address of the gateway stored in this entry
Definition at line 184 of file ipv4-dgr-routing-table-entry.cc.
References m_gateway.
Referenced by ns3::Ipv4DGRRouting::LookupDGRRoute(), ns3::Ipv4DGRRouting::LookupUniRoute(), ns3::operator<<(), ns3::operator==(), and ns3::Ipv4DGRRouting::PrintRoutingTable().
GetInterface()
uint32_t ns3::Ipv4DGRRoutingTableEntry::GetInterface (void) const
Returns
The Ipv4 interface number used for sending outgoing packets
Definition at line 191 of file ipv4-dgr-routing-table-entry.cc.
References m_interface.
Referenced by ns3::Ipv4DGRRouting::LookupDGRRoute(), ns3::Ipv4DGRRouting::LookupUniRoute(), ns3::operator<<(), ns3::operator==(), and ns3::Ipv4DGRRouting::PrintRoutingTable().
GetNextInterface()
uint32_t ns3::Ipv4DGRRoutingTableEntry::GetNextInterface (void) const
Returns
The Ipv4 interface number used for sending outgoing packets in the next hop
Definition at line 198 of file ipv4-dgr-routing-table-entry.cc.
References m_nextInterface.
Referenced by ns3::Ipv4DGRRouting::PrintRoutingTable().
IsDefault()
bool ns3::Ipv4DGRRoutingTableEntry::IsDefault (void) const
Returns
True if this route is a default route; false otherwise
Definition at line 146 of file ipv4-dgr-routing-table-entry.cc.
References m_dest.
Referenced by ns3::operator<<().
IsGateway()
bool ns3::Ipv4DGRRoutingTableEntry::IsGateway (void) const
Returns
True if this route is a gateway route; false otherwise
Definition at line 171 of file ipv4-dgr-routing-table-entry.cc.
References m_gateway.
Referenced by ns3::operator<<(), and ns3::Ipv4DGRRouting::PrintRoutingTable().
IsHost()
bool ns3::Ipv4DGRRoutingTableEntry::IsHost (void) const
Returns
True if this route is a host route (mask of all ones); false otherwise
Definition at line 121 of file ipv4-dgr-routing-table-entry.cc.
References m_destNetworkMask.
Referenced by IsNetwork(), ns3::operator<<(), and ns3::Ipv4DGRRouting::PrintRoutingTable().
IsNetwork()
bool ns3::Ipv4DGRRoutingTableEntry::IsNetwork (void) const
Returns
True if this route is not a host route (mask is not all ones); false otherwise
This method is implemented as !IsHost ().
Definition at line 140 of file ipv4-dgr-routing-table-entry.cc.
References IsHost().
Referenced by ns3::operator<<().
Member Data Documentation
m_dest
Ipv4Address ns3::Ipv4DGRRoutingTableEntry::m_dest private
destination address
Definition at line 194 of file ipv4-dgr-routing-table-entry.h.
Referenced by GetDest(), GetDestNetwork(), and IsDefault().
m_destNetworkMask
Ipv4Mask ns3::Ipv4DGRRoutingTableEntry::m_destNetworkMask private
destination network mask
Definition at line 195 of file ipv4-dgr-routing-table-entry.h.
Referenced by GetDestNetworkMask(), and IsHost().
m_distance
uint32_t ns3::Ipv4DGRRoutingTableEntry::m_distance private
the distance between root and destination
Definition at line 199 of file ipv4-dgr-routing-table-entry.h.
Referenced by GetDistance().
m_gateway
Ipv4Address ns3::Ipv4DGRRoutingTableEntry::m_gateway private
gateway
Definition at line 196 of file ipv4-dgr-routing-table-entry.h.
Referenced by GetGateway(), and IsGateway().
m_interface
uint32_t ns3::Ipv4DGRRoutingTableEntry::m_interface private
output interface
Definition at line 197 of file ipv4-dgr-routing-table-entry.h.
Referenced by GetInterface().
m_nextInterface
uint32_t ns3::Ipv4DGRRoutingTableEntry::m_nextInterface private
output interface in next hop
Definition at line 198 of file ipv4-dgr-routing-table-entry.h.
Referenced by GetNextInterface().
The documentation for this class was generated from the following files:
model/ipv4-dgr-routing-table-entry.h
model/ipv4-dgr-routing-table-entry.cc