DGRv2: ns3::FlagTag Class Reference
ns3::FlagTag Class Reference
This class implements a tag that carries a flag to the application layer.
#include <dgr-tags.h>
Public Member Functions
FlagTag ()
void Deserialize (TagBuffer i) override
bool GetFlag (void) const
Get the tag's flag.
TypeId GetInstanceTypeId (void) const override
uint32_t GetSerializedSize (void) const override
void Print (std::ostream &os) const override
void Serialize (TagBuffer i) const override
void SetFlag (bool flag)
Set the tag's flag.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the Type ID.
Private Attributes
bool m_flag
Detailed Description
This class implements a tag that carries a flag to the application layer.
Definition at line 108 of file dgr-tags.h.
Constructor & Destructor Documentation
FlagTag()
ns3::FlagTag::FlagTag ()
Definition at line 164 of file dgr-tags.cc.
Member Function Documentation
Deserialize()
void ns3::FlagTag::Deserialize (TagBuffer i) override
Definition at line 215 of file dgr-tags.cc.
References ns3::i, and m_flag.
GetFlag()
bool ns3::FlagTag::GetFlag (void) const
Get the tag's flag.
Returns
the flag
Definition at line 177 of file dgr-tags.cc.
References m_flag.
Referenced by ns3::DGRPacketSink::HandleRead().
GetInstanceTypeId()
TypeId ns3::FlagTag::GetInstanceTypeId (void) const override
Definition at line 194 of file dgr-tags.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::FlagTag::GetSerializedSize (void) const override
Definition at line 200 of file dgr-tags.cc.
GetTypeId()
TypeId ns3::FlagTag::GetTypeId (void) static
Get the Type ID.
Returns
the object TypeId
Definition at line 184 of file dgr-tags.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::FlagTag::Print (std::ostream & os) const override
Definition at line 224 of file dgr-tags.cc.
References m_flag.
Serialize()
void ns3::FlagTag::Serialize (TagBuffer i) const override
Definition at line 207 of file dgr-tags.cc.
References ns3::i, and m_flag.
SetFlag()
void ns3::FlagTag::SetFlag (bool flag)
Set the tag's flag.
Parameters
flag the flag
Definition at line 170 of file dgr-tags.cc.
References m_flag.
Referenced by ns3::DGRTcpApplication::SendData(), and ns3::DGRUdpApplication::SendPacket().
Member Data Documentation
m_flag
bool ns3::FlagTag::m_flag private
Definition at line 147 of file dgr-tags.h.
Referenced by Deserialize(), GetFlag(), Print(), Serialize(), and SetFlag().
The documentation for this class was generated from the following files:
model/dgr-tags.h
model/dgr-tags.cc