DGRv2: ns3::PriorityTag Class Reference
ns3::PriorityTag Class Reference
#include <dgr-tags.h>
Public Member Functions
PriorityTag ()
void Deserialize (TagBuffer i) override
TypeId GetInstanceTypeId (void) const override
uint32_t GetPriority (void) const
Get the tag's priority.
uint32_t GetSerializedSize (void) const override
void Print (std::ostream &os) const override
void Serialize (TagBuffer i) const override
void SetPriority (uint32_t priority)
Set the tag's priority.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the Type ID.
Private Attributes
uint32_t m_priority
Detailed Description
Definition at line 150 of file dgr-tags.h.
Constructor & Destructor Documentation
PriorityTag()
ns3::PriorityTag::PriorityTag ()
Definition at line 235 of file dgr-tags.cc.
Member Function Documentation
Deserialize()
void ns3::PriorityTag::Deserialize (TagBuffer i) override
Definition at line 286 of file dgr-tags.cc.
References ns3::i, and m_priority.
GetInstanceTypeId()
TypeId ns3::PriorityTag::GetInstanceTypeId (void) const override
Definition at line 265 of file dgr-tags.cc.
References GetTypeId().
GetPriority()
uint32_t ns3::PriorityTag::GetPriority (void) const
Get the tag's priority.
Returns
the priority
Definition at line 248 of file dgr-tags.cc.
References m_priority.
GetSerializedSize()
uint32_t ns3::PriorityTag::GetSerializedSize (void) const override
Definition at line 271 of file dgr-tags.cc.
GetTypeId()
TypeId ns3::PriorityTag::GetTypeId (void) static
Get the Type ID.
Returns
the object TypeId
Definition at line 255 of file dgr-tags.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::PriorityTag::Print (std::ostream & os) const override
Definition at line 295 of file dgr-tags.cc.
References m_priority.
Serialize()
void ns3::PriorityTag::Serialize (TagBuffer i) const override
Definition at line 278 of file dgr-tags.cc.
References ns3::i, and m_priority.
SetPriority()
void ns3::PriorityTag::SetPriority (uint32_t priority)
Set the tag's priority.
Parameters
priority the priority
Definition at line 241 of file dgr-tags.cc.
References m_priority.
Referenced by ns3::DGRUdpApplication::SendPacket().
Member Data Documentation
m_priority
uint32_t ns3::PriorityTag::m_priority private
Definition at line 189 of file dgr-tags.h.
Referenced by Deserialize(), GetPriority(), Print(), Serialize(), and SetPriority().
The documentation for this class was generated from the following files:
model/dgr-tags.h
model/dgr-tags.cc