DGRv2: ns3::DgrHeader Class Reference
ns3::DgrHeader Class Reference
dgr header
#include <dgr-header.h>
Public Types
enum Command_e { REQUEST = 0x1 , RESPONSE = 0x2 }
Commands to be used in Dgr headers.
Public Member Functions
DgrHeader ()
void AddNse (DgrNse nse)
Add a DGR Neighbor Status Entry (NSE) to the message.
void ClearNses ()
Clear all the NSEs from the header.
uint32_t Deserialize (Buffer::Iterator start) override
Deserialize the packet.
Command_e GetCommand () const
Get the command.
TypeId GetInstanceTypeId () const override
Return the instance type identifier.
std::list< DgrNse > GetNseList () const
Get the list of NSEs included in the message.
uint16_t GetNseNumber () const
Get the number of NSEs includes in the message.
uint32_t GetSerializedSize () const override
Get the serialized size of the packet.
void Print (std::ostream &os) const override
void Serialize (Buffer::Iterator start) const override
Serialize the packet.
void SetCommand (Command_e command)
Set the command.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Private Attributes
uint8_t m_command
command type
std::list< DgrNse > m_nseList
list of the DNEs in the message
Detailed Description
dgr header
Definition at line 95 of file dgr-header.h.
Member Enumeration Documentation
Command_e
enum ns3::DgrHeader::Command_e
Commands to be used in Dgr headers.
Enumerator
REQUEST
RESPONSE
Definition at line 136 of file dgr-header.h.
Constructor & Destructor Documentation
DgrHeader()
ns3::DgrHeader::DgrHeader ()
Definition at line 103 of file dgr-header.cc.
Member Function Documentation
AddNse()
void ns3::DgrHeader::AddNse (DgrNse nse)
Add a DGR Neighbor Status Entry (NSE) to the message.
Parameters
nse the Neighbor Status Entry
Definition at line 214 of file dgr-header.cc.
References m_nseList.
Referenced by ns3::Ipv4DGRRouting::DoSendNeighborStatusUpdate().
ClearNses()
void ns3::DgrHeader::ClearNses ()
Clear all the NSEs from the header.
Definition at line 220 of file dgr-header.cc.
References m_nseList.
Referenced by ns3::Ipv4DGRRouting::DoSendNeighborStatusUpdate().
Deserialize()
uint32_t ns3::DgrHeader::Deserialize (Buffer::Iterator start) override
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Definition at line 162 of file dgr-header.cc.
References ns3::DgrNse::Deserialize(), ns3::DgrNse::GetSerializedSize(), GetSerializedSize(), ns3::i, m_command, m_nseList, REQUEST, and RESPONSE.
GetCommand()
DgrHeader::Command_e ns3::DgrHeader::GetCommand () const
Get the command.
Returns
the command
Definition at line 208 of file dgr-header.cc.
References m_command.
Referenced by ns3::Ipv4DGRRouting::Receive().
GetInstanceTypeId()
TypeId ns3::DgrHeader::GetInstanceTypeId () const override
Return the instance type identifier.
Returns
the object TypeId
Definition at line 119 of file dgr-header.cc.
References GetTypeId().
GetNseList()
std::list< DgrNse > ns3::DgrHeader::GetNseList () const
Get the list of NSEs included in the message.
Returns
the list of DNEs in the message
Definition at line 232 of file dgr-header.cc.
References m_nseList.
Referenced by ns3::Ipv4DGRRouting::HandleResponses().
GetNseNumber()
uint16_t ns3::DgrHeader::GetNseNumber () const
Get the number of NSEs includes in the message.
Returns
the number of DNEs in the message
Definition at line 226 of file dgr-header.cc.
References m_nseList.
Referenced by ns3::Ipv4DGRRouting::DoSendNeighborStatusUpdate().
GetSerializedSize()
uint32_t ns3::DgrHeader::GetSerializedSize () const override
Get the serialized size of the packet.
Returns
size
Definition at line 138 of file dgr-header.cc.
References ns3::DgrNse::GetSerializedSize(), and m_nseList.
Referenced by Deserialize(), ns3::Ipv4DGRRouting::DoSendNeighborStatusUpdate(), and ns3::Ipv4DGRRouting::HandleResponses().
GetTypeId()
TypeId ns3::DgrHeader::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 109 of file dgr-header.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::DgrHeader::Print (std::ostream & os) const override
Definition at line 125 of file dgr-header.cc.
References m_command, and m_nseList.
Referenced by ns3::operator<<().
Serialize()
void ns3::DgrHeader::Serialize (Buffer::Iterator start) const override
Serialize the packet.
Parameters
start Buffer iterator
Definition at line 145 of file dgr-header.cc.
References ns3::i, m_command, and m_nseList.
SetCommand()
void ns3::DgrHeader::SetCommand (Command_e command)
Set the command.
Parameters
command the command
Definition at line 202 of file dgr-header.cc.
References m_command.
Referenced by ns3::Ipv4DGRRouting::DoSendNeighborStatusUpdate().
Member Data Documentation
m_command
uint8_t ns3::DgrHeader::m_command private
command type
Definition at line 178 of file dgr-header.h.
Referenced by Deserialize(), GetCommand(), Print(), Serialize(), and SetCommand().
m_nseList
std::list<DgrNse> ns3::DgrHeader::m_nseList private
list of the DNEs in the message
Definition at line 179 of file dgr-header.h.
Referenced by AddNse(), ClearNses(), Deserialize(), GetNseList(), GetNseNumber(), GetSerializedSize(), Print(), and Serialize().
The documentation for this class was generated from the following files:
model/dgr-header.h
model/dgr-header.cc