DGRv2: ns3::Ipv4DGRRoutingHelper Class Reference
ns3::Ipv4DGRRoutingHelper Class Reference
Helper class that adds ns3::Ipv4GlobalRouting objects.
#include <ipv4-dgr-routing-helper.h>
Public Member Functions
Ipv4DGRRoutingHelper ()
Construct a GlobalRoutingHelper to make life easier for managing global routing tasks.
Ipv4DGRRoutingHelper (const Ipv4DGRRoutingHelper &)
Construct a GlobalRoutingHelper from another previously initialized instance (Copy Constructor).
Ipv4DGRRoutingHelper * Copy (void) const
virtual Ptr< Ipv4RoutingProtocol > Create (Ptr< Node > node) const
QueueDiscContainer Install (NetDeviceContainer c)
This method create the DGRv2 QueueDisc (along with it's internal queues, classes) configured with the methods provided by this class and installs them on the given node. Additionally, if configured, a queue limits object is installed on each transmission queue of the device.
QueueDiscContainer Install (Ptr< NetDevice > d)
This method intall DGRv2Queue into NetDevice.
QueueDiscContainer Install (Ptr< Node > node)
This method create the DGRv2 QueueDisc (along with it's internal queues, classes) configured with the methods provided by this class and installs them on the given node. Additionally, if configured, a queue limits object is installed on each transmission queue of the device.
Static Public Member Functions
static void PopulateRoutingTables (void)
Build a routing database and initialize the routing tables of the nodes in the simulation.
static void RecomputeRoutingTables (void)
Remove all routes that were previously installed in a prior call to either PopulateRoutingTables() or RecomputeRoutingTables(), and add a new set of routes.
Private Member Functions
Ipv4DGRRoutingHelper & operator= (const Ipv4DGRRoutingHelper &)
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Detailed Description
Helper class that adds ns3::Ipv4GlobalRouting objects.
Definition at line 38 of file ipv4-dgr-routing-helper.h.
Constructor & Destructor Documentation
Ipv4DGRRoutingHelper() [1/2]
ns3::Ipv4DGRRoutingHelper::Ipv4DGRRoutingHelper ()
Construct a GlobalRoutingHelper to make life easier for managing global routing tasks.
Definition at line 31 of file ipv4-dgr-routing-helper.cc.
Referenced by Copy().
Ipv4DGRRoutingHelper() [2/2]
ns3::Ipv4DGRRoutingHelper::Ipv4DGRRoutingHelper (const Ipv4DGRRoutingHelper & o)
Construct a GlobalRoutingHelper from another previously initialized instance (Copy Constructor).
Definition at line 35 of file ipv4-dgr-routing-helper.cc.
Member Function Documentation
Copy()
Ipv4DGRRoutingHelper * ns3::Ipv4DGRRoutingHelper::Copy (void) const
Returns
pointer to clone of this Ipv4GlobalRoutingHelper
This method is mainly for internal use by the other helpers; clients are expected to free the dynamic memory allocated by this method
Definition at line 40 of file ipv4-dgr-routing-helper.cc.
References Ipv4DGRRoutingHelper().
Create()
Ptr< Ipv4RoutingProtocol > ns3::Ipv4DGRRoutingHelper::Create (Ptr< Node > node) const virtual
Parameters
node the node on which the routing protocol will run
Returns
a newly-created routing protocol
This method will be called by ns3::InternetStackHelper::Install
Definition at line 46 of file ipv4-dgr-routing-helper.cc.
Install() [1/3]
QueueDiscContainer ns3::Ipv4DGRRoutingHelper::Install (NetDeviceContainer c)
This method create the DGRv2 QueueDisc (along with it's internal queues, classes) configured with the methods provided by this class and installs them on the given node. Additionally, if configured, a queue limits object is installed on each transmission queue of the device.
Parameters
c netdevic container
Returns
a QeueuDisc container with the root queue disc installed on the device
Definition at line 90 of file ipv4-dgr-routing-helper.cc.
References ns3::i, and Install().
Install() [2/3]
QueueDiscContainer ns3::Ipv4DGRRoutingHelper::Install (Ptr< NetDevice > d)
This method intall DGRv2Queue into NetDevice.
Definition at line 101 of file ipv4-dgr-routing-helper.cc.
Install() [3/3]
QueueDiscContainer ns3::Ipv4DGRRoutingHelper::Install (Ptr< Node > node)
This method create the DGRv2 QueueDisc (along with it's internal queues, classes) configured with the methods provided by this class and installs them on the given node. Additionally, if configured, a queue limits object is installed on each transmission queue of the device.
Parameters
node Node
Returns
a QueueDisc container with the queue discs installed on the node
Definition at line 79 of file ipv4-dgr-routing-helper.cc.
References ns3::i, and Install().
Referenced by Install(), and Install().
operator=()
Ipv4DGRRoutingHelper & ns3::Ipv4DGRRoutingHelper::operator= (const Ipv4DGRRoutingHelper &) private
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Returns
PopulateRoutingTables()
void ns3::Ipv4DGRRoutingHelper::PopulateRoutingTables (void) static
Build a routing database and initialize the routing tables of the nodes in the simulation.
Makes all nodes in the simulation into routers.
All this function does is call the functions BuildGlobalRoutingDatabase () and InitializeRoutes ().
Definition at line 64 of file ipv4-dgr-routing-helper.cc.
References ns3::DGRRouteManager::BuildDGRRoutingDatabase(), and ns3::DGRRouteManager::InitializeRoutes().
RecomputeRoutingTables()
void ns3::Ipv4DGRRoutingHelper::RecomputeRoutingTables (void) static
Remove all routes that were previously installed in a prior call to either PopulateRoutingTables() or RecomputeRoutingTables(), and add a new set of routes.
This method does not change the set of nodes over which GlobalRouting is being used, but it will dynamically update its representation of the global topology before recomputing routes. Users must first call PopulateRoutingTables() and then may subsequently call RecomputeRoutingTables() at any later time in the simulation.
Definition at line 70 of file ipv4-dgr-routing-helper.cc.
References ns3::DGRRouteManager::BuildDGRRoutingDatabase(), ns3::DGRRouteManager::DeleteDGRRoutes(), and ns3::DGRRouteManager::InitializeRoutes().
The documentation for this class was generated from the following files:
helper/ipv4-dgr-routing-helper.h
helper/ipv4-dgr-routing-helper.cc