DGRv2: ns3::StatusUnit Class Reference
ns3::StatusUnit Class Reference
#include <neighbor-status-database.h>
Public Member Functions
StatusUnit ()
~StatusUnit ()
int GetCurrentState () const
int GetLastState () const
void Print (std::ostream &os) const
void Update (int state)
Private Attributes
int m_matrix [STATESIZE][STATESIZE]
int m_state
Detailed Description
Definition at line 12 of file neighbor-status-database.h.
Constructor & Destructor Documentation
StatusUnit()
ns3::StatusUnit::StatusUnit ()
Definition at line 10 of file neighbor-status-database.cc.
~StatusUnit()
ns3::StatusUnit::~StatusUnit ()
Definition at line 16 of file neighbor-status-database.cc.
Member Function Documentation
GetCurrentState()
int ns3::StatusUnit::GetCurrentState () const
Definition at line 21 of file neighbor-status-database.cc.
References ns3::i, m_matrix, and m_state.
Referenced by ns3::Ipv4DGRRouting::HandleResponses(), ns3::Ipv4DGRRouting::LookupDGRRoute(), and Print().
GetLastState()
int ns3::StatusUnit::GetLastState () const
Definition at line 37 of file neighbor-status-database.cc.
References m_state.
Referenced by Print().
Print()
void ns3::StatusUnit::Print (std::ostream & os) const
Definition at line 50 of file neighbor-status-database.cc.
References GetCurrentState(), GetLastState(), ns3::i, and m_matrix.
Update()
void ns3::StatusUnit::Update (int state)
Definition at line 43 of file neighbor-status-database.cc.
References m_matrix, and m_state.
Referenced by ns3::Ipv4DGRRouting::HandleResponses().
Member Data Documentation
m_matrix
int ns3::StatusUnit::m_matrix[STATESIZE][STATESIZE] private
Definition at line 22 of file neighbor-status-database.h.
Referenced by GetCurrentState(), Print(), and Update().
m_state
int ns3::StatusUnit::m_state private
Definition at line 23 of file neighbor-status-database.h.
Referenced by GetCurrentState(), GetLastState(), and Update().
The documentation for this class was generated from the following files:
model/neighbor-status-database.h
model/neighbor-status-database.cc