DGRv2: ns3::Ipv4DGRRouting Class Reference
ns3::Ipv4DGRRouting Class Reference
Global routing protocol for IPv4 stacks.
#include <ipv4-dgr-routing.h>
Public Member Functions
Ipv4DGRRouting ()
Construct an empty Ipv4GlobalRouting routing protocol,.
~Ipv4DGRRouting ()
void AddASExternalRouteTo (Ipv4Address network, Ipv4Mask networkMask, Ipv4Address nextHop, uint32_t interface)
Add an external route to the global routing table.
void AddHostRouteTo (Ipv4Address dest, Ipv4Address nextHop, uint32_t interface)
Add a host route to the global routing table.
void AddHostRouteTo (Ipv4Address dest, Ipv4Address nextHop, uint32_t interface, uint32_t nextInterface, uint32_t distance)
Add a host route to the global routing table with the distance between root and destination.
void AddHostRouteTo (Ipv4Address dest, uint32_t interface)
Add a host route to the global routing table.
void AddNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, Ipv4Address nextHop, uint32_t interface)
Add a network route to the global routing table.
void AddNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, uint32_t interface)
Add a network route to the global routing table.
int64_t AssignStreams (int64_t stream)
Build the routing database by gathering Link State Advertisements from each node exporting a DGRRouter interface.
void DoInitialize () override
Start protocol operation.
uint32_t GetNRoutes (void) const
Get the number of individual unicast routes that have been added to the routing table.
Ipv4DGRRoutingTableEntry * GetRoute (uint32_t i) const
Get a route from the global unicast routing table.
Ptr< Ipv4Route > LookupDGRRoute (Ipv4Address dest, Ptr< Packet > p, Ptr< const NetDevice > idev=0)
Ptr< Ipv4Route > LookupUniRoute (Ipv4Address dest, Ptr< NetDevice > oif=0)
Lookup in the forwarding table for destination.
void NotifyAddAddress (uint32_t interface, Ipv4InterfaceAddress address)
void NotifyInterfaceDown (uint32_t interface)
void NotifyInterfaceUp (uint32_t interface)
void NotifyRemoveAddress (uint32_t interface, Ipv4InterfaceAddress address)
void PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S) const
void RemoveRoute (uint32_t i)
Remove a route from the global unicast routing table.
bool RouteInput (Ptr< const Packet > p, const Ipv4Header &header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb)
Ptr< Ipv4Route > RouteOutput (Ptr< Packet > p, const Ipv4Header &header, Ptr< NetDevice > oif, Socket::SocketErrno &sockerr)
void SetIpv4 (Ptr< Ipv4 > ipv4)
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
void DoDispose (void) override
Dispose this object.
Private Types
typedef std::list< Ipv4DGRRoutingTableEntry * > ASExternalRoutes
container of Ipv4RoutingTableEntry (routes to external AS)
typedef std::list< Ipv4DGRRoutingTableEntry * >::const_iterator ASExternalRoutesCI
const iterator of container of Ipv4RoutingTableEntry (routes to external AS)
typedef std::list< Ipv4DGRRoutingTableEntry * >::iterator ASExternalRoutesI
iterator of container of Ipv4RoutingTableEntry (routes to external AS)
typedef std::list< Ipv4DGRRoutingTableEntry * > HostRoutes
container of Ipv4RoutingTableEntry (routes to hosts)
typedef std::list< Ipv4DGRRoutingTableEntry * >::const_iterator HostRoutesCI
const iterator of container of Ipv4RoutingTableEntry (routes to hosts)
typedef std::list< Ipv4DGRRoutingTableEntry * >::iterator HostRoutesI
iterator of container of Ipv4RoutingTableEntry (routes to hosts)
typedef std::list< Ipv4DGRRoutingTableEntry * > NetworkRoutes
container of Ipv4RoutingTableEntry (routes to networks)
typedef std::list< Ipv4DGRRoutingTableEntry * >::const_iterator NetworkRoutesCI
const iterator of container of Ipv4RoutingTableEntry (routes to networks)
typedef std::list< Ipv4DGRRoutingTableEntry * >::iterator NetworkRoutesI
iterator of container of Ipv4RoutingTableEntry (routes to networks)
typedef std::map< Ptr< Socket >, uint32_t > SocketList
One socket per interface, each bound to that interface's address (reason: for Neighbor status sensing, we need to know on which interface the messages arrive)
typedef std::map< Ptr< Socket >, uint32_t >::const_iterator SocketListCI
socket list type const iterator
typedef std::map< Ptr< Socket >, uint32_t >::iterator SocketListI
socket list type iterator
Private Member Functions
void DoSendNeighborStatusUpdate (bool periodic)
Sending Neighbor Status Updates on all interfaces.
void HandleResponses (DgrHeader hdr, Ipv4Address senderAddress, uint32_t incomingInterface, uint8_t hopLimit)
Handle DGR responses.
void Receive (Ptr< Socket > socket)
Receive an DGR message.
void SendTriggeredNeighborStatusUpdate ()
Send Triggered Routing Updates on all interfaces.
void SendUnsolicitedUpdate ()
Send Unsolicited neighbor status information Updates on all interfaces.
Private Attributes
ASExternalRoutes m_ASexternalRoutes
External routes imported.
HostRoutes m_hostRoutes
Routes to hosts.
bool m_initialized
flag to allow socket's late-creation.
std::set< uint32_t > m_interfaceExclusions
Set of excluded interfaces.
Ptr< Ipv4 > m_ipv4
associated IPv4 instance
Ptr< Socket > m_multicastRecvSocket
multicast receive socket
NetworkRoutes m_networkRoutes
Routes to networks.
EventId m_nextTriggeredUpdate
Next Triggered Update event.
EventId m_nextUnsolicitedUpdate
Next Unsolicited Update event.
DgrNSDB m_nsdb
the Neighbor State DataBase (NSDB) of the DGR Rout
Ptr< OutputStreamWrapper > m_outStream
Ptr< UniformRandomVariable > m_rand
A uniform random number generator for randomly routing packets among ECMP.
bool m_randomEcmpRouting
Set to true if packets are randomly routed among ECMP; set to false for using only one route consistently.
bool m_respondToInterfaceEvents
Set to true if this interface should respond to interface events by globallly recomputing routes.
SocketList m_unicastSocketList
list of sockets for unicast messages (socket, interface index)
Time m_unsolicitedUpdate
Time between two Unsolicited Neighbor State Updates.
Detailed Description
Global routing protocol for IPv4 stacks.
In ns-3 we have the concept of a pluggable routing protocol. Routing protocols are added to a list maintained by the Ipv4L3Protocol. Every stack gets one routing protocol for free – the Ipv4StaticRouting routing protocol is added in the constructor of the Ipv4L3Protocol (this is the piece of code that implements the functionality of the IP layer).
As an option to running a dynamic routing protocol, a GlobalRouteManager object has been created to allow users to build routes for all participating nodes. One can think of this object as a "routing oracle"; it has an omniscient view of the topology, and can construct shortest path routes between all pairs of nodes. These routes must be stored somewhere in the node, so therefore this class Ipv4GlobalRouting is used as one of the pluggable routing protocols. It is kept distinct from Ipv4StaticRouting because these routes may be dynamically cleared and rebuilt in the middle of the simulation, while manually entered routes into the Ipv4StaticRouting may need to be kept distinct.
This class deals with Ipv4 unicast routes only.
See also
Ipv4RoutingProtocol
GlobalRouteManager
Definition at line 79 of file ipv4-dgr-routing.h.
Member Typedef Documentation
ASExternalRoutes
typedef std::list<Ipv4DGRRoutingTableEntry *> ns3::Ipv4DGRRouting::ASExternalRoutes private
container of Ipv4RoutingTableEntry (routes to external AS)
Definition at line 305 of file ipv4-dgr-routing.h.
ASExternalRoutesCI
typedef std::list<Ipv4DGRRoutingTableEntry*>::const_iterator ns3::Ipv4DGRRouting::ASExternalRoutesCI private
const iterator of container of Ipv4RoutingTableEntry (routes to external AS)
Definition at line 307 of file ipv4-dgr-routing.h.
ASExternalRoutesI
typedef std::list<Ipv4DGRRoutingTableEntry*>::iterator ns3::Ipv4DGRRouting::ASExternalRoutesI private
iterator of container of Ipv4RoutingTableEntry (routes to external AS)
Definition at line 309 of file ipv4-dgr-routing.h.
HostRoutes
typedef std::list<Ipv4DGRRoutingTableEntry *> ns3::Ipv4DGRRouting::HostRoutes private
container of Ipv4RoutingTableEntry (routes to hosts)
Definition at line 291 of file ipv4-dgr-routing.h.
HostRoutesCI
typedef std::list<Ipv4DGRRoutingTableEntry*>::const_iterator ns3::Ipv4DGRRouting::HostRoutesCI private
const iterator of container of Ipv4RoutingTableEntry (routes to hosts)
Definition at line 293 of file ipv4-dgr-routing.h.
HostRoutesI
typedef std::list<Ipv4DGRRoutingTableEntry*>::iterator ns3::Ipv4DGRRouting::HostRoutesI private
iterator of container of Ipv4RoutingTableEntry (routes to hosts)
Definition at line 295 of file ipv4-dgr-routing.h.
NetworkRoutes
typedef std::list<Ipv4DGRRoutingTableEntry *> ns3::Ipv4DGRRouting::NetworkRoutes private
container of Ipv4RoutingTableEntry (routes to networks)
Definition at line 298 of file ipv4-dgr-routing.h.
NetworkRoutesCI
typedef std::list<Ipv4DGRRoutingTableEntry*>::const_iterator ns3::Ipv4DGRRouting::NetworkRoutesCI private
const iterator of container of Ipv4RoutingTableEntry (routes to networks)
Definition at line 300 of file ipv4-dgr-routing.h.
NetworkRoutesI
typedef std::list<Ipv4DGRRoutingTableEntry*>::iterator ns3::Ipv4DGRRouting::NetworkRoutesI private
iterator of container of Ipv4RoutingTableEntry (routes to networks)
Definition at line 302 of file ipv4-dgr-routing.h.
SocketList
typedef std::map<Ptr<Socket>, uint32_t> ns3::Ipv4DGRRouting::SocketList private
One socket per interface, each bound to that interface's address (reason: for Neighbor status sensing, we need to know on which interface the messages arrive)
Definition at line 322 of file ipv4-dgr-routing.h.
SocketListCI
typedef std::map<Ptr<Socket>,uint32_t>::const_iterator ns3::Ipv4DGRRouting::SocketListCI private
socket list type const iterator
Definition at line 326 of file ipv4-dgr-routing.h.
SocketListI
typedef std::map<Ptr<Socket>,uint32_t>::iterator ns3::Ipv4DGRRouting::SocketListI private
socket list type iterator
Definition at line 324 of file ipv4-dgr-routing.h.
Constructor & Destructor Documentation
Ipv4DGRRouting()
ns3::Ipv4DGRRouting::Ipv4DGRRouting ()
Construct an empty Ipv4GlobalRouting routing protocol,.
The Ipv4GlobalRouting class supports host and network unicast routes. This method initializes the lists containing these routes to empty.
See also
Ipv4GlobalRouting
Definition at line 81 of file ipv4-dgr-routing.cc.
References m_rand.
~Ipv4DGRRouting()
ns3::Ipv4DGRRouting::~Ipv4DGRRouting ()
Definition at line 93 of file ipv4-dgr-routing.cc.
Member Function Documentation
AddASExternalRouteTo()
void ns3::Ipv4DGRRouting::AddASExternalRouteTo (Ipv4Address network, Ipv4Mask networkMask, Ipv4Address nextHop, uint32_t interface)
Add an external route to the global routing table.
Parameters
network The Ipv4Address network for this route.
networkMask The Ipv4Mask to extract the network.
nextHop The next hop Ipv4Address
interface The network interface index used to send packets to the destination.
Definition at line 173 of file ipv4-dgr-routing.cc.
References ns3::Ipv4DGRRoutingTableEntry::CreateNetworkRouteTo(), and m_ASexternalRoutes.
AddHostRouteTo() [1/3]
void ns3::Ipv4DGRRouting::AddHostRouteTo (Ipv4Address dest, Ipv4Address nextHop, uint32_t interface)
Add a host route to the global routing table.
Parameters
dest The Ipv4Address destination for this route.
nextHop The Ipv4Address of the next hop in the route.
interface The network interface index used to send packets to the destination.
See also
Ipv4Address
Definition at line 99 of file ipv4-dgr-routing.cc.
References ns3::Ipv4DGRRoutingTableEntry::CreateHostRouteTo(), and m_hostRoutes.
AddHostRouteTo() [2/3]
void ns3::Ipv4DGRRouting::AddHostRouteTo (Ipv4Address dest, Ipv4Address nextHop, uint32_t interface, uint32_t nextInterface, uint32_t distance)
Add a host route to the global routing table with the distance between root and destination.
Parameters
dest The Ipv4Address destination for this route.
nextHop The next hop Ipv4Address
interface The network interface index used to send packets to the destination
distance The distance between root and destination
Author
Pu Yang
Parameters
dest The Ipv4Address destination for this route.
nextHop The next hop Ipv4Address
interface The network interface index used to send packets to the destination
distance The distance between root and destination
Definition at line 130 of file ipv4-dgr-routing.cc.
References ns3::Ipv4DGRRoutingTableEntry::CreateHostRouteTo(), and m_hostRoutes.
AddHostRouteTo() [3/3]
void ns3::Ipv4DGRRouting::AddHostRouteTo (Ipv4Address dest, uint32_t interface)
Add a host route to the global routing table.
Parameters
dest The Ipv4Address destination for this route.
interface The network interface index used to send packets to the destination.
See also
Ipv4Address
Definition at line 110 of file ipv4-dgr-routing.cc.
References ns3::Ipv4DGRRoutingTableEntry::CreateHostRouteTo(), and m_hostRoutes.
AddNetworkRouteTo() [1/2]
void ns3::Ipv4DGRRouting::AddNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, Ipv4Address nextHop, uint32_t interface)
Add a network route to the global routing table.
Parameters
network The Ipv4Address network for this route.
networkMask The Ipv4Mask to extract the network.
nextHop The next hop in the route to the destination network.
interface The network interface index used to send packets to the destination.
See also
Ipv4Address
Definition at line 145 of file ipv4-dgr-routing.cc.
References ns3::Ipv4DGRRoutingTableEntry::CreateNetworkRouteTo(), and m_networkRoutes.
AddNetworkRouteTo() [2/2]
void ns3::Ipv4DGRRouting::AddNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, uint32_t interface)
Add a network route to the global routing table.
Parameters
network The Ipv4Address network for this route.
networkMask The Ipv4Mask to extract the network.
interface The network interface index used to send packets to the destination.
See also
Ipv4Address
Definition at line 160 of file ipv4-dgr-routing.cc.
References ns3::Ipv4DGRRoutingTableEntry::CreateNetworkRouteTo(), and m_networkRoutes.
AssignStreams()
int64_t ns3::Ipv4DGRRouting::AssignStreams (int64_t stream)
Build the routing database by gathering Link State Advertisements from each node exporting a DGRRouter interface.
Assign a fixed random variable stream number to the random variables used by this model. Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 844 of file ipv4-dgr-routing.cc.
References m_rand.
DoDispose()
void ns3::Ipv4DGRRouting::DoDispose (void) override protected
Dispose this object.
Definition at line 852 of file ipv4-dgr-routing.cc.
References ns3::i, m_ASexternalRoutes, m_hostRoutes, and m_networkRoutes.
DoInitialize()
void ns3::Ipv4DGRRouting::DoInitialize () override
Start protocol operation.
Definition at line 879 of file ipv4-dgr-routing.cc.
References DGR_BROAD_CAST, DGR_PORT, ns3::i, m_initialized, m_interfaceExclusions, m_ipv4, m_multicastRecvSocket, m_nextUnsolicitedUpdate, m_outStream, m_unicastSocketList, m_unsolicitedUpdate, Receive(), and SendUnsolicitedUpdate().
DoSendNeighborStatusUpdate()
void ns3::Ipv4DGRRouting::DoSendNeighborStatusUpdate (bool periodic) private
Sending Neighbor Status Updates on all interfaces.
Parameters
periodic true for periodic update, else triggered.
Definition at line 1370 of file ipv4-dgr-routing.cc.
References ns3::DgrHeader::AddNse(), ns3::DgrHeader::ClearNses(), DGR_BROAD_CAST, DGR_PORT, ns3::DgrHeader::GetNseNumber(), ns3::DgrNse::GetSerializedSize(), ns3::DgrHeader::GetSerializedSize(), ns3::i, m_interfaceExclusions, m_ipv4, m_unicastSocketList, ns3::DgrHeader::RESPONSE, ns3::DgrHeader::SetCommand(), ns3::DgrNse::SetInterface(), and ns3::DgrNse::SetState().
Referenced by SendUnsolicitedUpdate().
GetNRoutes()
uint32_t ns3::Ipv4DGRRouting::GetNRoutes (void) const
Get the number of individual unicast routes that have been added to the routing table.
Warning
The default route counts as one of the routes.
Returns
the number of routes
Definition at line 727 of file ipv4-dgr-routing.cc.
References m_ASexternalRoutes, m_hostRoutes, and m_networkRoutes.
Referenced by PrintRoutingTable().
GetRoute()
Ipv4DGRRoutingTableEntry * ns3::Ipv4DGRRouting::GetRoute (uint32_t i) const
Get a route from the global unicast routing table.
Externally, the unicast global routing table appears simply as a table with n entries. The one subtlety of note is that if a default route has been set it will appear as the zeroth entry in the table. This means that if you add only a default route, the table will have one entry that can be accessed either by explicitly calling GetDefaultRoute () or by calling GetRoute (0).
Similarly, if the default route has been set, calling RemoveRoute (0) will remove the default route.
Parameters
i The index (into the routing table) of the route to retrieve. If the default route has been set, it will occupy index zero.
Returns
If route is set, a pointer to that Ipv4RoutingTableEntry is returned, otherwise a zero pointer is returned.
See also
Ipv4RoutingTableEntry
Ipv4GlobalRouting::RemoveRoute
Definition at line 738 of file ipv4-dgr-routing.cc.
References ns3::i, m_ASexternalRoutes, m_hostRoutes, and m_networkRoutes.
Referenced by PrintRoutingTable().
GetTypeId()
TypeId ns3::Ipv4DGRRouting::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 56 of file ipv4-dgr-routing.cc.
References m_randomEcmpRouting, m_respondToInterfaceEvents, and m_unsolicitedUpdate.
HandleResponses()
void ns3::Ipv4DGRRouting::HandleResponses (DgrHeader hdr, Ipv4Address senderAddress, uint32_t incomingInterface, uint8_t hopLimit) private
Handle DGR responses.
Parameters
hdr message header (including NSEs)
senderAddress sender address
incomingInterface incoming interface
hopLimit packet's hop limit
Definition at line 1432 of file ipv4-dgr-routing.cc.
References ns3::StatusUnit::GetCurrentState(), ns3::DgrHeader::GetNseList(), ns3::DgrHeader::GetSerializedSize(), ns3::NeighborStatusEntry::GetStatusUnit(), ns3::DgrNSDB::HandleNeighborStatusEntry(), ns3::DgrNSDB::Insert(), ns3::NeighborStatusEntry::Insert(), m_interfaceExclusions, m_nsdb, m_outStream, and ns3::StatusUnit::Update().
Referenced by Receive().
LookupDGRRoute()
Ptr< Ipv4Route > ns3::Ipv4DGRRouting::LookupDGRRoute (Ipv4Address dest, Ptr< Packet > p, Ptr< const NetDevice > idev = 0)
Todo:
handle multi-address case
Definition at line 253 of file ipv4-dgr-routing.cc.
References ns3::BudgetTag::GetBudget(), ns3::StatusUnit::GetCurrentState(), ns3::Ipv4DGRRoutingTableEntry::GetDest(), ns3::DistTag::GetDistance(), ns3::Ipv4DGRRoutingTableEntry::GetDistance(), ns3::Ipv4DGRRoutingTableEntry::GetGateway(), ns3::Ipv4DGRRoutingTableEntry::GetInterface(), ns3::DgrNSDB::GetNeighborStatusEntry(), ns3::NeighborStatusEntry::GetStatusUnit(), ns3::i, m_hostRoutes, m_ipv4, m_nsdb, m_rand, and ns3::DistTag::SetDistance().
Referenced by RouteInput(), and RouteOutput().
LookupUniRoute()
Ptr< Ipv4Route > ns3::Ipv4DGRRouting::LookupUniRoute (Ipv4Address dest, Ptr< NetDevice > oif = 0)
Lookup in the forwarding table for destination.
Parameters
dest destination address
oif output interface if any (put 0 otherwise)
Returns
Ipv4Route to route the packet to reach dest address
Get the shortest path in the routing table
Todo:
handle multi-address case
Definition at line 189 of file ipv4-dgr-routing.cc.
References ns3::Ipv4DGRRoutingTableEntry::GetDest(), ns3::Ipv4DGRRoutingTableEntry::GetGateway(), ns3::Ipv4DGRRoutingTableEntry::GetInterface(), ns3::i, m_hostRoutes, and m_ipv4.
Referenced by RouteInput(), and RouteOutput().
NotifyAddAddress()
void ns3::Ipv4DGRRouting::NotifyAddAddress (uint32_t interface, Ipv4InterfaceAddress address)
Definition at line 1255 of file ipv4-dgr-routing.cc.
References ns3::DGRRouteManager::BuildDGRRoutingDatabase(), ns3::DGRRouteManager::DeleteDGRRoutes(), ns3::DGRRouteManager::InitializeRoutes(), and m_respondToInterfaceEvents.
NotifyInterfaceDown()
void ns3::Ipv4DGRRouting::NotifyInterfaceDown (uint32_t interface)
Definition at line 1243 of file ipv4-dgr-routing.cc.
References ns3::DGRRouteManager::BuildDGRRoutingDatabase(), ns3::DGRRouteManager::DeleteDGRRoutes(), ns3::i, ns3::DGRRouteManager::InitializeRoutes(), and m_respondToInterfaceEvents.
NotifyInterfaceUp()
void ns3::Ipv4DGRRouting::NotifyInterfaceUp (uint32_t interface)
Definition at line 1231 of file ipv4-dgr-routing.cc.
References ns3::DGRRouteManager::BuildDGRRoutingDatabase(), ns3::DGRRouteManager::DeleteDGRRoutes(), ns3::i, ns3::DGRRouteManager::InitializeRoutes(), and m_respondToInterfaceEvents.
NotifyRemoveAddress()
void ns3::Ipv4DGRRouting::NotifyRemoveAddress (uint32_t interface, Ipv4InterfaceAddress address)
Definition at line 1267 of file ipv4-dgr-routing.cc.
References ns3::DGRRouteManager::BuildDGRRoutingDatabase(), ns3::DGRRouteManager::DeleteDGRRoutes(), ns3::DGRRouteManager::InitializeRoutes(), and m_respondToInterfaceEvents.
PrintRoutingTable()
void ns3::Ipv4DGRRouting::PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit = Time::S) const
Definition at line 970 of file ipv4-dgr-routing.cc.
References ns3::Ipv4DGRRoutingTableEntry::GetDest(), ns3::Ipv4DGRRoutingTableEntry::GetDistance(), ns3::Ipv4DGRRoutingTableEntry::GetGateway(), ns3::Ipv4DGRRoutingTableEntry::GetInterface(), ns3::Ipv4DGRRoutingTableEntry::GetNextInterface(), GetNRoutes(), GetRoute(), ns3::Ipv4DGRRoutingTableEntry::IsGateway(), ns3::Ipv4DGRRoutingTableEntry::IsHost(), and m_ipv4.
Receive()
void ns3::Ipv4DGRRouting::Receive (Ptr< Socket > socket) private
Receive an DGR message.
Parameters
socket the socket the packet was received from.
Definition at line 1287 of file ipv4-dgr-routing.cc.
References ns3::DgrHeader::GetCommand(), HandleResponses(), m_ipv4, m_multicastRecvSocket, and ns3::DgrHeader::RESPONSE.
Referenced by DoInitialize().
RemoveRoute()
void ns3::Ipv4DGRRouting::RemoveRoute (uint32_t i)
Remove a route from the global unicast routing table.
Externally, the unicast global routing table appears simply as a table with n entries. The one subtlety of note is that if a default route has been set it will appear as the zeroth entry in the table. This means that if the default route has been set, calling RemoveRoute (0) will remove the default route.
Parameters
i The index (into the routing table) of the route to remove. If the default route has been set, it will occupy index zero.
See also
Ipv4RoutingTableEntry
Ipv4GlobalRouting::GetRoute
Ipv4GlobalRouting::AddRoute
Definition at line 787 of file ipv4-dgr-routing.cc.
References ns3::i, m_ASexternalRoutes, m_hostRoutes, and m_networkRoutes.
RouteInput()
bool ns3::Ipv4DGRRouting::RouteInput (Ptr< const Packet > p, const Ipv4Header & header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb)
Definition at line 1160 of file ipv4-dgr-routing.cc.
References LookupDGRRoute(), LookupUniRoute(), and m_ipv4.
RouteOutput()
Ptr< Ipv4Route > ns3::Ipv4DGRRouting::RouteOutput (Ptr< Packet > p, const Ipv4Header & header, Ptr< NetDevice > oif, Socket::SocketErrno & sockerr)
Definition at line 1040 of file ipv4-dgr-routing.cc.
References LookupDGRRoute(), and LookupUniRoute().
SendTriggeredNeighborStatusUpdate()
void ns3::Ipv4DGRRouting::SendTriggeredNeighborStatusUpdate () private
Send Triggered Routing Updates on all interfaces.
SendUnsolicitedUpdate()
void ns3::Ipv4DGRRouting::SendUnsolicitedUpdate () private
Send Unsolicited neighbor status information Updates on all interfaces.
Definition at line 1356 of file ipv4-dgr-routing.cc.
References DoSendNeighborStatusUpdate(), m_nextTriggeredUpdate, m_nextUnsolicitedUpdate, m_unsolicitedUpdate, and SendUnsolicitedUpdate().
Referenced by DoInitialize(), and SendUnsolicitedUpdate().
SetIpv4()
void ns3::Ipv4DGRRouting::SetIpv4 (Ptr< Ipv4 > ipv4)
Definition at line 1279 of file ipv4-dgr-routing.cc.
References m_ipv4.
Member Data Documentation
m_ASexternalRoutes
ASExternalRoutes ns3::Ipv4DGRRouting::m_ASexternalRoutes private
External routes imported.
Definition at line 313 of file ipv4-dgr-routing.h.
Referenced by AddASExternalRouteTo(), DoDispose(), GetNRoutes(), GetRoute(), and RemoveRoute().
m_hostRoutes
HostRoutes ns3::Ipv4DGRRouting::m_hostRoutes private
Routes to hosts.
Definition at line 311 of file ipv4-dgr-routing.h.
Referenced by AddHostRouteTo(), AddHostRouteTo(), AddHostRouteTo(), DoDispose(), GetNRoutes(), GetRoute(), LookupDGRRoute(), LookupUniRoute(), and RemoveRoute().
m_initialized
bool ns3::Ipv4DGRRouting::m_initialized private
flag to allow socket's late-creation.
Definition at line 404 of file ipv4-dgr-routing.h.
Referenced by DoInitialize().
m_interfaceExclusions
std::set<uint32_t> ns3::Ipv4DGRRouting::m_interfaceExclusions private
Set of excluded interfaces.
Definition at line 343 of file ipv4-dgr-routing.h.
Referenced by DoInitialize(), DoSendNeighborStatusUpdate(), and HandleResponses().
m_ipv4
Ptr<Ipv4> ns3::Ipv4DGRRouting::m_ipv4 private
associated IPv4 instance
Definition at line 314 of file ipv4-dgr-routing.h.
Referenced by DoInitialize(), DoSendNeighborStatusUpdate(), LookupDGRRoute(), LookupUniRoute(), PrintRoutingTable(), Receive(), RouteInput(), and SetIpv4().
m_multicastRecvSocket
Ptr<Socket> ns3::Ipv4DGRRouting::m_multicastRecvSocket private
multicast receive socket
Definition at line 329 of file ipv4-dgr-routing.h.
Referenced by DoInitialize(), and Receive().
m_networkRoutes
NetworkRoutes ns3::Ipv4DGRRouting::m_networkRoutes private
Routes to networks.
Definition at line 312 of file ipv4-dgr-routing.h.
Referenced by AddNetworkRouteTo(), AddNetworkRouteTo(), DoDispose(), GetNRoutes(), GetRoute(), and RemoveRoute().
m_nextTriggeredUpdate
EventId ns3::Ipv4DGRRouting::m_nextTriggeredUpdate private
Next Triggered Update event.
Definition at line 332 of file ipv4-dgr-routing.h.
Referenced by SendUnsolicitedUpdate().
m_nextUnsolicitedUpdate
EventId ns3::Ipv4DGRRouting::m_nextUnsolicitedUpdate private
Next Unsolicited Update event.
Definition at line 331 of file ipv4-dgr-routing.h.
Referenced by DoInitialize(), and SendUnsolicitedUpdate().
m_nsdb
DgrNSDB ns3::Ipv4DGRRouting::m_nsdb private
the Neighbor State DataBase (NSDB) of the DGR Rout
Definition at line 316 of file ipv4-dgr-routing.h.
Referenced by HandleResponses(), and LookupDGRRoute().
m_outStream
Ptr<OutputStreamWrapper> ns3::Ipv4DGRRouting::m_outStream private
Initial value:
= Create<OutputStreamWrapper>
  ("queueStatusErr.txt", std::ios::out)
Definition at line 401 of file ipv4-dgr-routing.h.
Referenced by DoInitialize(), and HandleResponses().
m_rand
Ptr<UniformRandomVariable> ns3::Ipv4DGRRouting::m_rand private
A uniform random number generator for randomly routing packets among ECMP.
Definition at line 288 of file ipv4-dgr-routing.h.
Referenced by Ipv4DGRRouting(), AssignStreams(), and LookupDGRRoute().
m_randomEcmpRouting
bool ns3::Ipv4DGRRouting::m_randomEcmpRouting private
Set to true if packets are randomly routed among ECMP; set to false for using only one route consistently.
Definition at line 284 of file ipv4-dgr-routing.h.
Referenced by GetTypeId().
m_respondToInterfaceEvents
bool ns3::Ipv4DGRRouting::m_respondToInterfaceEvents private
Set to true if this interface should respond to interface events by globallly recomputing routes.
Definition at line 286 of file ipv4-dgr-routing.h.
Referenced by GetTypeId(), NotifyAddAddress(), NotifyInterfaceDown(), NotifyInterfaceUp(), and NotifyRemoveAddress().
m_unicastSocketList
SocketList ns3::Ipv4DGRRouting::m_unicastSocketList private
list of sockets for unicast messages (socket, interface index)
Definition at line 328 of file ipv4-dgr-routing.h.
Referenced by DoInitialize(), and DoSendNeighborStatusUpdate().
m_unsolicitedUpdate
Time ns3::Ipv4DGRRouting::m_unsolicitedUpdate private
Time between two Unsolicited Neighbor State Updates.
Definition at line 334 of file ipv4-dgr-routing.h.
Referenced by DoInitialize(), GetTypeId(), and SendUnsolicitedUpdate().
The documentation for this class was generated from the following files:
model/ipv4-dgr-routing.h
model/ipv4-dgr-routing.cc