DGRv2: ns3::DistTag Class Reference
ns3::DistTag Class Reference
This class implements a tag that carries the distance to destination node of a packet to the IP layer.
#include <dgr-tags.h>
Public Member Functions
DistTag ()
void Deserialize (TagBuffer i) override
uint32_t GetDistance (void) const
Get the tag's distance.
TypeId GetInstanceTypeId (void) const override
uint32_t GetSerializedSize (void) const override
void Print (std::ostream &os) const override
void Serialize (TagBuffer i) const override
void SetDistance (uint32_t distance)
Set the tag's distance.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the Type ID.
Private Attributes
uint32_t m_distance
Detailed Description
This class implements a tag that carries the distance to destination node of a packet to the IP layer.
Definition at line 63 of file dgr-tags.h.
Constructor & Destructor Documentation
DistTag()
ns3::DistTag::DistTag ()
Definition at line 93 of file dgr-tags.cc.
Member Function Documentation
Deserialize()
void ns3::DistTag::Deserialize (TagBuffer i) override
Definition at line 144 of file dgr-tags.cc.
References ns3::i, and m_distance.
GetDistance()
uint32_t ns3::DistTag::GetDistance (void) const
Get the tag's distance.
Returns
the distance
Definition at line 106 of file dgr-tags.cc.
References m_distance.
Referenced by ns3::Ipv4DGRRouting::LookupDGRRoute().
GetInstanceTypeId()
TypeId ns3::DistTag::GetInstanceTypeId (void) const override
Definition at line 123 of file dgr-tags.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::DistTag::GetSerializedSize (void) const override
Definition at line 129 of file dgr-tags.cc.
GetTypeId()
TypeId ns3::DistTag::GetTypeId (void) static
Get the Type ID.
Returns
the object TypeId
Definition at line 113 of file dgr-tags.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::DistTag::Print (std::ostream & os) const override
Definition at line 153 of file dgr-tags.cc.
References m_distance.
Serialize()
void ns3::DistTag::Serialize (TagBuffer i) const override
Definition at line 136 of file dgr-tags.cc.
References ns3::i, and m_distance.
SetDistance()
void ns3::DistTag::SetDistance (uint32_t distance)
Set the tag's distance.
Parameters
distance
Definition at line 99 of file dgr-tags.cc.
References m_distance.
Referenced by ns3::Ipv4DGRRouting::LookupDGRRoute().
Member Data Documentation
m_distance
uint32_t ns3::DistTag::m_distance private
Definition at line 101 of file dgr-tags.h.
Referenced by Deserialize(), GetDistance(), Print(), Serialize(), and SetDistance().
The documentation for this class was generated from the following files:
model/dgr-tags.h
model/dgr-tags.cc