DGRv2: ns3::DGRRoutingLSA Class Reference
ns3::DGRRoutingLSA Class Reference
a Link State Advertisement (LSA) for a router, used in global routing.
#include <dgr-router-interface.h>
Public Types
enum LSType {
Unknown = 0 , RouterLSA , NetworkLSA , SummaryLSA ,
SummaryLSA_ASBR , ASExternalLSAs
}
corresponds to LS type field of \RFC{2328} OSPF LSA header
enum SPFStatus { LSA_SPF_NOT_EXPLORED = 0 , LSA_SPF_CANDIDATE , LSA_SPF_IN_SPFTREE }
Enumeration of the possible values of the status flag in the Routing Link State Advertisements.
Public Member Functions
DGRRoutingLSA ()
Create a blank Global Routing Link State Advertisement.
DGRRoutingLSA (DGRRoutingLSA &lsa)
Copy constructor for a Global Routing Link State Advertisement.
DGRRoutingLSA (SPFStatus status, Ipv4Address linkStateId, Ipv4Address advertisingRtr)
Create an initialized Global Routing Link State Advertisement.
~DGRRoutingLSA ()
Destroy an existing Global Routing Link State Advertisement.
uint32_t AddAttachedRouter (Ipv4Address addr)
Add an attached router to the list in the NetworkLSA.
uint32_t AddLinkRecord (DGRRoutingLinkRecord *lr)
Add a given Global Routing Link Record to the LSA.
void ClearLinkRecords (void)
Release all of the Global Routing Link Records present in the Global Routing Link State Advertisement and make the list of link records empty.
void CopyLinkRecords (const DGRRoutingLSA &lsa)
Copy any Global Routing Link Records in a given Global Routing Link State Advertisement to the current LSA.
Ipv4Address GetAdvertisingRouter (void) const
Get the Advertising Router as defined by the OSPF spec.
Ipv4Address GetAttachedRouter (uint32_t n) const
Return an Ipv4Address corresponding to the specified attached router.
DGRRoutingLinkRecord * GetLinkRecord (uint32_t n) const
Return a pointer to the specified Global Routing Link Record.
Ipv4Address GetLinkStateId (void) const
Get the Link State ID as defined by the OSPF spec.
LSType GetLSType (void) const
Return the LSType field of the LSA.
uint32_t GetNAttachedRouters (void) const
Return the number of attached routers listed in the NetworkLSA.
Ipv4Mask GetNetworkLSANetworkMask (void) const
For a Network LSA, get the Network Mask field that precedes the list of attached routers.
uint32_t GetNLinkRecords (void) const
Return the number of Global Routing Link Records in the LSA.
Ptr< Node > GetNode (void) const
Get the Node pointer of the node that originated this LSA.
SPFStatus GetStatus (void) const
Get the SPF status of the advertisement.
bool IsEmpty (void) const
Check to see if the list of Global Routing Link Records present in the Global Routing Link State Advertisement is empty.
DGRRoutingLSA & operator= (const DGRRoutingLSA &lsa)
Assignment operator for a Global Routing Link State Advertisement.
void Print (std::ostream &os) const
Print the contents of the Global Routing Link State Advertisement and any Global Routing Link Records present in the list.
void SetAdvertisingRouter (Ipv4Address rtr)
Set the Advertising Router as defined by the OSPF spec.
void SetLinkStateId (Ipv4Address addr)
Set the Link State ID is defined by the OSPF spec.
void SetLSType (LSType typ)
Set the LS type field of the LSA.
void SetNetworkLSANetworkMask (Ipv4Mask mask)
For a Network LSA, set the Network Mask field that precedes the list of attached routers.
void SetNode (Ptr< Node > node)
Set the Node pointer of the node that originated this LSA.
void SetStatus (SPFStatus status)
Set the SPF status of the advertisement.
Private Types
typedef std::list< Ipv4Address > ListOfAttachedRouters_t
A convenience typedef to avoid too much writers cramp.
typedef std::list< DGRRoutingLinkRecord * > ListOfLinkRecords_t
A convenience typedef to avoid too much writers cramp.
Private Attributes
Ipv4Address m_advertisingRtr
The Advertising Router is defined by the OSPF spec.
ListOfAttachedRouters_t m_attachedRouters
Each Network LSA contains a list of attached routers.
ListOfLinkRecords_t m_linkRecords
Each Link State Advertisement contains a number of Link Records that describe the kinds of links that are attached to a given node.
Ipv4Address m_linkStateId
The Link State ID is defined by the OSPF spec.
LSType m_lsType
The type of the LSA.
Ipv4Mask m_networkLSANetworkMask
Each Network LSA contains the network mask of the attached network.
uint32_t m_node_id
node ID
SPFStatus m_status
This is a tristate flag used internally in the SPF computation to mark if an SPFVertex (a data structure representing a vertex in the SPF tree – a router) is new, is a candidate for a shortest path, or is in its proper position in the tree.
Detailed Description
a Link State Advertisement (LSA) for a router, used in global routing.
Roughly equivalent to a global incarnation of the OSPF link state header combined with a list of Link Records. Since it's global, there's no need for age or sequence number. See \RFC{2328}, Appendix A.
Definition at line 253 of file dgr-router-interface.h.
Member Typedef Documentation
ListOfAttachedRouters_t
typedef std::list<Ipv4Address> ns3::DGRRoutingLSA::ListOfAttachedRouters_t private
A convenience typedef to avoid too much writers cramp.
Definition at line 549 of file dgr-router-interface.h.
ListOfLinkRecords_t
typedef std::list<DGRRoutingLinkRecord*> ns3::DGRRoutingLSA::ListOfLinkRecords_t private
A convenience typedef to avoid too much writers cramp.
Definition at line 527 of file dgr-router-interface.h.
Member Enumeration Documentation
LSType
enum ns3::DGRRoutingLSA::LSType
corresponds to LS type field of \RFC{2328} OSPF LSA header
Enumerator
Unknown
Uninitialized Type.
RouterLSA
NetworkLSA
SummaryLSA
SummaryLSA_ASBR
ASExternalLSAs
Definition at line 260 of file dgr-router-interface.h.
SPFStatus
enum ns3::DGRRoutingLSA::SPFStatus
Enumeration of the possible values of the status flag in the Routing Link State Advertisements.
Enumerator
LSA_SPF_NOT_EXPLORED
New vertex not yet considered.
LSA_SPF_CANDIDATE
Vertex is in the SPF candidate queue.
LSA_SPF_IN_SPFTREE
Vertex is in the SPF tree.
Definition at line 273 of file dgr-router-interface.h.
Constructor & Destructor Documentation
DGRRoutingLSA() [1/3]
ns3::DGRRoutingLSA::DGRRoutingLSA ()
Create a blank Global Routing Link State Advertisement.
On completion Ipv4Address variables initialized to 0.0.0.0 and the list of Link State Records is empty.
Definition at line 137 of file dgr-router-interface.cc.
DGRRoutingLSA() [2/3]
ns3::DGRRoutingLSA::DGRRoutingLSA (DGRRoutingLSA::SPFStatus status, Ipv4Address linkStateId, Ipv4Address advertisingRtr)
Create an initialized Global Routing Link State Advertisement.
On completion the list of Link State Records is empty.
Parameters
status The status to of the new LSA.
linkStateId The Ipv4Address for the link state ID field.
advertisingRtr The Ipv4Address for the advertising router field.
Definition at line 151 of file dgr-router-interface.cc.
DGRRoutingLSA() [3/3]
ns3::DGRRoutingLSA::DGRRoutingLSA (DGRRoutingLSA & lsa)
Copy constructor for a Global Routing Link State Advertisement.
Takes a piece of memory and constructs a semantically identical copy of the given LSA.
Parameters
lsa The existing LSA to be used as the source.
Definition at line 168 of file dgr-router-interface.cc.
References CopyLinkRecords(), and IsEmpty().
~DGRRoutingLSA()
ns3::DGRRoutingLSA::~DGRRoutingLSA ()
Destroy an existing Global Routing Link State Advertisement.
Any Global Routing Link Records present in the list are freed.
Definition at line 220 of file dgr-router-interface.cc.
References ClearLinkRecords().
Member Function Documentation
AddAttachedRouter()
uint32_t ns3::DGRRoutingLSA::AddAttachedRouter (Ipv4Address addr)
Add an attached router to the list in the NetworkLSA.
Parameters
addr The Ipv4Address of the interface on the network link
Returns
The number of addresses in the list.
Definition at line 350 of file dgr-router-interface.cc.
References m_attachedRouters.
Referenced by ns3::DGRRouter::BuildNetworkLSAs().
AddLinkRecord()
uint32_t ns3::DGRRoutingLSA::AddLinkRecord (DGRRoutingLinkRecord * lr)
Add a given Global Routing Link Record to the LSA.
Parameters
lr The Global Routing Link Record to be added.
Returns
The number of link records in the list.
Definition at line 247 of file dgr-router-interface.cc.
References m_linkRecords.
Referenced by ns3::DGRRouter::ProcessBridgedBroadcastLink(), ns3::DGRRouter::ProcessPointToPointLink(), and ns3::DGRRouter::ProcessSingleBroadcastLink().
ClearLinkRecords()
void ns3::DGRRoutingLSA::ClearLinkRecords (void)
Release all of the Global Routing Link Records present in the Global Routing Link State Advertisement and make the list of link records empty.
Definition at line 227 of file dgr-router-interface.cc.
References ns3::i, and m_linkRecords.
Referenced by ~DGRRoutingLSA(), and operator=().
CopyLinkRecords()
void ns3::DGRRoutingLSA::CopyLinkRecords (const DGRRoutingLSA & lsa)
Copy any Global Routing Link Records in a given Global Routing Link State Advertisement to the current LSA.
Existing Link Records are not deleted – this is a concatenation of Link Records.
See also
ClearLinkRecords ()
Parameters
lsa The LSA to copy the Link Records from.
Definition at line 198 of file dgr-router-interface.cc.
References ns3::DGRRoutingLinkRecord::GetLinkData(), ns3::DGRRoutingLinkRecord::GetLinkId(), ns3::DGRRoutingLinkRecord::GetLinkType(), ns3::DGRRoutingLinkRecord::GetMetric(), ns3::i, m_attachedRouters, m_linkRecords, ns3::DGRRoutingLinkRecord::SetLinkData(), ns3::DGRRoutingLinkRecord::SetLinkId(), ns3::DGRRoutingLinkRecord::SetLinkType(), and ns3::DGRRoutingLinkRecord::SetMetric().
Referenced by DGRRoutingLSA(), and operator=().
GetAdvertisingRouter()
Ipv4Address ns3::DGRRoutingLSA::GetAdvertisingRouter (void) const
Get the Advertising Router as defined by the OSPF spec.
We always set it to the router ID of the router making the advertisement.
See also
RoutingEnvironment::AllocateRouterId ()
GlobalRouting::GetRouterId ()
Returns
The Ipv4Address stored as the advertising router.
Definition at line 315 of file dgr-router-interface.cc.
References m_advertisingRtr.
Referenced by ns3::DGRRouteManagerImpl::ProcessASExternals(), and ns3::DGRRouteManagerImpl::SPFAddASExternal().
GetAttachedRouter()
Ipv4Address ns3::DGRRoutingLSA::GetAttachedRouter (uint32_t n) const
Return an Ipv4Address corresponding to the specified attached router.
Parameters
n The attached router number desired (number in the list).
Returns
The Ipv4Address of the requested router
Definition at line 365 of file dgr-router-interface.cc.
References ns3::i, and m_attachedRouters.
Referenced by ns3::DGRRouteManagerImpl::SPFNext().
GetLinkRecord()
DGRRoutingLinkRecord * ns3::DGRRoutingLSA::GetLinkRecord (uint32_t n) const
Return a pointer to the specified Global Routing Link Record.
Parameters
n The LSA number desired.
Returns
The number of link records in the list.
Definition at line 262 of file dgr-router-interface.cc.
References ns3::i, and m_linkRecords.
Referenced by ns3::DGRRouteManagerImpl::CheckForStubNode(), ns3::DGRRouteManagerLSDB::GetLSAByLinkData(), ns3::DGRRouteManagerImpl::InitializeRoutes(), ns3::DGRRouteManagerImpl::SPFGetNextLink(), ns3::DGRRouteManagerImpl::SPFIntraAddRouter(), ns3::DGRRouteManagerImpl::SPFNext(), and ns3::DGRRouteManagerImpl::SPFProcessStubs().
GetLinkStateId()
Ipv4Address ns3::DGRRoutingLSA::GetLinkStateId (void) const
Get the Link State ID as defined by the OSPF spec.
We always set it to the router ID of the router making the advertisement.
See also
RoutingEnvironment::AllocateRouterId ()
GlobalRouting::GetRouterId ()
Returns
The Ipv4Address stored as the link state ID.
Definition at line 301 of file dgr-router-interface.cc.
References m_linkStateId.
Referenced by ns3::DGRRouteManagerImpl::BuildDGRRoutingDatabase(), ns3::DGRRouteManagerImpl::CheckForStubNode(), ns3::DGRRouteManagerImpl::InitializeRoutes(), ns3::DGRRouteManagerImpl::ProcessASExternals(), ns3::DGRRouteManagerImpl::SPFAddASExternal(), ns3::DGRRouteManagerImpl::SPFCalculate(), ns3::DGRRouteManagerImpl::SPFIntraAddRouter(), ns3::DGRRouteManagerImpl::SPFIntraAddTransit(), ns3::DGRRouteManagerImpl::SPFNext(), ns3::DGRRouteManagerImpl::SPFNexthopCalculation(), and ns3::DGRRouteManagerImpl::SPFProcessStubs().
GetLSType()
DGRRoutingLSA::LSType ns3::DGRRoutingLSA::GetLSType (void) const
Return the LSType field of the LSA.
Returns
The LS Type.
Definition at line 287 of file dgr-router-interface.cc.
References m_lsType.
Referenced by ns3::DGRVertex::DGRVertex(), ns3::DGRRouteManagerLSDB::Insert(), ns3::DGRRouteManagerImpl::SPFNext(), and ns3::DGRRouteManagerImpl::SPFNexthopCalculation().
GetNAttachedRouters()
uint32_t ns3::DGRRoutingLSA::GetNAttachedRouters (void) const
Return the number of attached routers listed in the NetworkLSA.
Returns
The number of attached routers.
Definition at line 358 of file dgr-router-interface.cc.
References m_attachedRouters.
Referenced by ns3::DGRRouteManagerImpl::InitializeRoutes(), and ns3::DGRRouteManagerImpl::SPFNext().
GetNetworkLSANetworkMask()
Ipv4Mask ns3::DGRRoutingLSA::GetNetworkLSANetworkMask (void) const
For a Network LSA, get the Network Mask field that precedes the list of attached routers.
Returns
the NetworkLSANetworkMask
Definition at line 336 of file dgr-router-interface.cc.
References m_networkLSANetworkMask.
Referenced by ns3::DGRRouteManagerImpl::SPFAddASExternal(), ns3::DGRRouteManagerImpl::SPFIntraAddTransit(), and ns3::DGRRouteManagerImpl::SPFNexthopCalculation().
GetNLinkRecords()
uint32_t ns3::DGRRoutingLSA::GetNLinkRecords (void) const
Return the number of Global Routing Link Records in the LSA.
Returns
The number of link records in the list.
Definition at line 255 of file dgr-router-interface.cc.
References m_linkRecords.
Referenced by ns3::DGRRouteManagerImpl::CheckForStubNode(), ns3::DGRRouteManagerLSDB::GetLSAByLinkData(), ns3::DGRRouteManagerImpl::InitializeRoutes(), ns3::DGRRouteManagerImpl::SPFIntraAddRouter(), ns3::DGRRouteManagerImpl::SPFNext(), and ns3::DGRRouteManagerImpl::SPFProcessStubs().
GetNode()
Ptr< Node > ns3::DGRRoutingLSA::GetNode (void) const
Get the Node pointer of the node that originated this LSA.
Returns
Node pointer
Definition at line 390 of file dgr-router-interface.cc.
References m_node_id.
Referenced by ns3::DGRRouteManagerImpl::CheckForStubNode().
GetStatus()
DGRRoutingLSA::SPFStatus ns3::DGRRoutingLSA::GetStatus (void) const
Get the SPF status of the advertisement.
See also
SPFStatus
Returns
The SPFStatus of the LSA.
Definition at line 343 of file dgr-router-interface.cc.
References m_status.
Referenced by ns3::DGRRouteManagerImpl::SPFNext().
IsEmpty()
bool ns3::DGRRoutingLSA::IsEmpty (void) const
Check to see if the list of Global Routing Link Records present in the Global Routing Link State Advertisement is empty.
Returns
True if the list is empty, false otherwise.
Definition at line 280 of file dgr-router-interface.cc.
References m_linkRecords.
Referenced by DGRRoutingLSA(), and ns3::DGRRouter::GetLSA().
operator=()
DGRRoutingLSA & ns3::DGRRoutingLSA::operator= (const DGRRoutingLSA & lsa)
Assignment operator for a Global Routing Link State Advertisement.
Takes an existing Global Routing Link State Advertisement and overwrites it to make a semantically identical copy of a given prototype LSA.
If there are any Global Routing Link Records present in the existing LSA, they are freed before the assignment happens.
Parameters
lsa The existing LSA to be used as the source.
Returns
Reference to the overwritten LSA.
Definition at line 182 of file dgr-router-interface.cc.
References ClearLinkRecords(), CopyLinkRecords(), m_advertisingRtr, m_linkStateId, m_lsType, m_networkLSANetworkMask, m_node_id, and m_status.
Print()
void ns3::DGRRoutingLSA::Print (std::ostream & os) const
Print the contents of the Global Routing Link State Advertisement and any Global Routing Link Records present in the list.
Quite verbose.
Parameters
os the output stream
Definition at line 404 of file dgr-router-interface.cc.
References ASExternalLSAs, ns3::i, m_advertisingRtr, m_attachedRouters, ns3::DGRRoutingLinkRecord::m_linkData, ns3::DGRRoutingLinkRecord::m_linkId, m_linkRecords, m_linkStateId, ns3::DGRRoutingLinkRecord::m_linkType, m_lsType, ns3::DGRRoutingLinkRecord::m_metric, m_networkLSANetworkMask, NetworkLSA, ns3::DGRRoutingLinkRecord::PointToPoint, RouterLSA, ns3::DGRRoutingLinkRecord::StubNetwork, and ns3::DGRRoutingLinkRecord::TransitNetwork.
Referenced by ns3::operator<<().
SetAdvertisingRouter()
void ns3::DGRRoutingLSA::SetAdvertisingRouter (Ipv4Address rtr)
Set the Advertising Router as defined by the OSPF spec.
We always set it to the router ID of the router making the advertisement.
Parameters
rtr ID of the router making advertisement
See also
RoutingEnvironment::AllocateRouterId ()
GlobalRouting::GetRouterId ()
Definition at line 322 of file dgr-router-interface.cc.
References m_advertisingRtr.
Referenced by ns3::DGRRouter::BuildNetworkLSAs(), and ns3::DGRRouter::DiscoverLSAs().
SetLinkStateId()
void ns3::DGRRoutingLSA::SetLinkStateId (Ipv4Address addr)
Set the Link State ID is defined by the OSPF spec.
We always set it to the router ID of the router making the advertisement.
Parameters
addr IPv4 address which will act as ID
See also
RoutingEnvironment::AllocateRouterId ()
GlobalRouting::GetRouterId ()
Definition at line 308 of file dgr-router-interface.cc.
References m_linkStateId.
Referenced by ns3::DGRRouter::BuildNetworkLSAs(), and ns3::DGRRouter::DiscoverLSAs().
SetLSType()
void ns3::DGRRoutingLSA::SetLSType (DGRRoutingLSA::LSType typ)
Set the LS type field of the LSA.
Parameters
typ the LS Type.
Definition at line 294 of file dgr-router-interface.cc.
References m_lsType.
Referenced by ns3::DGRRouter::BuildNetworkLSAs(), and ns3::DGRRouter::DiscoverLSAs().
SetNetworkLSANetworkMask()
void ns3::DGRRoutingLSA::SetNetworkLSANetworkMask (Ipv4Mask mask)
For a Network LSA, set the Network Mask field that precedes the list of attached routers.
Parameters
mask the Network Mask field.
Definition at line 329 of file dgr-router-interface.cc.
References m_networkLSANetworkMask.
Referenced by ns3::DGRRouter::BuildNetworkLSAs(), and ns3::DGRRouter::DiscoverLSAs().
SetNode()
void ns3::DGRRoutingLSA::SetNode (Ptr< Node > node)
Set the Node pointer of the node that originated this LSA.
Parameters
node Node pointer
Definition at line 397 of file dgr-router-interface.cc.
References m_node_id.
Referenced by ns3::DGRRouter::BuildNetworkLSAs(), and ns3::DGRRouter::DiscoverLSAs().
SetStatus()
void ns3::DGRRoutingLSA::SetStatus (DGRRoutingLSA::SPFStatus status)
Set the SPF status of the advertisement.
Parameters
status SPF status to set
See also
SPFStatus
Definition at line 383 of file dgr-router-interface.cc.
References m_status.
Referenced by ns3::DGRRouter::BuildNetworkLSAs(), ns3::DGRRouter::DiscoverLSAs(), ns3::DGRRouteManagerLSDB::Initialize(), ns3::DGRRouteManagerImpl::SPFCalculate(), and ns3::DGRRouteManagerImpl::SPFNext().
Member Data Documentation
m_advertisingRtr
Ipv4Address ns3::DGRRoutingLSA::m_advertisingRtr private
The Advertising Router is defined by the OSPF spec.
We always set it to the router ID of the router making the advertisement.
See also
RoutingEnvironment::AllocateRouterId ()
GlobalRouting::GetRouterId ()
Definition at line 522 of file dgr-router-interface.h.
Referenced by GetAdvertisingRouter(), operator=(), Print(), and SetAdvertisingRouter().
m_attachedRouters
ListOfAttachedRouters_t ns3::DGRRoutingLSA::m_attachedRouters private
Each Network LSA contains a list of attached routers.
m_attachedRouters is an STL list container to hold the addresses that have been discovered and prepared for the advertisement.
See also
GlobalRouting::DiscoverLSAs ()
Definition at line 559 of file dgr-router-interface.h.
Referenced by AddAttachedRouter(), CopyLinkRecords(), GetAttachedRouter(), GetNAttachedRouters(), and Print().
m_linkRecords
ListOfLinkRecords_t ns3::DGRRoutingLSA::m_linkRecords private
Each Link State Advertisement contains a number of Link Records that describe the kinds of links that are attached to a given node.
We consider PointToPoint and StubNetwork links.
m_linkRecords is an STL list container to hold the Link Records that have been discovered and prepared for the advertisement.
See also
GlobalRouting::DiscoverLSAs ()
Definition at line 539 of file dgr-router-interface.h.
Referenced by AddLinkRecord(), ClearLinkRecords(), CopyLinkRecords(), GetLinkRecord(), GetNLinkRecords(), IsEmpty(), and Print().
m_linkStateId
Ipv4Address ns3::DGRRoutingLSA::m_linkStateId private
The Link State ID is defined by the OSPF spec.
We always set it to the router ID of the router making the advertisement.
See also
RoutingEnvironment::AllocateRouterId ()
GlobalRouting::GetRouterId ()
Definition at line 513 of file dgr-router-interface.h.
Referenced by GetLinkStateId(), operator=(), Print(), and SetLinkStateId().
m_lsType
LSType ns3::DGRRoutingLSA::m_lsType private
The type of the LSA.
Each LSA type has a separate advertisement format.
Definition at line 505 of file dgr-router-interface.h.
Referenced by GetLSType(), operator=(), Print(), and SetLSType().
m_networkLSANetworkMask
Ipv4Mask ns3::DGRRoutingLSA::m_networkLSANetworkMask private
Each Network LSA contains the network mask of the attached network.
Definition at line 544 of file dgr-router-interface.h.
Referenced by GetNetworkLSANetworkMask(), operator=(), Print(), and SetNetworkLSANetworkMask().
m_node_id
uint32_t ns3::DGRRoutingLSA::m_node_id private
node ID
Definition at line 568 of file dgr-router-interface.h.
Referenced by GetNode(), operator=(), and SetNode().
m_status
SPFStatus ns3::DGRRoutingLSA::m_status private
This is a tristate flag used internally in the SPF computation to mark if an SPFVertex (a data structure representing a vertex in the SPF tree – a router) is new, is a candidate for a shortest path, or is in its proper position in the tree.
Definition at line 567 of file dgr-router-interface.h.
Referenced by GetStatus(), operator=(), and SetStatus().
The documentation for this class was generated from the following files:
model/dgr-router-interface.h
model/dgr-router-interface.cc