# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('dsr-routing-example', ['dsr-routing'])
    obj.source = 'dsr-routing-example.cc'

