DGRv2: ns3::DGRPacketSink Class Reference
ns3::DGRPacketSink Class Reference
PacketSink
Receive and consume traffic generated to an IP address and port.
#include <dgr-sink.h>
Classes
struct AddressHash
Hashing for the Address class.
Public Types
typedef void(* SeqTsSizeCallback) (Ptr< const Packet > p, const Address &from, const Address &to, const SeqTsSizeHeader &header)
TracedCallback signature for a reception with addresses and SeqTsSizeHeader.
Public Member Functions
DGRPacketSink ()
virtual ~DGRPacketSink ()
std::list< Ptr< Socket > > GetAcceptedSockets (void) const
Time GetDelay (const Ptr< Packet > &p) const
Ptr< Socket > GetListeningSocket (void) const
uint64_t GetTotalRx () const
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Private Member Functions
void HandleAccept (Ptr< Socket > socket, const Address &from)
Handle an incoming connection.
void HandlePeerClose (Ptr< Socket > socket)
Handle an connection close.
void HandlePeerError (Ptr< Socket > socket)
Handle an connection error.
void HandleRead (Ptr< Socket > socket)
Handle a packet received by the application.
void PacketReceived (const Ptr< Packet > &p, const Address &from, const Address &localAddress)
Packet received: assemble byte stream to extract SeqTsSizeHeader.
virtual void StartApplication (void)
virtual void StopApplication (void)
Private Attributes
std::unordered_map< Address, Ptr< Packet >, AddressHash > m_buffer
Buffer for received packets.
Ptr< OutputStreamWrapper > m_delayStream
bool m_enableSeqTsSizeHeader {false}
Enable or disable the export of SeqTsSize header.
Address m_local
Local address to bind to.
TracedCallback< Ptr< const Packet >, const Address & > m_rxTrace
Traced Callback: received packets, source address.
TracedCallback< Ptr< const Packet >, const Address &, const Address & > m_rxTraceWithAddresses
Callback for tracing the packet Rx events, includes source and destination addresses.
TracedCallback< Ptr< const Packet >, const Address &, const Address &, const SeqTsSizeHeader & > m_rxTraceWithSeqTsSize
Callbacks for tracing the packet Rx events, includes source, destination addresses, and headers.
Ptr< Socket > m_socket
Listening socket.
std::list< Ptr< Socket > > m_socketList
the accepted sockets
TypeId m_tid
Protocol TypeId.
uint64_t m_totalRx
Total bytes received.
Detailed Description
Receive and consume traffic generated to an IP address and port.
This application was written to complement OnOffApplication, but it is more general so a PacketSink name was selected. Functionally it is important to use in multicast situations, so that reception of the layer-2 multicast frames of interest are enabled, but it is also useful for unicast as an example of how you can write something simple to receive packets at the application layer. Also, if an IP stack generates ICMP Port Unreachable errors, receiving applications will be needed.
The constructor specifies the Address (IP address and port) and the transport protocol to use. A virtual Receive () method is installed as a callback on the receiving socket. By default, when logging is enabled, it prints out the size of packets and their address. A tracing source to Receive() is also available.
Definition at line 54 of file dgr-sink.h.
Member Typedef Documentation
SeqTsSizeCallback
typedef void(* ns3::DGRPacketSink::SeqTsSizeCallback) (Ptr< const Packet > p, const Address &from, const Address &to, const SeqTsSizeHeader &header)
TracedCallback signature for a reception with addresses and SeqTsSizeHeader.
Parameters
p The packet received (without the SeqTsSize header)
from From address
to Local address
header The SeqTsSize header
Definition at line 95 of file dgr-sink.h.
Constructor & Destructor Documentation
DGRPacketSink()
ns3::DGRPacketSink::DGRPacketSink ()
Definition at line 63 of file dgr-sink.cc.
References m_socket, and m_totalRx.
~DGRPacketSink()
ns3::DGRPacketSink::~DGRPacketSink () virtual
Definition at line 70 of file dgr-sink.cc.
Member Function Documentation
DoDispose()
void ns3::DGRPacketSink::DoDispose (void) protected virtual
Definition at line 105 of file dgr-sink.cc.
References m_socket, and m_socketList.
GetAcceptedSockets()
std::list< Ptr< Socket > > ns3::DGRPacketSink::GetAcceptedSockets (void) const
Returns
list of pointers to accepted sockets
Definition at line 89 of file dgr-sink.cc.
References m_socketList.
GetDelay()
Time ns3::DGRPacketSink::GetDelay (const Ptr< Packet > & p) const
Author
Pu Yang
Returns
the delay information
Definition at line 95 of file dgr-sink.cc.
Referenced by HandleRead().
GetListeningSocket()
Ptr< Socket > ns3::DGRPacketSink::GetListeningSocket (void) const
Returns
pointer to listening socket
Definition at line 82 of file dgr-sink.cc.
References m_socket.
GetTotalRx()
uint64_t ns3::DGRPacketSink::GetTotalRx () const
Returns
the total bytes received in this sink app
Definition at line 75 of file dgr-sink.cc.
References m_totalRx.
GetTypeId()
TypeId ns3::DGRPacketSink::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 27 of file dgr-sink.cc.
References m_enableSeqTsSizeHeader, m_local, m_rxTrace, m_rxTraceWithAddresses, m_rxTraceWithSeqTsSize, and m_tid.
HandleAccept()
void ns3::DGRPacketSink::HandleAccept (Ptr< Socket > socket, const Address & from) private
Handle an incoming connection.
Parameters
socket the incoming connection socket
from the address the connection is from
Definition at line 293 of file dgr-sink.cc.
References HandleRead(), and m_socketList.
Referenced by StartApplication().
HandlePeerClose()
void ns3::DGRPacketSink::HandlePeerClose (Ptr< Socket > socket) private
Handle an connection close.
Parameters
socket the connected socket
Definition at line 283 of file dgr-sink.cc.
Referenced by StartApplication().
HandlePeerError()
void ns3::DGRPacketSink::HandlePeerError (Ptr< Socket > socket) private
Handle an connection error.
Parameters
socket the connected socket
Definition at line 288 of file dgr-sink.cc.
Referenced by StartApplication().
HandleRead()
void ns3::DGRPacketSink::HandleRead (Ptr< Socket > socket) private
Handle a packet received by the application.
Parameters
socket the receiving socket
Definition at line 170 of file dgr-sink.cc.
References GetDelay(), ns3::FlagTag::GetFlag(), ns3::i, m_delayStream, m_enableSeqTsSizeHeader, m_rxTrace, m_rxTraceWithAddresses, m_totalRx, and PacketReceived().
Referenced by HandleAccept(), and StartApplication().
PacketReceived()
void ns3::DGRPacketSink::PacketReceived (const Ptr< Packet > & p, const Address & from, const Address & localAddress) private
Packet received: assemble byte stream to extract SeqTsSizeHeader.
Parameters
p received packet
from from address
localAddress local address
The method assembles a received byte stream and extracts SeqTsSizeHeader instances from the stream to export in a trace source.
Definition at line 244 of file dgr-sink.cc.
References m_buffer, and m_rxTraceWithSeqTsSize.
Referenced by HandleRead().
StartApplication()
void ns3::DGRPacketSink::StartApplication (void) private virtual
Definition at line 116 of file dgr-sink.cc.
References HandleAccept(), HandlePeerClose(), HandlePeerError(), HandleRead(), m_local, m_socket, and m_tid.
StopApplication()
void ns3::DGRPacketSink::StopApplication (void) private virtual
Definition at line 153 of file dgr-sink.cc.
References m_socket, and m_socketList.
Member Data Documentation
m_buffer
std::unordered_map<Address, Ptr<Packet>, AddressHash> ns3::DGRPacketSink::m_buffer private
Buffer for received packets.
Definition at line 161 of file dgr-sink.h.
Referenced by PacketReceived().
m_delayStream
Ptr<OutputStreamWrapper> ns3::DGRPacketSink::m_delayStream private
Initial value:
= Create<OutputStreamWrapper>
  ("dgr-packet.delay", std::ios::out)
Definition at line 172 of file dgr-sink.h.
Referenced by HandleRead().
m_enableSeqTsSizeHeader
bool ns3::DGRPacketSink::m_enableSeqTsSizeHeader {false} private
Enable or disable the export of SeqTsSize header.
Definition at line 175 of file dgr-sink.h.
Referenced by GetTypeId(), and HandleRead().
m_local
Address ns3::DGRPacketSink::m_local private
Local address to bind to.
Definition at line 168 of file dgr-sink.h.
Referenced by GetTypeId(), and StartApplication().
m_rxTrace
TracedCallback<Ptr<const Packet>, const Address &> ns3::DGRPacketSink::m_rxTrace private
Traced Callback: received packets, source address.
Definition at line 178 of file dgr-sink.h.
Referenced by GetTypeId(), and HandleRead().
m_rxTraceWithAddresses
TracedCallback<Ptr<const Packet>, const Address &, const Address &> ns3::DGRPacketSink::m_rxTraceWithAddresses private
Callback for tracing the packet Rx events, includes source and destination addresses.
Definition at line 180 of file dgr-sink.h.
Referenced by GetTypeId(), and HandleRead().
m_rxTraceWithSeqTsSize
TracedCallback<Ptr<const Packet>, const Address &, const Address &, const SeqTsSizeHeader&> ns3::DGRPacketSink::m_rxTraceWithSeqTsSize private
Callbacks for tracing the packet Rx events, includes source, destination addresses, and headers.
Definition at line 182 of file dgr-sink.h.
Referenced by GetTypeId(), and PacketReceived().
m_socket
Ptr<Socket> ns3::DGRPacketSink::m_socket private
Listening socket.
Definition at line 165 of file dgr-sink.h.
Referenced by DGRPacketSink(), DoDispose(), GetListeningSocket(), StartApplication(), and StopApplication().
m_socketList
std::list<Ptr<Socket> > ns3::DGRPacketSink::m_socketList private
the accepted sockets
Definition at line 166 of file dgr-sink.h.
Referenced by DoDispose(), GetAcceptedSockets(), HandleAccept(), and StopApplication().
m_tid
TypeId ns3::DGRPacketSink::m_tid private
Protocol TypeId.
Definition at line 170 of file dgr-sink.h.
Referenced by GetTypeId(), and StartApplication().
m_totalRx
uint64_t ns3::DGRPacketSink::m_totalRx private
Total bytes received.
Definition at line 169 of file dgr-sink.h.
Referenced by DGRPacketSink(), GetTotalRx(), and HandleRead().
The documentation for this class was generated from the following files:
model/dgr-sink.h
model/dgr-sink.cc