DGRv2: ns3::DGRRouteManager Class Reference
ns3::DGRRouteManager Class Reference
A global global router.
#include <dgr-route-manager.h>
Static Public Member Functions
static uint32_t AllocateRouterId ()
Allocate a 32-bit router ID from monotonically increasing counter.
static void BuildDGRRoutingDatabase ()
Build the routing database by gathering Link State Advertisements from each node exporting a DGRRouter interface.
static void DeleteDGRRoutes ()
Delete all static routes on all nodes that have a DGRRouterInterface.
static void InitializeRoutes ()
Compute routes using a Dijkstra SPF computation and populate per-node forwarding tables.
Private Member Functions
DGRRouteManager (DGRRouteManager &srm)
Global Route Manager copy construction is disallowed.
DGRRouteManager & operator= (DGRRouteManager &srm)
Global Router copy assignment operator is disallowed.
Detailed Description
A global global router.
This singleton object can query interface each node in the system for a DGRRouter interface. For those nodes, it fetches one or more Link State Advertisements and stores them in a local database. Then, it can compute shortest paths on a per-node basis to all routers, and finally configure each of the node's forwarding tables.
The design is guided by OSPFv2 \RFC{2328} section 16.1.1 and quagga ospfd.
Definition at line 40 of file dgr-route-manager.h.
Constructor & Destructor Documentation
DGRRouteManager()
ns3::DGRRouteManager::DGRRouteManager (DGRRouteManager & srm) private
Global Route Manager copy construction is disallowed.
There's no need for it and a compiler provided shallow copy would be wrong.
Parameters
srm object to copy from
Member Function Documentation
AllocateRouterId()
uint32_t ns3::DGRRouteManager::AllocateRouterId (void) static
Allocate a 32-bit router ID from monotonically increasing counter.
Returns
A new new RouterId.
Definition at line 62 of file dgr-route-manager.cc.
Referenced by ns3::DGRRouter::DGRRouter().
BuildDGRRoutingDatabase()
void ns3::DGRRouteManager::BuildDGRRoutingDatabase (void) static
Build the routing database by gathering Link State Advertisements from each node exporting a DGRRouter interface.
Definition at line 46 of file dgr-route-manager.cc.
References BuildDGRRoutingDatabase().
Referenced by BuildDGRRoutingDatabase(), ns3::Ipv4DGRRouting::NotifyAddAddress(), ns3::Ipv4DGRRouting::NotifyInterfaceDown(), ns3::Ipv4DGRRouting::NotifyInterfaceUp(), ns3::Ipv4DGRRouting::NotifyRemoveAddress(), ns3::Ipv4DGRRoutingHelper::PopulateRoutingTables(), and ns3::Ipv4DGRRoutingHelper::RecomputeRoutingTables().
DeleteDGRRoutes()
void ns3::DGRRouteManager::DeleteDGRRoutes () static
Delete all static routes on all nodes that have a DGRRouterInterface.
Definition at line 38 of file dgr-route-manager.cc.
References DeleteDGRRoutes().
Referenced by DeleteDGRRoutes(), ns3::Ipv4DGRRouting::NotifyAddAddress(), ns3::Ipv4DGRRouting::NotifyInterfaceDown(), ns3::Ipv4DGRRouting::NotifyInterfaceUp(), ns3::Ipv4DGRRouting::NotifyRemoveAddress(), and ns3::Ipv4DGRRoutingHelper::RecomputeRoutingTables().
InitializeRoutes()
void ns3::DGRRouteManager::InitializeRoutes (void) static
Compute routes using a Dijkstra SPF computation and populate per-node forwarding tables.
Definition at line 54 of file dgr-route-manager.cc.
References InitializeRoutes().
Referenced by InitializeRoutes(), ns3::Ipv4DGRRouting::NotifyAddAddress(), ns3::Ipv4DGRRouting::NotifyInterfaceDown(), ns3::Ipv4DGRRouting::NotifyInterfaceUp(), ns3::Ipv4DGRRouting::NotifyRemoveAddress(), ns3::Ipv4DGRRoutingHelper::PopulateRoutingTables(), and ns3::Ipv4DGRRoutingHelper::RecomputeRoutingTables().
operator=()
DGRRouteManager & ns3::DGRRouteManager::operator= (DGRRouteManager & srm) private
Global Router copy assignment operator is disallowed.
There's no need for it and a compiler provided shallow copy would be wrong.
Parameters
srm object to copy from
Returns
the copied object
The documentation for this class was generated from the following files:
model/dgr-route-manager.h
model/dgr-route-manager.cc