DGRv2: ns3::DgrNse Class Reference
ns3::DgrNse Class Reference
dgr v2 Neighbor Status Entry (NSE)
#include <dgr-header.h>
Public Member Functions
DgrNse ()
uint32_t Deserialize (Buffer::Iterator start) override
Deserialize the packet.
TypeId GetInstanceTypeId () const override
Return the instance type identifier.
uint32_t GetInterface () const
Get the iface.
uint32_t GetSerializedSize () const override
Get the serialized size of the packet.
uint32_t GetState () const
void Print (std::ostream &os) const override
void Serialize (Buffer::Iterator start) const override
Serialize the packet.
void SetInterface (uint32_t iface)
Set the interface.
void SetState (uint32_t state)
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Private Attributes
uint32_t m_iface
uint32_t m_state
Detailed Description
dgr v2 Neighbor Status Entry (NSE)
Definition at line 25 of file dgr-header.h.
Constructor & Destructor Documentation
DgrNse()
ns3::DgrNse::DgrNse ()
Definition at line 16 of file dgr-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::DgrNse::Deserialize (Buffer::Iterator start) override
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Definition at line 59 of file dgr-header.cc.
References GetSerializedSize(), ns3::i, m_iface, and m_state.
Referenced by ns3::DgrHeader::Deserialize().
GetInstanceTypeId()
TypeId ns3::DgrNse::GetInstanceTypeId () const override
Return the instance type identifier.
Returns
Instance type ID.
Definition at line 33 of file dgr-header.cc.
References GetTypeId().
GetInterface()
uint32_t ns3::DgrNse::GetInterface () const
Get the iface.
Returns
the iface
Definition at line 74 of file dgr-header.cc.
References m_iface.
GetSerializedSize()
uint32_t ns3::DgrNse::GetSerializedSize () const override
Get the serialized size of the packet.
Returns
size
Definition at line 45 of file dgr-header.cc.
Referenced by Deserialize(), ns3::DgrHeader::Deserialize(), ns3::Ipv4DGRRouting::DoSendNeighborStatusUpdate(), and ns3::DgrHeader::GetSerializedSize().
GetState()
uint32_t ns3::DgrNse::GetState () const
Definition at line 86 of file dgr-header.cc.
References m_state.
GetTypeId()
TypeId ns3::DgrNse::GetTypeId () static
Get the type ID.
Returns
The object TypeId
Definition at line 23 of file dgr-header.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::DgrNse::Print (std::ostream & os) const override
Definition at line 39 of file dgr-header.cc.
References m_iface, and m_state.
Referenced by ns3::operator<<().
Serialize()
void ns3::DgrNse::Serialize (Buffer::Iterator start) const override
Serialize the packet.
Parameters
start Buffer iterator
Definition at line 51 of file dgr-header.cc.
References ns3::i, m_iface, and m_state.
SetInterface()
void ns3::DgrNse::SetInterface (uint32_t iface)
Set the interface.
Parameters
command the interface
Definition at line 68 of file dgr-header.cc.
References m_iface.
Referenced by ns3::Ipv4DGRRouting::DoSendNeighborStatusUpdate().
SetState()
void ns3::DgrNse::SetState (uint32_t state)
Definition at line 80 of file dgr-header.cc.
References m_state.
Referenced by ns3::Ipv4DGRRouting::DoSendNeighborStatusUpdate().
Member Data Documentation
m_iface
uint32_t ns3::DgrNse::m_iface private
Definition at line 78 of file dgr-header.h.
Referenced by Deserialize(), GetInterface(), Print(), Serialize(), and SetInterface().
m_state
uint32_t ns3::DgrNse::m_state private
Definition at line 79 of file dgr-header.h.
Referenced by Deserialize(), GetState(), Print(), Serialize(), and SetState().
The documentation for this class was generated from the following files:
model/dgr-header.h
model/dgr-header.cc