DGRv2: ns3 Namespace Reference
ns3 Namespace Reference
Functions
NS_LOG_COMPONENT_DEFINE ("BudgetTag")
NS_LOG_COMPONENT_DEFINE ("DGRCandidateQueue")
NS_LOG_COMPONENT_DEFINE ("DgrHeader")
NS_LOG_COMPONENT_DEFINE ("DGRPacketSink")
NS_LOG_COMPONENT_DEFINE ("DGRRouteManager")
NS_LOG_COMPONENT_DEFINE ("DGRRouteManagerImpl")
NS_LOG_COMPONENT_DEFINE ("DGRRouter")
NS_LOG_COMPONENT_DEFINE ("DGRRoutingHelper")
NS_LOG_COMPONENT_DEFINE ("DGRTcpApplication")
NS_LOG_COMPONENT_DEFINE ("DGRUdpApplication")
NS_LOG_COMPONENT_DEFINE ("DGRv2QueueDisc")
NS_LOG_COMPONENT_DEFINE ("Ipv4DGRRouting")
NS_LOG_COMPONENT_DEFINE ("Ipv4DGRRoutingTableEntry")
NS_LOG_COMPONENT_DEFINE ("NeighborStatusDatabase")
NS_OBJECT_ENSURE_REGISTERED (BudgetTag)
NS_OBJECT_ENSURE_REGISTERED (DgrHeader)
NS_OBJECT_ENSURE_REGISTERED (DgrNSDB)
NS_OBJECT_ENSURE_REGISTERED (DgrNse)
NS_OBJECT_ENSURE_REGISTERED (DGRPacketSink)
NS_OBJECT_ENSURE_REGISTERED (DGRRouter)
NS_OBJECT_ENSURE_REGISTERED (DGRTcpApplication)
NS_OBJECT_ENSURE_REGISTERED (DGRUdpApplication)
NS_OBJECT_ENSURE_REGISTERED (DGRv2QueueDisc)
NS_OBJECT_ENSURE_REGISTERED (DistTag)
NS_OBJECT_ENSURE_REGISTERED (FlagTag)
NS_OBJECT_ENSURE_REGISTERED (Ipv4DGRRouting)
NS_OBJECT_ENSURE_REGISTERED (NSTag)
NS_OBJECT_ENSURE_REGISTERED (PriorityTag)
std::ostream & operator<< (std::ostream &os, const DGRCandidateQueue &q)
std::ostream & operator<< (std::ostream &os, const DgrHeader &h)
std::ostream & operator<< (std::ostream &os, const DgrNse &h)
std::ostream & operator<< (std::ostream &os, const DGRVertex::ListOfDGRVertex_t &vs)
std::ostream & operator<< (std::ostream &os, const DGRVertex::NodeExit_t &exit)
Stream insertion operator.
std::ostream & operator<< (std::ostream &os, const DGRVertex::VertexType &t)
Stream insertion operator.
std::ostream & operator<< (std::ostream &os, DGRRoutingLSA &lsa)
std::ostream & operator<< (std::ostream &os, Ipv4DGRRoutingTableEntry const &route)
bool operator== (const Ipv4DGRRoutingTableEntry a, const Ipv4DGRRoutingTableEntry b)
Variables
int i = 0
Function Documentation
NS_LOG_COMPONENT_DEFINE() [1/14]
ns3::NS_LOG_COMPONENT_DEFINE ("BudgetTag")
NS_LOG_COMPONENT_DEFINE() [2/14]
ns3::NS_LOG_COMPONENT_DEFINE ("DGRCandidateQueue")
NS_LOG_COMPONENT_DEFINE() [3/14]
ns3::NS_LOG_COMPONENT_DEFINE ("DgrHeader")
NS_LOG_COMPONENT_DEFINE() [4/14]
ns3::NS_LOG_COMPONENT_DEFINE ("DGRPacketSink")
NS_LOG_COMPONENT_DEFINE() [5/14]
ns3::NS_LOG_COMPONENT_DEFINE ("DGRRouteManager")
NS_LOG_COMPONENT_DEFINE() [6/14]
ns3::NS_LOG_COMPONENT_DEFINE ("DGRRouteManagerImpl")
NS_LOG_COMPONENT_DEFINE() [7/14]
ns3::NS_LOG_COMPONENT_DEFINE ("DGRRouter")
NS_LOG_COMPONENT_DEFINE() [8/14]
ns3::NS_LOG_COMPONENT_DEFINE ("DGRRoutingHelper")
NS_LOG_COMPONENT_DEFINE() [9/14]
ns3::NS_LOG_COMPONENT_DEFINE ("DGRTcpApplication")
NS_LOG_COMPONENT_DEFINE() [10/14]
ns3::NS_LOG_COMPONENT_DEFINE ("DGRUdpApplication")
NS_LOG_COMPONENT_DEFINE() [11/14]
ns3::NS_LOG_COMPONENT_DEFINE ("DGRv2QueueDisc")
NS_LOG_COMPONENT_DEFINE() [12/14]
ns3::NS_LOG_COMPONENT_DEFINE ("Ipv4DGRRouting")
NS_LOG_COMPONENT_DEFINE() [13/14]
ns3::NS_LOG_COMPONENT_DEFINE ("Ipv4DGRRoutingTableEntry")
NS_LOG_COMPONENT_DEFINE() [14/14]
ns3::NS_LOG_COMPONENT_DEFINE ("NeighborStatusDatabase")
NS_OBJECT_ENSURE_REGISTERED() [1/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (BudgetTag)
NS_OBJECT_ENSURE_REGISTERED() [2/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (DgrHeader)
References NS_OBJECT_ENSURE_REGISTERED().
NS_OBJECT_ENSURE_REGISTERED() [3/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (DgrNSDB)
References NS_OBJECT_ENSURE_REGISTERED().
NS_OBJECT_ENSURE_REGISTERED() [4/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (DgrNse)
Referenced by NS_OBJECT_ENSURE_REGISTERED(), NS_OBJECT_ENSURE_REGISTERED(), and NS_OBJECT_ENSURE_REGISTERED().
NS_OBJECT_ENSURE_REGISTERED() [5/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (DGRPacketSink)
NS_OBJECT_ENSURE_REGISTERED() [6/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (DGRRouter)
References NS_OBJECT_ENSURE_REGISTERED().
NS_OBJECT_ENSURE_REGISTERED() [7/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (DGRTcpApplication)
NS_OBJECT_ENSURE_REGISTERED() [8/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (DGRUdpApplication)
NS_OBJECT_ENSURE_REGISTERED() [9/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (DGRv2QueueDisc)
NS_OBJECT_ENSURE_REGISTERED() [10/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (DistTag)
NS_OBJECT_ENSURE_REGISTERED() [11/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (FlagTag)
NS_OBJECT_ENSURE_REGISTERED() [12/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (Ipv4DGRRouting)
NS_OBJECT_ENSURE_REGISTERED() [13/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (NSTag)
NS_OBJECT_ENSURE_REGISTERED() [14/14]
ns3::NS_OBJECT_ENSURE_REGISTERED (PriorityTag)
operator<<() [1/8]
std::ostream & ns3::operator<< (std::ostream & os, const DGRCandidateQueue & q)
Definition at line 49 of file dgr-candidate-queue.cc.
operator<<() [2/8]
std::ostream & ns3::operator<< (std::ostream & os, const DgrHeader & h)
Definition at line 237 of file dgr-header.cc.
operator<<() [3/8]
std::ostream & ns3::operator<< (std::ostream & os, const DgrNse & h)
Definition at line 91 of file dgr-header.cc.
operator<<() [4/8]
std::ostream & ns3::operator<< (std::ostream & os, const DGRVertex::ListOfDGRVertex_t & vs)
Definition at line 62 of file dgr-route-manager-impl.cc.
operator<<() [5/8]
std::ostream & ns3::operator<< (std::ostream & os, const DGRVertex::NodeExit_t & exit)
Stream insertion operator.
Parameters
os the reference to the output stream
exit the exit node
Returns
the reference to the output stream
Definition at line 55 of file dgr-route-manager-impl.cc.
operator<<() [6/8]
std::ostream & ns3::operator<< (std::ostream & os, const DGRVertex::VertexType & t)
Stream insertion operator.
Parameters
os the reference to the output stream
t the DGRVertex type
Returns
the reference to the output stream
Definition at line 37 of file dgr-candidate-queue.cc.
operator<<() [7/8]
std::ostream & ns3::operator<< (std::ostream & os, DGRRoutingLSA & lsa)
Definition at line 496 of file dgr-router-interface.cc.
operator<<() [8/8]
std::ostream & ns3::operator<< (std::ostream & os, Ipv4DGRRoutingTableEntry const & route)
Definition at line 271 of file ipv4-dgr-routing-table-entry.cc.
operator==()
bool ns3::operator== (const Ipv4DGRRoutingTableEntry a, const Ipv4DGRRoutingTableEntry b)
Definition at line 315 of file ipv4-dgr-routing-table-entry.cc.
Variable Documentation
i
int ns3::i = 0
Definition at line 169 of file dgr-sink.cc.