DGRv2: ns3::DGRTcpAppHelper Class Reference
ns3::DGRTcpAppHelper Class Reference
A helper to make it easier to instantiate an ns3::BulkSendApplication on a set of nodes.
#include <dgr-tcp-application-helper.h>
Public Member Functions
DGRTcpAppHelper (std::string protocol, Address address)
Create an DGRTcpAppHelper to make it easier to work with BulkSendApplications.
ApplicationContainer Install (NodeContainer c) const
Install an ns3::BulkSendApplication on each node of the input container configured with all the attributes set with SetAttribute.
ApplicationContainer Install (Ptr< Node > node) const
Install an ns3::BulkSendApplication on the node configured with all the attributes set with SetAttribute.
ApplicationContainer Install (std::string nodeName) const
Install an ns3::BulkSendApplication on the node configured with all the attributes set with SetAttribute.
void SetAttribute (std::string name, const AttributeValue &value)
Helper function used to set the underlying application attributes, not the socket attributes.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Install an ns3::BulkSendApplication on the node configured with all the attributes set with SetAttribute.
Private Attributes
ObjectFactory m_factory
Object factory.
Detailed Description
A helper to make it easier to instantiate an ns3::BulkSendApplication on a set of nodes.
Definition at line 22 of file dgr-tcp-application-helper.h.
Constructor & Destructor Documentation
DGRTcpAppHelper()
ns3::DGRTcpAppHelper::DGRTcpAppHelper (std::string protocol, Address address)
Create an DGRTcpAppHelper to make it easier to work with BulkSendApplications.
Parameters
protocol the name of the protocol to use to send traffic by the applications. This string identifies the socket factory type used to create sockets for the applications. A typical value would be ns3::UdpSocketFactory.
address the address of the remote node to send traffic to.
Definition at line 11 of file dgr-tcp-application-helper.cc.
References m_factory.
Member Function Documentation
Install() [1/3]
ApplicationContainer ns3::DGRTcpAppHelper::Install (NodeContainer c) const
Install an ns3::BulkSendApplication on each node of the input container configured with all the attributes set with SetAttribute.
Parameters
c NodeContainer of the set of nodes on which an BulkSendApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 38 of file dgr-tcp-application-helper.cc.
References ns3::i, and InstallPriv().
Install() [2/3]
ApplicationContainer ns3::DGRTcpAppHelper::Install (Ptr< Node > node) const
Install an ns3::BulkSendApplication on the node configured with all the attributes set with SetAttribute.
Parameters
node The node on which an BulkSendApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 25 of file dgr-tcp-application-helper.cc.
References InstallPriv().
Install() [3/3]
ApplicationContainer ns3::DGRTcpAppHelper::Install (std::string nodeName) const
Install an ns3::BulkSendApplication on the node configured with all the attributes set with SetAttribute.
Parameters
nodeName The node on which an BulkSendApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 31 of file dgr-tcp-application-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::DGRTcpAppHelper::InstallPriv (Ptr< Node > node) const private
Install an ns3::BulkSendApplication on the node configured with all the attributes set with SetAttribute.
Parameters
node The node on which an BulkSendApplication will be installed.
Returns
Ptr to the application installed.
Definition at line 50 of file dgr-tcp-application-helper.cc.
References m_factory.
Referenced by Install(), Install(), and Install().
SetAttribute()
void ns3::DGRTcpAppHelper::SetAttribute (std::string name, const AttributeValue & value)
Helper function used to set the underlying application attributes, not the socket attributes.
Parameters
name the name of the application attribute to set
value the value of the application attribute to set
Definition at line 19 of file dgr-tcp-application-helper.cc.
References m_factory.
Member Data Documentation
m_factory
ObjectFactory ns3::DGRTcpAppHelper::m_factory private
Object factory.
Definition at line 84 of file dgr-tcp-application-helper.h.
Referenced by DGRTcpAppHelper(), InstallPriv(), and SetAttribute().
The documentation for this class was generated from the following files:
helper/dgr-tcp-application-helper.h
helper/dgr-tcp-application-helper.cc