DGRv2: ns3::DGRRouteManagerImpl Class Reference
ns3::DGRRouteManagerImpl Class Reference
A global router implementation.
#include <dgr-route-manager-impl.h>
Public Member Functions
DGRRouteManagerImpl ()
virtual ~DGRRouteManagerImpl ()
virtual void BuildDGRRoutingDatabase ()
Build the routing database by gathering Link State Advertisements from each node exporting a DGRRouter interface.
void DebugSPFCalculate (Ipv4Address root)
Debugging routine; call the core SPF from the unit tests.
void DebugUseLsdb (DGRRouteManagerLSDB *)
Debugging routine; allow client code to supply a pre-built LSDB.
virtual void DeleteDGRRoutes ()
Delete all static routes on all nodes that have a DGRRouterInterface.
virtual void InitializeRoutes ()
Compute routes using a Dijkstra SPF computation and populate per-node forwarding tables.
Private Member Functions
DGRRouteManagerImpl (DGRRouteManagerImpl &srmi)
DGRRouteManagerImpl copy construction is disallowed.
bool CheckForStubNode (Ipv4Address root)
Test if a node is a stub, from an OSPF sense.
void DGRVertexAddParent (DGRVertex *v)
Adds a vertex to the list of children in each of its parents.
int32_t FindOutgoingInterfaceId (Ipv4Address a, Ipv4Mask amask=Ipv4Mask("255.255.255.255"))
Return the interface number corresponding to a given IP address and mask.
DGRRouteManagerImpl & operator= (DGRRouteManagerImpl &srmi)
Global Route Manager Implementation assignment operator is disallowed.
void ProcessASExternals (DGRVertex *v, DGRRoutingLSA *extlsa)
Process Autonomous Systems (AS) External LSA.
void SPFAddASExternal (DGRRoutingLSA *extlsa, DGRVertex *v)
Add an external route to the routing tables.
void SPFCalculate (Ipv4Address root, Ipv4Address initroot, DGRRoutingLinkRecord *l, uint32_t Iface)
Calculate the shortest path first (SPF) tree.
DGRRoutingLinkRecord * SPFGetNextLink (DGRVertex *v, DGRVertex *w, DGRRoutingLinkRecord *prev_link)
Search for a link between two vertices.
void SPFIntraAddRouter (DGRVertex *v, DGRVertex *v_init, Ipv4Address nextHop, uint32_t Iface)
Add a host route to the routing tables.
void SPFIntraAddStub (DGRRoutingLinkRecord *l, DGRVertex *v)
Add a stub to the routing tables.
void SPFIntraAddTransit (DGRVertex *v)
Add a transit to the routing tables.
void SPFNext (DGRVertex *v, DGRCandidateQueue &candidate)
Examine the links in v's LSA and update the list of candidates with any vertices not already on the list.
int SPFNexthopCalculation (DGRVertex *v, DGRVertex *w, DGRRoutingLinkRecord *l, uint32_t distance)
Calculate nexthop from root through V (parent) to vertex W (destination) with given distance from root->W.
void SPFProcessStubs (DGRVertex *v)
Process Stub nodes.
Private Attributes
DGRRouteManagerLSDB * m_lsdb
the Link State DataBase (LSDB) of the Global Route Manager
DGRVertex * m_spfroot
the root node
Detailed Description
A global router implementation.
This singleton object can query interface each node in the system for a DGRRouter interface. For those nodes, it fetches one or more Link State Advertisements and stores them in a local database. Then, it can compute shortest paths on a per-node basis to all routers, and finally configure each of the node's forwarding tables.
The design is guided by OSPFv2 \RFC{2328} section 16.1.1 and quagga ospfd.
Definition at line 713 of file dgr-route-manager-impl.h.
Constructor & Destructor Documentation
DGRRouteManagerImpl() [1/2]
ns3::DGRRouteManagerImpl::DGRRouteManagerImpl ()
Definition at line 541 of file dgr-route-manager-impl.cc.
References m_lsdb.
~DGRRouteManagerImpl()
ns3::DGRRouteManagerImpl::~DGRRouteManagerImpl () virtual
Definition at line 549 of file dgr-route-manager-impl.cc.
References m_lsdb.
DGRRouteManagerImpl() [2/2]
ns3::DGRRouteManagerImpl::DGRRouteManagerImpl (DGRRouteManagerImpl & srmi) private
DGRRouteManagerImpl copy construction is disallowed.
There's no need for it and a compiler provided shallow copy would be wrong.
Parameters
srmi object to copy from
Member Function Documentation
BuildDGRRoutingDatabase()
void ns3::DGRRouteManagerImpl::BuildDGRRoutingDatabase () virtual
Build the routing database by gathering Link State Advertisements from each node exporting a DGRRouter interface.
Definition at line 614 of file dgr-route-manager-impl.cc.
References ns3::DGRRoutingLSA::GetLinkStateId(), ns3::DGRRouter::GetRoutingProtocol(), ns3::i, ns3::DGRRouteManagerLSDB::Insert(), and m_lsdb.
CheckForStubNode()
bool ns3::DGRRouteManagerImpl::CheckForStubNode (Ipv4Address root) private
Test if a node is a stub, from an OSPF sense.
If there is only one link of type 1 or 2, then a default route can safely be added to the next-hop router and SPF does not need to be run
Parameters
root the root node
Returns
true if the node is a stub
Definition at line 1374 of file dgr-route-manager-impl.cc.
References FindOutgoingInterfaceId(), ns3::DGRRoutingLinkRecord::GetLinkData(), ns3::DGRRoutingLinkRecord::GetLinkId(), ns3::DGRRoutingLSA::GetLinkRecord(), ns3::DGRRoutingLSA::GetLinkStateId(), ns3::DGRRoutingLinkRecord::GetLinkType(), ns3::DGRRouteManagerLSDB::GetLSA(), ns3::DGRRoutingLSA::GetNLinkRecords(), ns3::DGRRoutingLSA::GetNode(), ns3::i, m_lsdb, ns3::DGRRoutingLinkRecord::PointToPoint, and ns3::DGRRoutingLinkRecord::TransitNetwork.
Referenced by SPFCalculate().
DebugSPFCalculate()
void ns3::DGRRouteManagerImpl::DebugSPFCalculate (Ipv4Address root)
Debugging routine; call the core SPF from the unit tests.
Parameters
root the root node to start calculations
Definition at line 1361 of file dgr-route-manager-impl.cc.
DebugUseLsdb()
void ns3::DGRRouteManagerImpl::DebugUseLsdb (DGRRouteManagerLSDB * lsdb)
Debugging routine; allow client code to supply a pre-built LSDB.
Definition at line 559 of file dgr-route-manager-impl.cc.
References m_lsdb.
DeleteDGRRoutes()
void ns3::DGRRouteManagerImpl::DeleteDGRRoutes () virtual
Delete all static routes on all nodes that have a DGRRouterInterface.
Todo:
separate manually assigned static routes from static routes that the global routing code injects, and only delete the latter
Definition at line 570 of file dgr-route-manager-impl.cc.
References ns3::DGRRouter::GetRoutingProtocol(), ns3::i, and m_lsdb.
DGRVertexAddParent()
void ns3::DGRRouteManagerImpl::DGRVertexAddParent (DGRVertex * v) private
Adds a vertex to the list of children in each of its parents.
Derived from quagga ospf_vertex_add_parents ()
This is a somewhat oddly named method (blame quagga). Although you might expect it to add a parent to something, it actually adds a vertex to the list of children in each of its parents.
Given a pointer to a vertex, it links back to the vertex's parent that it already has set and adds itself to that vertex's list of children.
Parameters
v the vertex
Definition at line 2299 of file dgr-route-manager-impl.cc.
References ns3::DGRVertex::AddChild(), ns3::DGRVertex::GetParent(), and ns3::i.
Referenced by SPFCalculate(), and SPFNext().
FindOutgoingInterfaceId()
int32_t ns3::DGRRouteManagerImpl::FindOutgoingInterfaceId (Ipv4Address a, Ipv4Mask amask = Ipv4Mask ("255.255.255.255")) private
Return the interface number corresponding to a given IP address and mask.
This is a wrapper around GetInterfaceForPrefix(), but we first have to find the right node pointer to pass to that function. If no such interface is found, return -1 (note: unit test framework for routing assumes -1 to be a legal return value)
Parameters
a the target IP address
amask the target subnet mask
Returns
the outgoing interface number
Definition at line 1972 of file dgr-route-manager-impl.cc.
References ns3::DGRVertex::GetVertexId(), ns3::i, and m_spfroot.
Referenced by CheckForStubNode(), and SPFNexthopCalculation().
InitializeRoutes()
void ns3::DGRRouteManagerImpl::InitializeRoutes () virtual
Compute routes using a Dijkstra SPF computation and populate per-node forwarding tables.
Definition at line 696 of file dgr-route-manager-impl.cc.
References ns3::DGRRoutingLinkRecord::GetLinkData(), ns3::DGRRoutingLinkRecord::GetLinkId(), ns3::DGRRoutingLSA::GetLinkRecord(), ns3::DGRRoutingLSA::GetLinkStateId(), ns3::DGRRoutingLinkRecord::GetLinkType(), ns3::DGRRouteManagerLSDB::GetLSA(), ns3::DGRVertex::GetLSA(), ns3::DGRRoutingLinkRecord::GetMetric(), ns3::DGRRoutingLSA::GetNAttachedRouters(), ns3::DGRRoutingLSA::GetNLinkRecords(), ns3::DGRRouter::GetRoutingProtocol(), ns3::DGRVertex::GetVertexId(), ns3::DGRVertex::GetVertexType(), ns3::i, m_lsdb, ns3::DGRRoutingLinkRecord::PointToPoint, SPFCalculate(), SPFGetNextLink(), ns3::DGRRoutingLinkRecord::StubNetwork, ns3::DGRRoutingLinkRecord::TransitNetwork, ns3::DGRVertex::VertexNetwork, and ns3::DGRVertex::VertexRouter.
operator=()
DGRRouteManagerImpl & ns3::DGRRouteManagerImpl::operator= (DGRRouteManagerImpl & srmi) private
Global Route Manager Implementation assignment operator is disallowed.
There's no need for it and a compiler provided shallow copy would be hopelessly wrong.
Parameters
srmi object to copy from
Returns
the copied object
ProcessASExternals()
void ns3::DGRRouteManagerImpl::ProcessASExternals (DGRVertex * v, DGRRoutingLSA * extlsa) private
Process Autonomous Systems (AS) External LSA.
Parameters
v vertex to be processed
extlsa external LSA
Definition at line 1630 of file dgr-route-manager-impl.cc.
References ns3::DGRRoutingLSA::GetAdvertisingRouter(), ns3::DGRVertex::GetChild(), ns3::DGRRoutingLSA::GetLinkStateId(), ns3::DGRVertex::GetLSA(), ns3::DGRVertex::GetNChildren(), ns3::DGRVertex::GetVertexId(), ns3::DGRVertex::GetVertexType(), ns3::i, ns3::DGRVertex::IsVertexProcessed(), ProcessASExternals(), ns3::DGRVertex::SetVertexProcessed(), SPFAddASExternal(), and ns3::DGRVertex::VertexRouter.
Referenced by ProcessASExternals(), and SPFCalculate().
SPFAddASExternal()
void ns3::DGRRouteManagerImpl::SPFAddASExternal (DGRRoutingLSA * extlsa, DGRVertex * v) private
Add an external route to the routing tables.
Parameters
extlsa the external LSA
v the vertex
Author
Pu Yang get the distance
Definition at line 1664 of file dgr-route-manager-impl.cc.
References ns3::DGRRoutingLSA::GetAdvertisingRouter(), ns3::DGRRoutingLSA::GetLinkStateId(), ns3::DGRVertex::GetLSA(), ns3::DGRRoutingLSA::GetNetworkLSANetworkMask(), ns3::DGRVertex::GetNRootExitDirections(), ns3::DGRVertex::GetRootExitDirection(), ns3::DGRRouter::GetRoutingProtocol(), ns3::DGRVertex::GetVertexId(), ns3::i, and m_spfroot.
Referenced by ProcessASExternals().
SPFCalculate()
void ns3::DGRRouteManagerImpl::SPFCalculate (Ipv4Address root, Ipv4Address initroot, DGRRoutingLinkRecord * l, uint32_t Iface) private
Calculate the shortest path first (SPF) tree.
Equivalent to quagga ospf_spf_calculate
Parameters
root the root node
add the initroot for DGR
Author
Pu Yang
Definition at line 1456 of file dgr-route-manager-impl.cc.
References CheckForStubNode(), ns3::DGRVertex::ClearVertexProcessed(), DGRVertexAddParent(), ns3::DGRRouteManagerLSDB::GetExtLSA(), ns3::DGRRoutingLinkRecord::GetLinkData(), ns3::DGRRoutingLSA::GetLinkStateId(), ns3::DGRRouteManagerLSDB::GetLSA(), ns3::DGRVertex::GetLSA(), ns3::DGRRoutingLinkRecord::GetMetric(), ns3::DGRRouteManagerLSDB::GetNumExtLSAs(), ns3::DGRVertex::GetVertexId(), ns3::DGRVertex::GetVertexType(), ns3::i, ns3::DGRRouteManagerLSDB::Initialize(), ns3::DGRRoutingLSA::LSA_SPF_IN_SPFTREE, m_lsdb, m_spfroot, ns3::DGRCandidateQueue::Pop(), ProcessASExternals(), ns3::DGRVertex::SetDistanceFromRoot(), ns3::DGRRoutingLSA::SetStatus(), ns3::DGRCandidateQueue::Size(), SPFIntraAddRouter(), SPFIntraAddTransit(), SPFNext(), SPFProcessStubs(), ns3::DGRVertex::VertexNetwork, and ns3::DGRVertex::VertexRouter.
Referenced by InitializeRoutes().
SPFGetNextLink()
DGRRoutingLinkRecord * ns3::DGRRouteManagerImpl::SPFGetNextLink (DGRVertex * v, DGRVertex * w, DGRRoutingLinkRecord * prev_link) private
Search for a link between two vertices.
This method is derived from quagga ospf_get_next_link ()
First search the Global Router Link Records of vertex v for one representing a point-to point link to vertex w.
What is done depends on prev_link. Contrary to appearances, prev_link just acts as a flag here. If prev_link is NULL, we return the first Global Router Link Record we find that describes a point-to-point link from v to w. If prev_link is not NULL, we return a Global Router Link Record representing a possible second link from v to w.
Parameters
v first vertex
w second vertex
prev_link the previous link in the list
Returns
the link's record
Definition at line 1283 of file dgr-route-manager-impl.cc.
References ns3::DGRRoutingLinkRecord::GetLinkData(), ns3::DGRRoutingLinkRecord::GetLinkId(), ns3::DGRRoutingLSA::GetLinkRecord(), ns3::DGRVertex::GetLSA(), ns3::DGRVertex::GetVertexId(), and ns3::i.
Referenced by InitializeRoutes(), and SPFNexthopCalculation().
SPFIntraAddRouter()
void ns3::DGRRouteManagerImpl::SPFIntraAddRouter (DGRVertex * v, DGRVertex * v_init, Ipv4Address nextHop, uint32_t Iface) private
Add a host route to the routing tables.
This method is derived from quagga ospf_intra_add_router ()
This is where we are actually going to add the host routes to the routing tables of the individual nodes.
The vertex passed as a parameter has just been added to the SPF tree. This vertex must have a valid m_root_oid, corresponding to the outgoing interface on the root router of the tree that is the first hop on the path to the vertex. The vertex must also have a next hop address, corresponding to the next hop on the path to the vertex. The vertex has an m_lsa field that has some number of link records. For each point to point link record, the m_linkData is the local IP address of the link. This corresponds to a destination IP address, reachable from the root, to which we add a host route.
Parameters
v the vertex
the router Ipv4 Address to write the routing table
Author
Pu Yang
Definition at line 2059 of file dgr-route-manager-impl.cc.
References ns3::DGRVertex::GetDistanceFromRoot(), ns3::DGRRoutingLinkRecord::GetLinkData(), ns3::DGRRoutingLSA::GetLinkRecord(), ns3::DGRRoutingLSA::GetLinkStateId(), ns3::DGRRoutingLinkRecord::GetLinkType(), ns3::DGRVertex::GetLSA(), ns3::DGRRoutingLSA::GetNLinkRecords(), ns3::DGRVertex::GetNRootExitDirections(), ns3::DGRVertex::GetRootExitDirection(), ns3::DGRRouter::GetRoutingProtocol(), ns3::DGRVertex::GetVertexId(), ns3::i, m_spfroot, and ns3::DGRRoutingLinkRecord::PointToPoint.
Referenced by SPFCalculate().
SPFIntraAddStub()
void ns3::DGRRouteManagerImpl::SPFIntraAddStub (DGRRoutingLinkRecord * l, DGRVertex * v) private
Add a stub to the routing tables.
Parameters
l the global routing link record
v the vertex
Definition at line 1832 of file dgr-route-manager-impl.cc.
References ns3::DGRRoutingLinkRecord::GetLinkData(), ns3::DGRRoutingLinkRecord::GetLinkId(), ns3::DGRVertex::GetLSA(), ns3::DGRVertex::GetNRootExitDirections(), ns3::DGRVertex::GetRootExitDirection(), ns3::DGRRouter::GetRoutingProtocol(), ns3::DGRVertex::GetVertexId(), ns3::i, and m_spfroot.
Referenced by SPFProcessStubs().
SPFIntraAddTransit()
void ns3::DGRRouteManagerImpl::SPFIntraAddTransit (DGRVertex * v) private
Add a transit to the routing tables.
Parameters
v the vertex
Definition at line 2181 of file dgr-route-manager-impl.cc.
References ns3::DGRRoutingLSA::GetLinkStateId(), ns3::DGRVertex::GetLSA(), ns3::DGRRoutingLSA::GetNetworkLSANetworkMask(), ns3::DGRVertex::GetNRootExitDirections(), ns3::DGRVertex::GetRootExitDirection(), ns3::DGRRouter::GetRoutingProtocol(), ns3::DGRVertex::GetVertexId(), ns3::i, and m_spfroot.
Referenced by SPFCalculate().
SPFNext()
void ns3::DGRRouteManagerImpl::SPFNext (DGRVertex * v, DGRCandidateQueue & candidate) private
Examine the links in v's LSA and update the list of candidates with any vertices not already on the list.
This method is derived from quagga ospf_spf_next (). See RFC2328 Section 16.1 (2) for further details.
We're passed a parameter v that is a vertex which is already in the SPF tree. A vertex represents a router node. We also get a reference to the SPF candidate queue, which is a priority queue containing the shortest paths to the networks we know about.
We examine the links in v's LSA and update the list of candidates with any vertices not already on the list. If a lower-cost path is found to a vertex already on the candidate list, store the new (lower) cost.
Parameters
v the vertex
candidate the SPF candidate queue
Definition at line 861 of file dgr-route-manager-impl.cc.
References DGRVertexAddParent(), ns3::DGRCandidateQueue::Find(), ns3::DGRRoutingLSA::GetAttachedRouter(), ns3::DGRVertex::GetDistanceFromRoot(), ns3::DGRRoutingLinkRecord::GetLinkId(), ns3::DGRRoutingLSA::GetLinkRecord(), ns3::DGRRoutingLSA::GetLinkStateId(), ns3::DGRRoutingLinkRecord::GetLinkType(), ns3::DGRRouteManagerLSDB::GetLSA(), ns3::DGRVertex::GetLSA(), ns3::DGRRouteManagerLSDB::GetLSAByLinkData(), ns3::DGRRoutingLSA::GetLSType(), ns3::DGRRoutingLinkRecord::GetMetric(), ns3::DGRRoutingLSA::GetNAttachedRouters(), ns3::DGRRoutingLSA::GetNLinkRecords(), ns3::DGRRoutingLSA::GetStatus(), ns3::DGRVertex::GetVertexId(), ns3::DGRVertex::GetVertexType(), ns3::i, ns3::DGRRoutingLSA::LSA_SPF_CANDIDATE, ns3::DGRRoutingLSA::LSA_SPF_IN_SPFTREE, ns3::DGRRoutingLSA::LSA_SPF_NOT_EXPLORED, m_lsdb, ns3::DGRVertex::MergeParent(), ns3::DGRVertex::MergeRootExitDirections(), ns3::DGRRoutingLinkRecord::PointToPoint, ns3::DGRCandidateQueue::Push(), ns3::DGRCandidateQueue::Reorder(), ns3::DGRRoutingLSA::RouterLSA, ns3::DGRRoutingLSA::SetStatus(), SPFNexthopCalculation(), ns3::DGRRoutingLinkRecord::StubNetwork, ns3::DGRRoutingLinkRecord::TransitNetwork, ns3::DGRVertex::VertexNetwork, and ns3::DGRVertex::VertexRouter.
Referenced by SPFCalculate().
SPFNexthopCalculation()
int ns3::DGRRouteManagerImpl::SPFNexthopCalculation (DGRVertex * v, DGRVertex * w, DGRRoutingLinkRecord * l, uint32_t distance) private
Calculate nexthop from root through V (parent) to vertex W (destination) with given distance from root->W.
This method is derived from quagga ospf_nexthop_calculation() 16.1.1. For now, this is greatly simplified from the quagga code
Parameters
v the parent
w the destination
l the link record
distance the target distance
Returns
1 on success
Definition at line 1095 of file dgr-route-manager-impl.cc.
References FindOutgoingInterfaceId(), ns3::DGRRoutingLinkRecord::GetLinkData(), ns3::DGRRoutingLSA::GetLinkStateId(), ns3::DGRVertex::GetLSA(), ns3::DGRRoutingLSA::GetLSType(), ns3::DGRRoutingLSA::GetNetworkLSANetworkMask(), ns3::DGRVertex::GetParent(), ns3::DGRVertex::GetRootExitDirection(), ns3::DGRVertex::GetVertexId(), ns3::DGRVertex::GetVertexType(), ns3::DGRVertex::InheritAllRootExitDirections(), m_spfroot, ns3::DGRRoutingLSA::NetworkLSA, ns3::DGRVertex::SetDistanceFromRoot(), ns3::DGRVertex::SetParent(), ns3::DGRVertex::SetRootExitDirection(), SPFGetNextLink(), ns3::DGRVertex::VertexNetwork, and ns3::DGRVertex::VertexRouter.
Referenced by SPFNext().
SPFProcessStubs()
void ns3::DGRRouteManagerImpl::SPFProcessStubs (DGRVertex * v) private
Process Stub nodes.
Processing logic from RFC 2328, page 166 and quagga ospf_spf_process_stubs () stub link records will exist for point-to-point interfaces and for broadcast interfaces for which no neighboring router can be found
Parameters
v vertex to be processed
Definition at line 1798 of file dgr-route-manager-impl.cc.
References ns3::DGRVertex::GetChild(), ns3::DGRRoutingLinkRecord::GetLinkId(), ns3::DGRRoutingLSA::GetLinkRecord(), ns3::DGRRoutingLSA::GetLinkStateId(), ns3::DGRRoutingLinkRecord::GetLinkType(), ns3::DGRVertex::GetLSA(), ns3::DGRVertex::GetNChildren(), ns3::DGRRoutingLSA::GetNLinkRecords(), ns3::DGRVertex::GetVertexId(), ns3::DGRVertex::GetVertexType(), ns3::i, ns3::DGRVertex::IsVertexProcessed(), ns3::DGRVertex::SetVertexProcessed(), SPFIntraAddStub(), SPFProcessStubs(), ns3::DGRRoutingLinkRecord::StubNetwork, and ns3::DGRVertex::VertexRouter.
Referenced by SPFCalculate(), and SPFProcessStubs().
Member Data Documentation
m_lsdb
DGRRouteManagerLSDB* ns3::DGRRouteManagerImpl::m_lsdb private
the Link State DataBase (LSDB) of the Global Route Manager
Definition at line 771 of file dgr-route-manager-impl.h.
Referenced by DGRRouteManagerImpl(), ~DGRRouteManagerImpl(), BuildDGRRoutingDatabase(), CheckForStubNode(), DebugUseLsdb(), DeleteDGRRoutes(), InitializeRoutes(), SPFCalculate(), and SPFNext().
m_spfroot
DGRVertex* ns3::DGRRouteManagerImpl::m_spfroot private
the root node
Definition at line 770 of file dgr-route-manager-impl.h.
Referenced by FindOutgoingInterfaceId(), SPFAddASExternal(), SPFCalculate(), SPFIntraAddRouter(), SPFIntraAddStub(), SPFIntraAddTransit(), and SPFNexthopCalculation().
The documentation for this class was generated from the following files:
model/dgr-route-manager-impl.h
model/dgr-route-manager-impl.cc